### ISSUE TITLE
Minor fix to Chat RESTful API reference

### ISSUE THREAD

**Issue by jinyuagora** [AgoraIO/Docs-Source#1009]
**Business case**: Minor fix

**Subject Matter Expert**: If any questions, please kindly reach out @haoxiuwen, she will pass your questions to the developers who owns the corresponding features.

**Reviewers**:
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: Chat RESTful API Reference.

**Additional valuable information**: Anything else that will help with this issue.
Use the diff here to locate what to add/remove: https://github.com/AgoraIO/agora_doc_source/pull/2683/files

**Comment by billy-the-fish** [comment]
Pr to staging please. Assign Anastasia as reviewer please.

**Comment by Kishan-Dhakan** [comment]
Closed by #1109
