### ISSUE TITLE
Update 3.x Flutter API ref doc (Voice, video, ILS)

### ISSUE THREAD

**Issue by pmmgithub** [AgoraIO/Docs-Source#1010]
**Business case**: As requested by support colleagues, we added a note about the enum 'videoRenderMode', to remind users that this mode doesn't work on macOS or Windows.

**Subject Matter Expert**: panweikui@agora.io
**Reviewers**:
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: 3.x Flutter API ref doc (Voice, video, ILS)

**Acceptance criteria**: Criteria for this issue to be approved.

**Additional valuable information**: 
[3.x-flutter.zip](https://github.com/AgoraIO/Docs-Source/files/10226183/3.x-flutter.zip)

Please use the attached ZIP file. Thanks!

**Comment by billy-the-fish** [comment]
Hi @pmmgithub, I've just had a look at this, and the HTML output is for the old format. I tried to build from the "v3.7.0-flutter-rtc" but it seems the note is not there. Is there any chance you could give me a tag in the source so I can build the correct docs.  Thanks in advance.

**Comment by pmmgithub** [comment]
Hi @billy-the-fish, I created a latest release that contains the note. Please check this https://github.com/AgoraIO/agora_doc_source/releases/tag/v3.7.0-flutter-rtc-fix

**Comment by billy-the-fish** [comment]
Truly awesome, thanks muchly @pmmgithub. you are the best. 

@nirm2009, I've generated the API refs from the latest source, [Archive.zip](https://github.com/AgoraIO/Docs-Source/files/10731549/Archive.zip) please put use them for the PR. As this is the new style, you need to double check that the links work before we publish. Big clue, push your changes and generate an API ref instance in vercel, then update a couple of path links locally in the flutter 3.x docs and check they work. If you have any problems, ping me.
