### ISSUE TITLE
Create the product overview page for MA

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#1016]
**Business case**: Give a holistic overview of MA

**Subject Matter Expert**: 
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: use the information in https://docs-preprod.agora.io/en/RTSA/product_rtsa?platform=All%20Platforms to create a product overview with Garrett. 

**Acceptance criteria**: Page follows the same style as the other product overview. 

Additional valuable information: Branches for all tickets must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone-43-media-accelerator.

**Comment by atovpeko** [comment]
Status: Waiting for a finalized IoT marketing page to update the overview page accordingly
