### ISSUE TITLE
Wrong value for parameter :role

### ISSUE THREAD

**Issue by EmmaAzureAgora** [AgoraIO/Docs-Source#1033]
The document describes the parameter :role below:
_:role is the user role

Use 1 for publisher, 2 for subscriber._

However if I use 1 or 2, it always gives me the token with subscriber privilege. The parameter value must be "publisher" or "subscriber" instead of the number.
Here the example.
http://localhost:8080/rtc/emmatest/publisher/uid/123/

**Comment by billy-the-fish** [comment]
Pr to staging please. Assign Anastasia as reviewer please.

**Comment by EmmaAzureAgora** [comment]
Sorry. The original doc link is: https://docs.agora.io/en/video-calling/develop/authentication-workflow?platform=flutter
The parameter I mentioned is as this screenshot:
https://paste.pics/79e69431a7086df4cca25f939c6ae36b
