### ISSUE TITLE
Update the quick start for this new release. 

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#1035]
**Business case**: There is a new repo for the demo for this release. Update to use the new one. 

**Subject Matter Expert**: 
  - *Technical*: Kyle
  - *Language*: @atovpeko 
  - *PM*: 

**Scope**:  It appears that the flexible classroom now uses a different repo. Check against the CN docs and update the procedure accordingly.  
- Doc to update: https://docs.agora.io/en/flexible-classroom/get-started/?platform=android
- Source to check against: https://docs.agora.io/cn/agora-class/agora_class_quickstart_ios
- [x] iOS: 
- [x] Web: 
- [x] Electron: 

**Acceptance criteria**: Criteria for this issue to be approved.

**Additional valuable information**: All branches must be made from and merged to: https://github.com/AgoraIO/Docs-Source/tree/milestone44-flexible-classroom-2.8.0

**Comment by billy-the-fish** [comment]
Can you check for all platforms please.

**Comment by Kishan-Dhakan** [comment]
Done for these 3 platforms in https://github.com/AgoraIO/Docs-Source/pull/1061

**Comment by Kishan-Dhakan** [comment]
Closed by #1061
