### ISSUE TITLE
Update custom classroom UI

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#1039]
**Business case**: How will this issue help our customers.

**Reviewers**:
  - *Technical*: Kyle
  - *Language*: Anastasia
  - *PM*: 

**Scope**: Check https://docs.agora.io/en/flexible-classroom/develop/customize-ui against https://docs.agora.io/cn/agora-class/agora_class_custom_ui_android?platform=Android (for your platform), and update the EN docs of there are any technical changes. 
- [x] Android
- [x]  iOS
- [x] Web
- [x] Electron
-  Somebody change the title to Customize the classroom UI. 

**Acceptance criteria**: Docs are technically correct and follow the google style guide. 

**Additional valuable information**: All branches must be made from and merged to: https://github.com/AgoraIO/Docs-Source/tree/milestone44-flexible-classroom-2.8.0

**Comment by Kishan-Dhakan** [comment]
Closed by #1062
