### ISSUE TITLE
Update Record a class for the latest release

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#1041]
**Business case**: Enable developers to make the best apps using Flexible Classroom

**Reviewers**:
  - *Technical*: Kyle
  - *Language*: Anastasia
  - *PM*: only if essential

**Scope**:  Update  https://docs.agora.io/en/flexible-classroom/develop/record-a-class with new information from https://docs.agora.io/cn/agora-class/agora_class_record?platform=Android. Use the doc for your platform. 
- [x] Android
- [x] iOS 
- [x] Web
- [x] Electron

**Acceptance criteria**: Docs must be technically correct and follow the google style guide. 

**Additional valuable information**: All branches must be made from and merged to: https://github.com/AgoraIO/Docs-Source/tree/milestone44-flexible-classroom-2.8.0

**Comment by Kishan-Dhakan** [comment]
Closed by #1071
