### ISSUE TITLE
Release notes, API refs and version numbers

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#1042]
**Business case**: Enable the users to easily understand and use the features in this release. 

**Reviewers**:
  - *Technical*: Tong Meng
  - *Language*: Iain
  - *PM*: 

**Scope**: Updates to the following:
 - Release notes: https://docs.agora.io/en/video-calling/reference/release-notes, source to be supplied by CN team.  @atovpeko 
 - Default video profile: Update https://docs.agora.io/en/video-calling/develop/ensure-channel-quality?platform=web#video-profile-table to say the default resolution changed from 640x360 to 960x540 @atovpeko 
 - AINS, quality improvement. @billy-the-fish 
 - API reference: for Video SDK and Voice SDK.  Tag to the drop to be supplied by CN team. @billy-the-fish 
 - Version numbers and links to binaries in the doc build. @atovpeko 

**Acceptance criteria**: Docs must be technically correct and follow the google style guide. 

Additional valuable information: All branches must be made from and merged to: https://github.com/AgoraIO/Docs-Source/tree/milestone45-videosdk-4.1.1-native

**Comment by billy-the-fish** [comment]
The release notes are in here: https://github.com/AgoraIO/agora_doc_source/tree/master/markdown/RTC%204.x/en-US. If you could add them to the en docs please @atovpeko.

**Comment by atovpeko** [comment]
@Cilla-luodan are the release notes in https://github.com/AgoraIO/agora_doc_source/tree/master/markdown/RTC%204.x/en-US final?

**Comment by atovpeko** [comment]
Release notes added including 4.1.0-1 for Android

**Comment by billy-the-fish** [comment]
Sooo, review stuff so far: 

Release Notes: 
Review in the format that makes you happy. Will not merge until we get a release date:
- https://docs-staging-ld0zit496-agora-gdxe.vercel.app/en/video-calling/reference/release-notes?platform=android
- https://github.com/AgoraIO/Docs-Source/pull/1156/files
API Ref:
- Video SDK:
  - https://api-reference-staging-86qgpk9rc-agora-gdxe.vercel.app/video-sdk/android/4.x/API/rtc_api_overview_ng.html
  - https://api-reference-staging-86qgpk9rc-agora-gdxe.vercel.app/video-sdk/ios/4.x/API/rtc_api_overview_ng.html
  - https://api-reference-staging-86qgpk9rc-agora-gdxe.vercel.app/video-sdk/macos/4.x/API/rtc_api_overview_ng.html
  - https://api-reference-staging-86qgpk9rc-agora-gdxe.vercel.app/video-sdk/cpp/4.x/API/rtc_api_overview_ng.html
- Voice SDK:
  - https://api-reference-staging-86qgpk9rc-agora-gdxe.vercel.app/voice-sdk/android/4.x/API/rtc_api_overview_ng.html
  - https://api-reference-staging-86qgpk9rc-agora-gdxe.vercel.app/voice-sdk/ios/4.x/API/rtc_api_overview_ng.html
  - https://api-reference-staging-86qgpk9rc-agora-gdxe.vercel.app/voice-sdk/macos/4.x/API/rtc_api_overview_ng.html
  - https://api-reference-staging-86qgpk9rc-agora-gdxe.vercel.app/voice-sdk/cpp/4.x/API/rtc_api_overview_ng.html
Downloads:
   Waiting for the final URLs.

**Comment by atovpeko** [comment]
Upon clarification in [this issue](https://github.com/AgoraIO/Docs-Source/issues/1122), I am dropping the  4.1.0-1 note that I added and changing 4.1.0 to 4.1.0-1.
