### ISSUE TITLE
FAQ information

### ISSUE THREAD

**Issue by bkuan** [AgoraIO/Docs-Source#1049]
Hi, a customer was looking for information on common errors in live streaming. I think this helped [here](https://docs-preprod.agora.io/en/live-streaming-premium-legacy/faq/streaminit_error?platform=Web) , but that type of information is hard to find in the new docs. Is information from the FAQ pages  from the old docs mapped to the new one?

**Comment by atovpeko** [comment]
@bkuan I hope Iain's reply above was sufficient, so I'll close this ticket. Please feel free to open a new one if there is something else we can do for you.
