### ISSUE TITLE
IW Jitpack

### ISSUE THREAD

**Issue by jurish-camille** [AgoraIO/Docs-Source#1054]
Hi,

I'm Camille, the Team Lead of CSE Tier1. I see that we are still using Jitpack in the doc of IW however we already migrated to mavenCentral. This is causing issues with the customers. https://docs.agora.io/en/interactive-whiteboard/get-started/get-started-sdk?platform=android#get-

**Comment by billy-the-fish** [comment]
Pr to staging please. Assign Anastasia as reviewer please.
