### ISSUE TITLE
Release notes and API ref updates for 2.8

### ISSUE THREAD

**Issue by pmmgithub** [AgoraIO/Docs-Source#1056]
Hi Iain, please help review and publish the following attached docs:
- (Updated) Classroom client APIs for Web/Electron, Android and iOS
- (Updated) Classroom REST APIs. Please note we didn't have the latest version, so I copied the source file from your docs-source repo and update it.
- (new) Proctor SDK APIs for Web/Electron and iOS
- (new) Release notes
 Feel free to let me know if you have any question. Thanks!
[FCR_2.8.zip](https://github.com/AgoraIO/Docs-Source/files/10301384/FCR_2.8.zip)

**Comment by atovpeko** [comment]
@pmmgithub There is only 1 file for the release notes and 4 platforms. Do I have to copy this same doc in all 4 or edit this file for each based on the platforms specified in brackets? If so, where there are no platforms specified (like for improvements or demo features), does it mean it applies to all 4?

**Comment by atovpeko** [comment]
@pmmgithub thank you for clarifications! Release notes are organized differently in the English docs, so I'd better adjust this one file for different platforms. Otherwise, it will defeat the purpose of having those different platforms as separate tabs. Anyway, thanks again!
