### ISSUE TITLE
Angle brackets in description

### ISSUE THREAD

**Issue by EmmaAzureAgora** [AgoraIO/Docs-Source#1059]
https://docs.agora.io/en/signaling/get-started/run-the-sample-project?platform=ios
The description is not well formatted. There are many angle brackets at step 3 Integrate the Signaling SDK. See this screenshot. 
https://paste.pics/80ef52dfee5295cfa48c3a006ca838c5

**Comment by billy-the-fish** [comment]
Pr to staging please.
