### ISSUE TITLE
MultiPath UDP Beta feature enablement needs to contact with support@agora.io instead of sales.

### ISSUE THREAD

**Issue by EmmaAzureAgora** [AgoraIO/Docs-Source#1064]
https://docs.agora.io/en/video-calling/reference/release-notes?platform=ios#v410
In Release note of 4.1.0, it says to use MPUDP (MultiPath UDP) (Beta), contact with sales-us@agora.io. However sales doesn't know how to enable it technically. Customer should contact with support@agora.io for the beta feature.

**Comment by billy-the-fish** [comment]
PR to master please.
