### ISSUE TITLE
Update api ref for RTC 3.x thanks

### ISSUE THREAD

**Issue by kelzr** [AgoraIO/Docs-Source#1070]
We will send you the API ref zip folder for Java and C++. Please upload and publish them.

**Comment by kelzr** [comment]
C++: 
[372html.zip](https://github.com/AgoraIO/Docs-Source/files/10317966/372html.zip)

**Comment by pmmgithub** [comment]
Java API ref: 
[html.zip](https://github.com/AgoraIO/Docs-Source/files/10318438/html.zip)
