### ISSUE TITLE
signature verification 

### ISSUE THREAD

**Issue by qiuyanli1990** [AgoraIO/Docs-Source#1091]
https://docs.agora.io/en/cloud-recording/reference/rest-api/rest-api-overview#signature-verification#signature-verification

Signature verification sample code is incomplete compared with CN version. 
 
The CN version has different programming languages.  The EN doc only has java and the java code is missing a full function compared with CN version. 

    public static void main(String[] args) {
        String request_body = "{\"eventType\":10,\"noticeId\":\"4eb720f0-8da7-11e9-a43e-53f411c2761f\",\"notifyMs\":1560408533119,\"payload\":{\"a\":\"1\",\"b\":2},\"productId\":1}";
        String secret = "secret";
        System.out.println(hmacSha256(request_body, secret)); //033c62f40f687675f17f0f41f91a40c71c0f134c
    }

**Comment by billy-the-fish** [comment]
@qiuyanli1990, we can't find the CN signature verification doc, can you add the link here please.

**Comment by atovpeko** [comment]
@qiuyanli1990 could you please provide the link to the signature verification doc, as requested by Iain?

**Comment by atovpeko** [comment]
Closing this ticket because we can't find the corresponding doc. Please feel free to open a new ticket, if still relevant, and we'll make sure to address this asap. Thank you.
