### ISSUE TITLE
implement multi-channel live streaming doc for unreal

### ISSUE THREAD

**Issue by hussain-khalid** [AgoraIO/Docs-Source#1092]
Business case - developers need to easily implement Agora functionality using Video SDK in a Unreal game
Fix version - hard release
Subject Matter Expert - Iain. Find the previous style docs here: https://docs-preprod.agora.io/en/live-streaming-premium-4.x-beta/multiple_channel_windows_ng?platform=unrealWrite in C++
Reviewer - team
Scope - The source code is here :doc: https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/blob/main/Agora-Unreal-SDK-CPP-Example/Source/AgoraExample/JoinMultipleChannelWidget.cpp
Acceptance criteria - developers must be able to easily implement video calling functionality for unreal
Milestone branch - https://github.com/AgoraIO/Docs-Source/tree/milestone16-unrealengine

**Comment by billy-the-fish** [comment]
Done: https://github.com/AgoraIO/Docs-Source/pull/1094
