### ISSUE TITLE
Two High-Priority Issues from Customer Feedback

### ISSUE THREAD

**Issue by haoxiuwen** [AgoraIO/Docs-Source#1093]
**Business case**: How will this issue help our customers.

**Subject Matter Expert**: Who the doc team can ask technical questions.

**Reviewers**:
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: The products and documents to be updated. If you are not sure, leave it to Iain. 

**Acceptance criteria**: Criteria for this issue to be approved.

**Additional valuable information**: Anything else that will help with this issue.

**Comment by haoxiuwen** [comment]
Android - Manage local messages
https://docs.agora.io/en/agora-chat/client-api/messages/manage-messages?platform=android#understand-the-tech

Remove the content in the red box because this page presents how to manage local conversations and messages.

![image](https://user-images.githubusercontent.com/95393471/210958048-e41f2724-02cc-40bb-9f6f-7aba287947e5.png)

**Comment by haoxiuwen** [comment]
Reference - Security best practice

https://docs.agora.io/en/agora-chat/reference/security-best-practice?platform=android

The image in the red box on the "Security best practice" page is incorrect.

Please replace it with the image in the green box on the "Secure authentication with tokens" page(https://docs.agora.io/en/agora-chat/develop/authentication?platform=android).


![image](https://user-images.githubusercontent.com/95393471/210958458-85fae83a-0f92-4eaa-b211-fc88dd7cf320.png)

![image](https://user-images.githubusercontent.com/95393471/210959028-e65ae09e-441d-47d7-a27c-796cc5a1a853.png)

**Comment by Kishan-Dhakan** [comment]
@haoxiuwen does deleteConversation need to removed from other platforms as well?

**Comment by haoxiuwen** [comment]
> @haoxiuwen does deleteConversation need to removed from other platforms as well?
Oh, it is unnecessary to delete it.
I have checked this doc of other platforms carefully and find that there are two APIs to present how to delete conversations locally and from the server.  So, I have notified the RD personnel to add the sample code for the API that is used to delete conversations from the server. Soon, I will provide it to you.

**Comment by haoxiuwen** [comment]
For Android:

1. Replace the content in the red box with "Delete a local conversation." or "Deletes a specified conversation locally."
2. Replace the content in the red box with "deleteConversationFromServer: Delete a conversation from the server."
![image](https://user-images.githubusercontent.com/95393471/212298836-d6b88066-3834-4086-860a-88d6c472a05a.png)

Add the following content in the red box:

To delete a conversation on the server, call DeleteConversationFromServer:

```java
ChatClient.getInstance().chatManager().deleteConversationFromServer(conversationId, conversationType, isDeleteServerMessages, new CallBack() {
    @Override
    public void onSuccess() {
        
    }
    @Override
    public void onError(int code, String error) {
    }
});
```

**Comment by haoxiuwen** [comment]
For iOS
1. Replace the content in the first red box with the following:

deleteConversation:  Deletes a local conversation.
deleteConversations: Deletes multiple local conversations.

2. Replace the content in the second red box with the following:

deleteServerConversation: Deletes a conversation from the server.  

![image](https://user-images.githubusercontent.com/95393471/212301741-dfb40592-e0fe-420c-9a9c-15f31103e7e0.png)


Add the following content in the red box:

To delete a conversation on the server, call deleteServerConversation:
```objective-c
[AgoraChatClient.sharedClient.chatManager deleteServerConversation:@"conversationId" conversationType:AgoraChatConversationTypeChat isDeleteServerMessages:YES completion:^(NSString * _Nullable aConversationId, AgoraChatError * _Nullable aError) {
            
    }];
```

![image](https://user-images.githubusercontent.com/95393471/212302600-0352c44e-9547-43ed-af43-b8b968dc0ced.png)

**Comment by Kishan-Dhakan** [comment]
Done the new changes in https://github.com/AgoraIO/Docs-Source/pull/1131.
