### ISSUE TITLE
Doc Update for Flexible Classroom

### ISSUE THREAD

**Issue by pmmgithub** [AgoraIO/Docs-Source#1098]
Hi team, based on the feedback from the engineering team, I made the following doc changes. Please help review and publish the attached MD file, thanks!

Product: Flexible Classroom
Doc: Classroom REST API
Changes:
- Added an API: Create or remove breakout rooms
- fixed typo

[agora_class_restful_api.md](https://github.com/AgoraIO/Docs-Source/files/10380698/agora_class_restful_api.md)

**Comment by billy-the-fish** [comment]
Done
