### ISSUE TITLE
Update the docs for Server Gateway v4.0.1

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#1120]
**Business case**: Enable developers to use the latest features for this product

**Subject Matter Expert**: Who the doc team can ask technical questions.
  - *Technical*:  zhou zheng @Zhou,Zheng,
  - *Language*: Anastasia
  - *PM*: Jennifer

**Scope**: 
   @atovpeko to guide you through the process. 
- Java:
   - API reference: https://github.com/AgoraIO/agora_doc_source/tree/servergateway_4.0.1_en/en-US/markdown/Server-Gateway/API%20reference/java
   - Release notes: https://github.com/AgoraIO/agora_doc_source/blob/servergateway_4.0.1_en/en-US/markdown/Server-Gateway/linux_sdk_releases_java.md
   - Download: https://download.agora.io/rtsasdk/release/Agora-RTC-x86_64-linux-gnu-v4.0.1-20230106_201642-252011.jar
- CPP:
    - API ref: https://github.com/AgoraIO/agora_doc_source/tree/servergateway_4.0.1_en/en-US/markdown/Server-Gateway/API%20reference/cpp
    - Release notes: https://github.com/AgoraIO/agora_doc_source/blob/servergateway_4.0.1_en/en-US/markdown/Server-Gateway/linux_sdk_releases_cpp.md
    - Download: https://download.agora.io/rtsasdk/release/Agora-RTC-x86_64-linux-gnu-v4.0.1-20230114_110348-252911.tgz

**Acceptance criteria**: Criteria for this issue to be approved.

**Additional valuable information**: Anything else that will help with this issue.

**Comment by billy-the-fish** [comment]
@nirm2009 . any chance you could quickly make a branch and have these docs ready on the off chance we ever release.

**Comment by nirm2009** [comment]
Closing the issue due to the reasons Jennifer mentioned:
"this version will not be released, since it did not pass security scan and currently we have moved on to an upcoming new version"
