### ISSUE TITLE
Add Release Notes and Some Documents for Agora Chat V1.1.0

### ISSUE THREAD

**Issue by haoxiuwen** [AgoraIO/Docs-Source#1121]
**Business case**: How will this issue help our customers.

**Subject Matter Expert**: Who the doc team can ask technical questions.

**Reviewers**:
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: The products and documents to be updated. If you are not sure, leave it to Iain. 

**Acceptance criteria**: Criteria for this issue to be approved.

**Additional valuable information**: Anything else that will help with this issue.

**Comment by haoxiuwen** [comment]
Agora Chat V1.1.0 is expected to release at the end of February. As we have a Spring Festival holiday for seven to ten days, for your good understanding of Agora Chat V1.1.0，I will provide the release notes and related docs for V1.1.0. The release notes are not the final draft and may be subject to minor changes in February. 

There are mainly four new features:
1. Adds the function of managing custom chat room attributes.
2. Adds the chat room message delivery prioritization function.
3. Adds pagination parameters in the method to allow users to get the conversation list from the server with pagination.
4. Adds a new method to allow users to delete messages on the server in a unidirectional way.

Notes:

a. For the first feature, documents for all platforms and frameworks are ready. I will provide you for reference. 
b. For the second feature, documents for Android, iOS, and Web are ready. I will provide them to you. This feature is under delevelopment for Unity, Windows, RN, and Windows, and therefore documents will be provided in February.
c. The third and fourth features are under development for some platforms and frameworks and documents will be provided in February.

Besides, API reference packages and SDK links will be provided in February.

**Comment by haoxiuwen** [comment]
Release Notes:

[agora_chat_release_notes_flutter.md](https://github.com/AgoraIO/Docs-Source/files/10430716/agora_chat_release_notes_flutter.md)
[agora_chat_release_notes_ios.md](https://github.com/AgoraIO/Docs-Source/files/10430717/agora_chat_release_notes_ios.md)
[agora_chat_release_notes_rn.md](https://github.com/AgoraIO/Docs-Source/files/10430719/agora_chat_release_notes_rn.md)
[agora_chat_release_notes_unity.md](https://github.com/AgoraIO/Docs-Source/files/10430720/agora_chat_release_notes_unity.md)
[agora_chat_release_notes_web.md](https://github.com/AgoraIO/Docs-Source/files/10430721/agora_chat_release_notes_web.md)
[agora_chat_release_notes_windows.md](https://github.com/AgoraIO/Docs-Source/files/10430722/agora_chat_release_notes_windows.md)
[agora_chat_release_notes_android.md](https://github.com/AgoraIO/Docs-Source/files/10430723/agora_chat_release_notes_android.md)

**Comment by haoxiuwen** [comment]
For the new function of managing custom chat room attributes, see the following documents. 
[agora_chat_chatroom_attributes_flutter.md](https://github.com/AgoraIO/Docs-Source/files/10430742/agora_chat_chatroom_attributes_flutter.md)

[agora_chat_chatroom_attributes_android.md](https://github.com/AgoraIO/Docs-Source/files/10430743/agora_chat_chatroom_attributes_android.md)
[agora_chat_chatroom_attributes_windows.md](https://github.com/AgoraIO/Docs-Source/files/10430744/agora_chat_chatroom_attributes_windows.md)

Such documents present how to manage both basic and custom chat room attributes. Currently, documents on the Agora website only describe how to manage basic chat room attributes, such as chat room name, description, and announcement. You can replace the following documents with those on the Agora website and make necessary adjustments (if any) to the conents.

[agora_chat_chatroom_attributes_web.md](https://github.com/AgoraIO/Docs-Source/files/10430737/agora_chat_chatroom_attributes_web.md)
[agora_chat_chatroom_attributes_unity.md](https://github.com/AgoraIO/Docs-Source/files/10430738/agora_chat_chatroom_attributes_unity.md)
[agora_chat_chatroom_attributes_rn.md](https://github.com/AgoraIO/Docs-Source/files/10430739/agora_chat_chatroom_attributes_rn.md)
[agora_chat_chatroom_attributes_ios.md](https://github.com/AgoraIO/Docs-Source/files/10430740/agora_chat_chatroom_attributes_ios.md)

**Comment by haoxiuwen** [comment]
For the chat room message delivery prioritization function, see the following documents for Android, iOS, and Web.
This function is described in agora_chat_send_receive_message docs, see the differences at the following address:
https://github.com/AgoraIO/agora_doc_source/pull/2746

**Comment by Kishan-Dhakan** [comment]
@haoxiuwen can you provide the updated release notes (to remove the `XXX`)?

**Comment by Kishan-Dhakan** [comment]
@haoxiuwen are there any updated RNs I should know about?

**Comment by Kishan-Dhakan** [comment]
@haoxiuwen when updated release notes are available, feel free to create a new ticket and assign it to me please, thanks.
