### ISSUE TITLE
Update on review

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#1136]
**Business case**: SME requests the following updates before publishing

**Subject Matter Expert**: 
  - *Technical*: Kyle: qianfen@agora.io
  - *Language*: Iain
  - *PM*: 

**Scope**: Email sent to saud with information in it

**Acceptance criteria**: Docs are technically correct and follow the Google Developer Style guide. 

**Additional valuable information**:

**Comment by saudsami** [comment]
I haven't received an email regarding this issue.

**Comment by billy-the-fish** [comment]
Hmm, I sent it to [saudsami@gmail.com](mailto:saudsami@gmail.com), the title is Updated CN Doc for v2.8.0 release

**Comment by saudsami** [comment]
The email address is correct but I cant find the message.

**Comment by billy-the-fish** [comment]
Can you quickly do this so we can release when everyone comes back from holiday please. 

[Document1.pdf](https://github.com/AgoraIO/Docs-Source/files/10507799/Document1.pdf)
