### ISSUE TITLE
Spatial Audio Settings

### ISSUE THREAD

**Issue by maxxfrazer** [AgoraIO/Docs-Source#1140]
**Business case**: There's missing settings from the spatial audio setups. Customers need the correct setup instructions.

**Subject Matter Expert**:

**Reviewers**:
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: All platforms that support spatial audio.

**Acceptance criteria**: Spatial audio confirmed working.

**Additional valuable information**: I have added missing properties for iOS in PR #1139.

**Comment by billy-the-fish** [comment]
Everyone check their platforms please:
- [ ] Android - Saud
- [ ] iOS - Dasun
- [ ] Web - Saud
- [ ] MacOS - Dasun
- [ ] Windows - Hussain
- [ ] Electron - Kishan 
- [ ] Unity - Hussain
- [ ] Flutter - Saud
- [ ] React Native - Kishan
