### ISSUE TITLE
Update the whiteboard pricing doc. 

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#1143]
**Business case**: Correct pricing helps

**Subject Matter Expert**: 
  - *Technical*: Karen Buchhagen
  - *Language*: Iain
  - *PM*: 

**Scope**: https://docs.agora.io/en/interactive-whiteboard/reference/pricing?platform=android to be updated to match:
![image](https://user-images.githubusercontent.com/22094088/214006448-2686ca91-b443-49ff-9025-c9377c7f3969.png)

Why is QBS based pricing in a different doc? Would it be better to be a section in the pricing page? 

**Acceptance criteria**: Doc is technically. 

**Additional valuable information**: Anything else that will help with this issue.

**Comment by atovpeko** [comment]
In the process of being fixed in the scope of https://github.com/AgoraIO/Docs-Source/issues/767
