### ISSUE TITLE
Routine Optimization for Agora Chat

### ISSUE THREAD

**Issue by haoxiuwen** [AgoraIO/Docs-Source#1151]
**Business case**: Routine Optimization for Agora Chat

**Subject Matter Expert**: Who the doc team can ask technical questions.

**Reviewers**:
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: The products and documents to be updated. If you are not sure, leave it to Iain. 

**Acceptance criteria**: Criteria for this issue to be approved.

**Additional valuable information**: The issue involves routine optimization for Agora Chat. The errors are found by our customers, technical support personnel, and writer. This issue is not bound with the product release. You can fix the errors whenever it is convenient to you.

**Comment by haoxiuwen** [comment]
Web - Retrieve messages

Replace the content in the red box with "The starting message ID for query."

![image](https://user-images.githubusercontent.com/95393471/215435814-7a021f10-be04-4c0f-a130-8b5cc6b472b0.png)

**Comment by haoxiuwen** [comment]
Android - Manage chat room members

Replace the content in the red box with` removeChatRoomMembers`.

![image](https://user-images.githubusercontent.com/95393471/215451300-c8de126d-0368-4bb1-8b0b-78701330ff95.png)

**Comment by haoxiuwen** [comment]
Android - Manage chat group members

Replace the content in the red box with the following:

The removed member receives the `onUserRemoved` callback and other members in the group receive the `onMemberExited` callback.

![image](https://user-images.githubusercontent.com/95393471/215452306-2f3c3a7e-5af8-48ea-be0b-f76646f52577.png)

**Comment by haoxiuwen** [comment]
Android - Manage chat room members

Delete `add` in the red box.

![image](https://user-images.githubusercontent.com/95393471/215453609-51d2c88c-831d-4239-878c-80a3fb60fdfc.png)

**Comment by haoxiuwen** [comment]
Routine optimization of various Docs

See the following URL

https://github.com/AgoraIO/agora_doc_source/pull/2762/files

**Comment by haoxiuwen** [comment]
Optimization of the "Secure authentication with tokens" Doc

See the following URL:
https://github.com/AgoraIO/agora_doc_source/pull/2761/files

**Comment by haoxiuwen** [comment]
Routine optimization of RESTful Docs

See the following PRs:

https://github.com/AgoraIO/agora_doc_source/pull/2753/files
https://github.com/AgoraIO/agora_doc_source/pull/2754/files

**Comment by haoxiuwen** [comment]
Optimization of Client API Docs

https://github.com/AgoraIO/agora_doc_source/pull/2781

**Comment by haoxiuwen** [comment]
iOS - Offline Push
Please re-adjust the format of the table by reference to Android push (https://docs.agora.io/en/agora-chat/develop/offline-push?platform=android#set-up-push-notifications).
![image](https://user-images.githubusercontent.com/95393471/217220348-f9c868b0-7a7d-4e68-8aba-c55e091b0be3.png)

**Comment by billy-the-fish** [comment]
HI @haoxiuwen,  Why are you writing the EN docs in another repository? The source for chat is in this repo. You are doubling the work.

**Comment by haoxiuwen** [comment]
@hussain-khalid Please modify the following content:

![image](https://user-images.githubusercontent.com/95393471/218368401-3e663a53-4cea-48f7-899a-491c1cae774e.png)
