### ISSUE TITLE
Validate the code in these docs

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#1152]
**Business case**: ensure the quality of the docs is the best possible

**Subject Matter Expert**: 
  - *Technical*: @hussain-khalid 
  - *Language*: Iain
  - *PM*: Shaocheng

**Scope**: Start with the get started in [milestone16-unrealengine](https://github.com/AgoraIO/Docs-Source/tree/milestone16-unrealengine), follow the doc and check the code works. Update the code if changes are necessary. Then do the same thing for each doc. 

**Acceptance criteria**: All code in the unreal engine works straight from the docs. 

**Additional valuable information**: Work from [milestone16-unrealengine](https://github.com/AgoraIO/Docs-Source/tree/milestone16-unrealengine)

**Comment by Pankajg123** [comment]
Closing the issue, as merged.
