### ISSUE TITLE
Update the Cloud Recording release notes to incorporate new releases

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#1153]
**Business case**: Make users aware of the latest features in Cloud Recording. 

**Subject Matter Expert**: 
  - *Technical*: meirongjun@agora.io
  - *Language*: Iain
  - *PM*: Jennifer

**Scope**: Updates can be made directly in https://github.com/AgoraIO/Docs-Source/blob/staging/cloud-recording/reference/release-notes.md or supplied as a separate markdown file. Please use this ticket to make a branch to work in from staging

**Acceptance criteria**: Docs are technically correct and follow the Google Developer Style Guide. 

**Additional valuable information**: Anything else that will help with this issue.

**Comment by Chuchun1991** [comment]
@atovpeko @billy-the-fish Please add the following content related to 2022.11.20 release:
1. Add the player compatibility to standard mode, and fix the bullet issue.
https://docs.agora.io/en/cloud-recording/reference/rest-api/start#recording-configuration
<img width="800" alt="image" src="https://user-images.githubusercontent.com/78007051/215715040-b33fb727-1f9c-448e-a91e-35ed0ce12655.png">
When using the standard mode to generate MPD files, the player compatibility is as follows:
- macOS: Movist/Chrome (47.0.2526.111+)
- Windows: Media Player/KM Player/VLC Player/Chrome (49.0.2623+)
- Linux: FFplay
CN version:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/78007051/215715267-eeea8c7e-5243-40f7-b706-3e2f6ad1b552.png">
CC [meirongjun@agora.io](mailto:meirongjun@agora.io)

**Comment by billy-the-fish** [comment]
Release notes source: https://github.com/AgoraIO/agora_doc_source/blob/master/en-US/markdown/Recording/release_cloud_recording.md

**Comment by Chuchun1991** [comment]
@atovpeko @billy-the-fish Please add the following content related to 2022.10.20 release:

1. Add the postpone transcoding scene.
<img width="783" alt="image" src="https://user-images.githubusercontent.com/78007051/215723546-9d8a5036-5cd3-4dec-8753-6592df1b0b0b.png">
- `2`: Postpone transcoding. After setting this scene, the recording service transcodes the recording file to generate an MP4 file within 24 hours after recording, and upload the MP4 file to the third-party cloud storage you specify. This scenario only applies to individual recording mode. You need to also set the `appsCollection` parameter in the `start` method.

**Comment by Chuchun1991** [comment]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/78007051/215934956-5bd84bfa-874d-4a22-9b6f-1634445feb91.png">
