### ISSUE TITLE
In audioTransportStatsOfUid some comments are about video 

### ISSUE THREAD

**Issue by Monichen-agora** [AgoraIO/Docs-Source#1154]
https://api-ref.agora.io/en/voice-sdk/ios/4.x/API/class_irtcengineeventhandler.html#ariaid-title50 
in audioTransportStatsOfUid the description of "During a call, when the user receives the video packet sent by the remote user/host, the callback is triggered every 2 seconds."

Does not belong here since it is audioTransport Stats.

**Comment by Suri539** [comment]
The English translation is corrected and is released in v4.1.1. Thanks for spotting this!
