### ISSUE TITLE
Update some REST docs

### ISSUE THREAD

**Issue by kelzr** [AgoraIO/Docs-Source#1166]
Based on feedback from the China technical support team, we have updated the documentation for Agora REST services based on the `api.agora.io` domain name. The primary purpose is to tell users how to ensure the high availability of the service by switching domain names. Chinese documentation for reference: https://confluence.agoralab.co/pages/viewpage.action?pageId=1122011779

I handled Chinese documentation directly with the technical team, I don't know if there is a product manager responsible for this. English documentation can be conducted at your discretion.

**Comment by billy-the-fish** [comment]
Looks really cool, great. 

API refs are owned by you in CN and EN. If you could supply the updates docs in markdown that would be great.

**Comment by billy-the-fish** [comment]
@saudsami,  @frank005, think it would be best to add this information to the Postman collection. What do you think?

**Comment by frank005** [comment]
@billy-the-fish - I agree with your assessment

**Comment by saudsami** [comment]
In Postman documentation you can add your own content only at certain points. 
If we add this content at the collection level, it will create a large chunk of text before the API requests and bury the actual APIs. If we add it at the request level it will have to be repeated with every request.
There is no option to add content to a Reference section at the end of the document.
I suggest we create a new doc with this content, and add a link to it at the collection level in the Postman documentation.

**Comment by kelzr** [comment]
> In Postman documentation you can add your own content only at certain points.
> If we add this content at the collection level, it will create a large chunk of text before the API requests and bury the actual APIs. If we add it at the request level it will have to be repeated with every request.
> There is no option to add content to a Reference section at the end of the document.
> I suggest we create a new doc with this content in the docs repository, and add a link to it at the collection level in the Postman documentation.

I agree with you. This content should be considered as a best practice for integrating REST services, rather than being part of the API Reference. The API Reference is meant to provide detailed information and reference for the APIs we provided. It should not include information on how to integrate the REST services, as that is a separate topic.
