### ISSUE TITLE
Wrong description in onRenderVideoFrame 

### ISSUE THREAD

**Issue by Monichen-agora** [AgoraIO/Docs-Source#1171]
https://api-ref.agora.io/en/voice-sdk/ios/4.x/API/class_ivideoframeobserver.html#class_ivideoframeobserver
This callback is about receiving the remote video, but the description says "get the video data before encoding" --- encoding is for the sender's side processing.  Doc in Chinese does not have this error. 
Recommend changing "before encoding" to "after decoding". 

After you successfully register the video frame observer, the SDK triggers this callback each time it receives a video frame. In this callback, you can get the video data before encoding. You can then process the data according to your particular scenarios.

<img width="871" alt="Screen Shot 2023-02-06 at 11 12 46 AM" src="https://user-images.githubusercontent.com/77456831/217064447-8fba20a7-747c-41ee-b1d9-0acbb18c87d1.png">

**Comment by Cilla-luodan** [comment]
Hi @Monichen-agora , the data returned in this callback is before rendering, as the name of this callback.
I'll change the sentence to: You can get the video data sent from the remote end before rendering in this callback, and then process it according to the particular scenarios.
The CN doc will also be changed to: 你可以在回调中获取远端发送的渲染前的视频数据，xxxx

The updated doc will be released on next Thursday (Beijing time), please let me know if you have further opinions, thanks for the feedback.

**Comment by Monichen-agora** [comment]
Before rending is fine.

**Comment by Cilla-luodan** [comment]
Both CN and EN API ref are ready, and the update request issue has been assigned to @billy-the-fish , issue link: https://github.com/AgoraIO/Docs-Source/issues/1273
