### ISSUE TITLE
No cloud proxy pricing information mentioned in document.

### ISSUE THREAD

**Issue by EmmaAzureAgora** [AgoraIO/Docs-Source#1181]
When user enable proxy in Agora console, the pop-up redirects to proxy document for pricing information. See this picture:
https://ibb.co/n32NgDF
However there is no pricing information at all in this webpage.
https://docs.agora.io/en/video-calling/develop/cloud-proxy?platform=android
There used to be price information like: https://docs-preprod.agora.io/en/Interactive%20Broadcast/cloudproxy_native?platform=Android&versionId=1ed8a4c0-a40c-11ec-83d9-39fb20031be5

**Comment by billy-the-fish** [comment]
Hi, pricing information for all addons/extensions/whatever is now in the pricing page for the product this feature will be used with: https://docs.agora.io/en/video-calling/reference/pricing?platform=android#-pricing-1 .
