### ISSUE TITLE
Update Whiteboard file-conversion RESTful API ref

### ISSUE THREAD

**Issue by Nero-Hu** [AgoraIO/Docs-Source#1186]
Hi Iain, we've made some updates for [Whiteboard file-conversion RESTful API ref](https://docs.agora.io/en/interactive-whiteboard/reference/whiteboard-api/file-conversion?platform=ios#set-task-priority), including a new parameter `imageCompressionLevel` and several small fixes. You can diff it with the current version to see the changes. 

This is the source: [New File Conversion RESTful API Reference.md](https://github.com/AgoraIO/Docs-Source/files/10719296/New.File.Conversion.RESTful.API.Reference.md)

**Comment by billy-the-fish** [comment]
@nirm2009, can you have a quick look at this please.
