### ISSUE TITLE
Update the Flexible Classroom docs for v2.8.10, v2.8.11, and v2.8.12

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#1187]
**Business case**: Enable developers to use the latest features for Flexible Classroom

**Subject Matter Expert**: 
  - *Technical*: 
  - *Language*: Iain
  - *PM*: Kyle

**Scope**: Please update the docs in [milestone44-flexible-classroom-2.8.0](https://github.com/AgoraIO/Docs-Source/tree/milestone44-flexible-classroom-2.8.0) with the following:
* Add to release notes - [release_notes_2.8.10_2.8.12.md](https://github.com/AgoraIO/Docs-Source/files/10722562/release_notes_2.8.10_2.8.12.md)
* EduStore API ref: [Edu_Store_v2.8.10.zip](https://github.com/AgoraIO/Docs-Source/files/10722567/Edu_Store_v2.8.10.zip)
* Links to Demos and samples:
    * Android:
         * Demo: http://10.80.1.174:8090/agora_ad/cloudclass/android/release_2.8.11/Agora_Flexible_for_Android_release_2.8.11_20230112_1405_prod_2738.apk
         * Sample code: https://github.com/AgoraIO-Community/CloudClass-Android/tree/release/2.8.11
    * Web and Electron:
         * Electron for windows demo: https://download.agora.io/edu-apaas/release/Agora_aPaas_Flexible_for_Windows_release_2.8.12_20230206_1530_prod_2836.zip
         * Electron for macOS demo: https://download.agora.io/edu-apaas/release/Agora_aPaas_Flexible_for_MAC_release_2.8.12_20230206_1500_prod_5093.zip
         * Web demo: https://solutions-apaas.agora.io/apaas/app/prod/release_2.8.12/20230206_5094/index.html
         * Web h5 demo: https://solutions-apaas.agora.io/apaas/app/prod/release_2.8.12/20230206_5094/index.html#/h5/join-room
         * Web/Electron sample code: https://github.com/AgoraIO-Community/flexible-classroom-desktop/tree/release/2.8.12
iOS:
         * demo: no need to update
         * sample code: https://github.com/AgoraIO-Community/flexible-classroom-ios/tree/release/2.8.11

**Acceptance criteria**: Docs are technically correct and follow the Google Developer Style Guide. 

**Additional valuable information**: All branches must be made from and merged to: https://github.com/AgoraIO/Docs-Source/tree/milestone44-flexible-classroom-2.8.0

**Comment by atovpeko** [comment]
@billy-the-fish `http://10.80.1.174:8090/agora_ad/cloudclass/android/release_2.8.11/Agora_Flexible_for_Android_release_2.8.11_20230112_1405_prod_2738.apk` neither looks correct, nor works. I followed the previous link format and changed it to `https://download.agora.io/edu-apaas/release/Agora_Flexible_for_Android_release_2.8.11_20230112_1405_prod_2738.apk` which does work
