### ISSUE TITLE
Redirection of Agora Analytics from website to doc is not supposed to appear

### ISSUE THREAD

**Issue by ShonStewart** [AgoraIO/Docs-Source#1190]
When I click "[Product Overview](https://docs.agora.io/en/Agora%20Analytics/aa_guide?platform=All%20Platforms)" from [https://www.agora.io/en/products/agora-analytics/](https://www.agora.io/en/products/agora-analytics/), I see the following redirection page and then the doc.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/17442826/218704034-6869b8c0-0fd2-415d-9806-074113a208c1.png">

I suggest we modify the URL of "Product Overview" to avoid the redirection.

**Comment by billy-the-fish** [comment]
Not sure who to assign this to. @embkim can you assign this to somebody please.

**Comment by samuelwan78** [comment]
This has been updated. Clearing page from CDN cache.
