### ISSUE TITLE
Enable and disable the whiteboard 

### ISSUE THREAD

**Issue by SunGiantor** [AgoraIO/Docs-Source#1191]
This file has been modified, please help update.

https://confluence.agoralab.co/display/PM/Enable+and+disable+the+whiteboard

The details of Enable and disable the whiteboard in version 2.8.x are in this document, please help to update it to the official website

**Comment by pmmgithub** [comment]
Hi Iain, please help update the [Enable and disable the whiteboard](https://docs.agora.io/en/flexible-classroom/develop/disable-whiteboard-module?platform=web) guide. If you have any technical questions you can contact Sun Liang (the issue creator). Thanks!
