### ISSUE TITLE
Sample code  uiMode update

### ISSUE THREAD

**Issue by SunGiantor** [AgoraIO/Docs-Source#1195]
https://docs.agora.io/en/flexible-classroom/develop/integrate-flexible-classroom?platform=web

old:
uiMode: FcrMultiThemeMode.light, // The theme of the classroom UI: FcrMultiThemeMode.light for the light mode, FcrMultiThemeMode.dark for the dark mode. 

new:
uiMode: 'light', // The theme of the classroom UI: light for the light mode,dark for the dark mode.

**Comment by billy-the-fish** [comment]
It now says light and not `light`. Could you update please.

**Comment by SunGiantor** [comment]
'light'

**Comment by SunGiantor** [comment]
uiMode: 'light',
