### ISSUE TITLE
Update RTC 4.1.1 iOS & Android release notes 

### ISSUE THREAD

**Issue by Nero-Hu** [AgoraIO/Docs-Source#1199]
Hi Iain, the description on Super Resolution in the current RTC iOS & Android release notes is not consistent with its CN counterpart. To avoid misunderstanding by users, please update them ASAP. Thanks!

Check this commit to see the changes: https://github.com/AgoraIO/agora_doc_source/commit/1a3339f110e606bf9548724b1a5db155b271ba7b

**Comment by billy-the-fish** [comment]
@atovpeko can you quickly do this so we can publish with the extensions later today please.

**Comment by billy-the-fish** [comment]
Doing this while I release spatial audio and AI noise suppression

**Comment by billy-the-fish** [comment]
Live: https://docs.agora.io/en/video-calling/reference/release-notes?platform=android#improvements
