### ISSUE TITLE
Change Singapore GST from 7% to 8% in the billing guide

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#1200]
**Business case**: Keep up  with the local laws and regulations

**Subject Matter Expert**: 崔焕焕 (Huanhuan) from the Finance team
**Reviewers**:
  - *Technical*: 崔焕焕 (Huanhuan) from the Finance team
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: Billing policies and free-of-charge, https://docs.agora.io/en/interactive-live-streaming/reference/billing-policies?platform=android#charging-7-singapore-goods-and-services-tax

**Acceptance criteria**: 7% Singapore Goods and Services Tax is changed to 8% Singapore Goods and Services Tax

**Additional valuable information**: None

**Comment by billy-the-fish** [comment]
Live: https://docs.agora.io/en/video-calling/reference/billing-policies?platform=android#charging-8-singapore-goods-and-services-tax
