### ISSUE TITLE
Add a resftul api "query specified user"

### ISSUE THREAD

**Issue by SunGiantor** [AgoraIO/Docs-Source#1204]
Reference Chinese document

https://docs.agora.io/cn/agora-class/agora_class_restful_api?platform=Web#%E6%9F%A5%E8%AF%A2%E6%8C%87%E5%AE%9A%E7%94%A8%E6%88%B7

**Comment by pmmgithub** [comment]
Hi Iain @billy-the-fish, please help add a restful API "Query a specific user" to the Flexible Classroom class rest APIs before the `[Query a specified event](https://docs.agora.io/en/flexible-classroom/reference/classroom-api?platform=electron#query-a-specified-event)` section. See the attached file for the API ref doc. Thanks!
[Query a specific user.md](https://github.com/AgoraIO/Docs-Source/files/10789329/Query.a.specific.user.md)
