### ISSUE TITLE
Screen Share for Flutter doesn't have iOS

### ISSUE THREAD

**Issue by tadaspetra** [AgoraIO/Docs-Source#1207]
**Business case**: People will be able to screenshare on iOS

**Subject Matter Expert**: @Meherdeep @maxxfrazer and @tadaspetra

**Reviewers**:
  - *Technical*: @Meherdeep @maxxfrazer 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: The products and documents to be updated. If you are not sure, leave it to Iain. 

**Acceptance criteria**: Criteria for this issue to be approved.

**Additional valuable information**: Anything else that will help with this issue.

**Comment by billy-the-fish** [comment]
Maybe you can ask Dasun to look at this as he has the iOS setup.
