### ISSUE TITLE
Agora Chat V1.1.0 Document

### ISSUE THREAD

**Issue by haoxiuwen** [AgoraIO/Docs-Source#1210]
**Business case**: Agora Chat V1.1.0 Document

**Subject Matter Expert**: Who the doc team can ask technical questions.

**Reviewers**:
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: The products and documents to be updated. If you are not sure, leave it to Iain. 

**Acceptance criteria**: Criteria for this issue to be approved.

**Additional valuable information**: Anything else that will help with this issue.

**Comment by haoxiuwen** [comment]
Custom chat room attributes:
[agora_chat_chatroom_attributes_unity.md](https://github.com/AgoraIO/Docs-Source/files/10811920/agora_chat_chatroom_attributes_unity.md)
[agora_chat_chatroom_attributes_web.md](https://github.com/AgoraIO/Docs-Source/files/10811921/agora_chat_chatroom_attributes_web.md)
[agora_chat_chatroom_attributes_windows.md](https://github.com/AgoraIO/Docs-Source/files/10811922/agora_chat_chatroom_attributes_windows.md)
[agora_chatroom_attributes_rn.md](https://github.com/AgoraIO/Docs-Source/files/10811923/agora_chatroom_attributes_rn.md)
[agora_chat_chatroom_attributes_android.md](https://github.com/AgoraIO/Docs-Source/files/10811924/agora_chat_chatroom_attributes_android.md)
[agora_chat_chatroom_attributes_flutter.md](https://github.com/AgoraIO/Docs-Source/files/10811925/agora_chat_chatroom_attributes_flutter.md)
[agora_chat_chatroom_attributes_ios.md](https://github.com/AgoraIO/Docs-Source/files/10811927/agora_chat_chatroom_attributes_ios.md)

**Comment by haoxiuwen** [comment]
For other document updates, see the following PR:
https://github.com/AgoraIO/agora_doc_source/pull/2815

**Comment by haoxiuwen** [comment]
Release Notes:

[agora_chat_release_notes_unity.md](https://github.com/AgoraIO/Docs-Source/files/10811959/agora_chat_release_notes_unity.md)
[agora_chat_release_notes_web.md](https://github.com/AgoraIO/Docs-Source/files/10811960/agora_chat_release_notes_web.md)
[agora_chat_release_notes_windows.md](https://github.com/AgoraIO/Docs-Source/files/10811961/agora_chat_release_notes_windows.md)
[agora_chat_release_notes_android.md](https://github.com/AgoraIO/Docs-Source/files/10811962/agora_chat_release_notes_android.md)
[agora_chat_release_notes_flutter.md](https://github.com/AgoraIO/Docs-Source/files/10811963/agora_chat_release_notes_flutter.md)
[agora_chat_release_notes_ios.md](https://github.com/AgoraIO/Docs-Source/files/10811964/agora_chat_release_notes_ios.md)
[agora_chat_release_notes_rn.md](https://github.com/AgoraIO/Docs-Source/files/10811965/agora_chat_release_notes_rn.md)

**Comment by jinyuagora** [comment]
**RESTful API reference**:
- Message priority: https://github.com/AgoraIO/agora_doc_source/pull/2789
- Chatroom attributes: https://github.com/AgoraIO/agora_doc_source/pull/2495/files
- Push notification: https://github.com/AgoraIO/agora_doc_source/pull/2790/files

**Comment by haoxiuwen** [comment]
API Reference Packages:

[Chat SDK for Flutter v1.1.0.zip](https://github.com/AgoraIO/Docs-Source/files/10819890/Chat.SDK.for.Flutter.v1.1.0.zip)
[Chat SDK for iOS v1.1.0.zip](https://github.com/AgoraIO/Docs-Source/files/10819891/Chat.SDK.for.iOS.v1.1.0.zip)
[Chat SDK for RN v1.1.0.zip](https://github.com/AgoraIO/Docs-Source/files/10819892/Chat.SDK.for.RN.v1.1.0.zip)
[Chat SDK for Unity v1.1.0.zip](https://github.com/AgoraIO/Docs-Source/files/10819893/Chat.SDK.for.Unity.v1.1.0.zip)
[Chat SDK for Web v1.1.0.zip](https://github.com/AgoraIO/Docs-Source/files/10819894/Chat.SDK.for.Web.v1.1.0.zip)
[Chat SDK for Windows v1.1.0.zip](https://github.com/AgoraIO/Docs-Source/files/10819895/Chat.SDK.for.Windows.v1.1.0.zip)
[Chat SDK for Android v1.1.0.zip](https://github.com/AgoraIO/Docs-Source/files/10819896/Chat.SDK.for.Android.v1.1.0.zip)

**Comment by haoxiuwen** [comment]
Updates to Flutter Quick Start 

Our Flutter developer updates the quick start. Please see the following URL:

https://github.com/AgoraIO/agora_doc_source/pull/2819/files

**Comment by lancezlhuang** [comment]
> **RESTful API reference**
> 
> * Overview & Limitations: [Restful overview & limitations agora_doc_source#2820](https://github.com/AgoraIO/agora_doc_source/pull/2820)
> * Message priority: [message priority agora_doc_source#2789](https://github.com/AgoraIO/agora_doc_source/pull/2789)
> * Chatroom attributes:
>   [Manage chatroom attributes](https://github.com/AgoraIO/Docs-Source/files/10821326/agora_chat_restful_chatroom_attributes.md)
> * Push notification:
>   
>   * [Set push labels](https://github.com/AgoraIO/Docs-Source/files/10821364/agora_chat_restful_push_tag.md)
>   * [Send push notifications](https://github.com/AgoraIO/Docs-Source/files/10821381/agora_chat_restful_send_push_notification.md)
>   * [Set push messages](https://github.com/AgoraIO/Docs-Source/files/10821389/agora_chat_restful_config_push_notification.md)

@haoxiuwen Send push notifications.md: “strategy” part, using us vs 3rd party push services. I believe the duration of us retaining the push messages is not limited to merely 7 days. It varies based on the package each customer subscribes and we need to reflect that in the documentation. Could you help verify this statement with PMs or R&D in China?

**Comment by lancezlhuang** [comment]
> **Business case**: Agora Chat V1.1.0 Document
> 
> **Subject Matter Expert**: Who the doc team can ask technical questions.
> 
> **Reviewers**:
> 
> * _Technical_:
> * _Language_: Iain
> * _PM_: only if essential
> 
> **Scope**: The products and documents to be updated. If you are not sure, leave it to Iain.
> 
> **Acceptance criteria**: Criteria for this issue to be approved.
> 
> **Additional valuable information**: Anything else that will help with this issue.

Technical owner is Zhaoliang (zhaoliang@agora.io). PM of US&RoW is Lance.

**Comment by lancezlhuang** [comment]
> Release Notes:
> 
> [agora_chat_release_notes_unity.md](https://github.com/AgoraIO/Docs-Source/files/10811959/agora_chat_release_notes_unity.md) [agora_chat_release_notes_web.md](https://github.com/AgoraIO/Docs-Source/files/10811960/agora_chat_release_notes_web.md) [agora_chat_release_notes_windows.md](https://github.com/AgoraIO/Docs-Source/files/10811961/agora_chat_release_notes_windows.md) [agora_chat_release_notes_android.md](https://github.com/AgoraIO/Docs-Source/files/10811962/agora_chat_release_notes_android.md) [agora_chat_release_notes_flutter.md](https://github.com/AgoraIO/Docs-Source/files/10811963/agora_chat_release_notes_flutter.md) [agora_chat_release_notes_ios.md](https://github.com/AgoraIO/Docs-Source/files/10811964/agora_chat_release_notes_ios.md) [agora_chat_release_notes_rn.md](https://github.com/AgoraIO/Docs-Source/files/10811965/agora_chat_release_notes_rn.md)

Hi Iain, regarding release note: 
Chat 1.1 introduces some new RESTful APIs and we shall have a place to capture these changes.

**Comment by haoxiuwen** [comment]
> > **RESTful API reference**
> > 
> > * Overview & Limitations: [Restful overview & limitations agora_doc_source#2820](https://github.com/AgoraIO/agora_doc_source/pull/2820)
> > * Message priority: [message priority agora_doc_source#2789](https://github.com/AgoraIO/agora_doc_source/pull/2789)
> > * Chatroom attributes:
> >   [Manage chatroom attributes](https://github.com/AgoraIO/Docs-Source/files/10821326/agora_chat_restful_chatroom_attributes.md)
> > * Push notification:
> >   
> >   * [Set push labels](https://github.com/AgoraIO/Docs-Source/files/10821364/agora_chat_restful_push_tag.md)
> >   * [Send push notifications](https://github.com/AgoraIO/Docs-Source/files/10821381/agora_chat_restful_send_push_notification.md)
> >   * [Set push messages](https://github.com/AgoraIO/Docs-Source/files/10821389/agora_chat_restful_config_push_notification.md)
> 
> @haoxiuwen Send push notifications.md: “strategy” part, using us vs 3rd party push services. I believe the duration of us retaining the push messages is not limited to merely 7 days. It varies based on the package each customer subscribes and we need to reflect that in the documentation. Could you help verify this statement with PMs or R&D in China?
Yes, the retention period varies based on the package each customer subscribes. and I have modified this document in https://github.com/AgoraIO/agora_doc_source/pull/2835/files

**Comment by haoxiuwen** [comment]
@billy-the-fish For the Push RESTful documents, I have make minor changes. 

Please see the following PRs:
https://github.com/AgoraIO/agora_doc_source/pull/2834/files

https://github.com/AgoraIO/agora_doc_source/pull/2835/files

**Comment by haoxiuwen** [comment]
SDK links:

Android: https://download.agora.io/sdk/release/Agora_CHAT_SDK_for_Android_v1_1_0.zip 
iOS: https://download.agora.io/sdk/release/AgoraChat1_1_0.xcframework.zip       
Web: https://www.npmjs.com/package/agora-chat   
Flutter: https://pub.dev/packages/agora_chat_sdk
RN: https://www.npmjs.com/package/react-native-agora-chat  
Unity: https://download.agora.io/sdk/release/agora_chat_unity_sdk1.1.0.unitypackage  
Windows: https://download.agora.io/sdk/release/agora_chat_sdk.1.1.0.nupkg

**Comment by haoxiuwen** [comment]
React Native SDK 1.1.1 

Release Notes:
[agora_chat_release_notes_rn.md](https://github.com/AgoraIO/Docs-Source/files/10919748/agora_chat_release_notes_rn.md)

API Reference Package:


[Chat SDK for RN v1.1.1.zip](https://github.com/AgoraIO/Docs-Source/files/10919756/Chat.SDK.for.RN.v1.1.1.zip)


SDK link:  https://www.npmjs.com/package/react-native-agora-chat

**Comment by atovpeko** [comment]
> **RESTful API reference**
> 
> * Overview & Limitations: [Restful overview & limitations agora_doc_source#2820](https://github.com/AgoraIO/agora_doc_source/pull/2820)
> * Message priority: [message priority agora_doc_source#2789](https://github.com/AgoraIO/agora_doc_source/pull/2789)
> * Chatroom attributes:
>   [Manage chatroom attributes](https://github.com/AgoraIO/Docs-Source/files/10821326/agora_chat_restful_chatroom_attributes.md)
> * Push notification:
>   
>   * [Set push labels](https://github.com/AgoraIO/Docs-Source/files/10821364/agora_chat_restful_push_tag.md)
>   * [Send push notifications](https://github.com/AgoraIO/Docs-Source/files/10821381/agora_chat_restful_send_push_notification.md)
>   * [Set push messages](https://github.com/AgoraIO/Docs-Source/files/10821389/agora_chat_restful_config_push_notification.md)

@jinyuagora the last three are the new docs that need to be housed together with Offline push in a subfolder in chat/reference/RESTful API, correct?

**Comment by jinyuagora** [comment]
> > **RESTful API reference**
> > 
> > * Overview & Limitations: [Restful overview & limitations agora_doc_source#2820](https://github.com/AgoraIO/agora_doc_source/pull/2820)
> > * Message priority: [message priority agora_doc_source#2789](https://github.com/AgoraIO/agora_doc_source/pull/2789)
> > * Chatroom attributes:
> >   [Manage chatroom attributes](https://github.com/AgoraIO/Docs-Source/files/10821326/agora_chat_restful_chatroom_attributes.md)
> > * Push notification:
> >   
> >   * [Set push labels](https://github.com/AgoraIO/Docs-Source/files/10821364/agora_chat_restful_push_tag.md)
> >   * [Send push notifications](https://github.com/AgoraIO/Docs-Source/files/10821381/agora_chat_restful_send_push_notification.md)
> >   * [Set push messages](https://github.com/AgoraIO/Docs-Source/files/10821389/agora_chat_restful_config_push_notification.md)
> 
> @jinyuagora the last three are the new docs that need to be housed together with Offline push in a subfolder in chat/reference/RESTful API, correct?

Correct

**Comment by atovpeko** [comment]
@lancezlhuang regarding your comments:
1. Regarding the chatroom message priority part, I slightly rephrased the paragraph although in my humble it was already quite clear :-). However, to put it under a separate section, I'd need more input on how to actually set the priority. I also don't see a section dedicated to using message extensions. If that needs to be added, again I'll need input. 
2. I have added a little bit of context to the doc about sending push notifications because to me it seems to be the 'main' doc for push, as opposed to configuring the message itself. While at that, I also renamed "Set push message" to "Configure push notification" to avoid using different terms. They are housed under message management, as requested. 
3. For release notes, in other products we have a section called API Changes (see [Signaling example](https://docs.agora.io/en/signaling/reference/release-notes?platform=android#api-changes)). We can add this section to Chat release notes as well, again with input on what the actual changes are. The current provided files seem to be describing the API changes in new features, correct me if I am wrong.

**Comment by haoxiuwen** [comment]
@atovpeko For Push docs are updated in V1.1.0, see https://github.com/AgoraIO/agora_doc_source/pull/2890/files

The updates include the following:
1. Add restrictions on the push label.
2. Add the push API call overage charge.
3. Add the push service in the release notes of each client.

**Comment by haoxiuwen** [comment]
@lancezlhuang @atovpeko @billy-the-fish 

Please use this archive to replace the current Chat iOS v1.1.0 API Reference.

[Chat SDK for iOS v1.1.0.zip](https://github.com/AgoraIO/Docs-Source/files/11300036/Chat.SDK.for.iOS.v1.1.0.zip)

**Comment by haoxiuwen** [comment]
@lancezlhuang @atovpeko @billy-the-fish 
For 1.1.0 demo links: 
1. For iOS and web demos, the current links are correct. 
2. For the Android demo, replace the current one with the following URL： https://download.agora.io/sdk/release/agorachatdemo_android_1.1.0.apk

**Comment by atovpeko** [comment]
@haoxiuwen could you please recheck whether this is the correct archive for Chat iOS v1.1.0 API Reference? The file/folder structure is very different from what we have in the repo

**Comment by lixm1988** [comment]
> @haoxiuwen could you please recheck whether this is the correct archive for Chat iOS v1.1.0 API Reference? The file/folder structure is very different from what we have in the repo

This doccarchive file is built by Xcode 14 and will show both swift and objective-C api reference.It is nicer than current API Reference.

**Comment by haoxiuwen** [comment]
> @haoxiuwen could you please recheck whether this is the correct archive for Chat iOS v1.1.0 API Reference? The file/folder structure is very different from what we have in the repo
Our developer lixm1988 explains the technical details.
This archive is provided according to suggestions of Max. It shows both swift and objective-C api reference.

**Comment by haoxiuwen** [comment]
@lancezlhuang @atovpeko @billy-the-fish 

If you still have issues with the new iOS archive, we can have a meeting at 10:00 am your time (17:00 pm our time). I'd like to know if this time is OK for you.

AVC: doc
