### ISSUE TITLE
Misleading information in docs

### ISSUE THREAD

**Issue by Jeffreyon** [AgoraIO/Docs-Source#1220]
I might be wrong, but the writeup in this [page](https://docs.agora.io/en/agora-chat/get-started/get-started-sdk?platform=web) of the docs seems to be off
![chrome-capture-2023-2-2](https://user-images.githubusercontent.com/60184009/222311191-39962825-3aa4-44bc-b217-788b15349ef1.jpeg)

**Comment by billy-the-fish** [comment]
Will check.

**Comment by atovpeko** [comment]
This page has been updated. If there are still issues with this page, please feel free to open a new ticket. Thank you!
