### ISSUE TITLE
API ref update

### ISSUE THREAD

**Issue by Suri539** [AgoraIO/Docs-Source#1227]
Hi Iain, 
Please update the English API ref according to the tag: [v4.1.1-bugfix-0302 ](https://github.com/AgoraIO/agora_doc_source/releases/tag/v4.1.1-bugfix-0302).
Please note that you need to delete the props="cn" for the following APIs in the ditamaps for all platforms, because they can be released in the English doc now:

setDirectCdnStreamingVideoConfiguration
startDirectCdnStreaming
stopDirectCdnStreaming
onDirectCdnStreamingStateChanged
onDirectCdnStreamingStats
DirectCdnStreamingMediaOptions
DirectCdnStreamingStats
enum_directcdnstreamingerror
enum_directcdnstreamingstate
class_IDirectCdnStreamingEventHandler

It would be great if you can update the English doc before 17, March, 2023. Thanks!

**Comment by Suri539** [comment]
This is the tag for framework platforms: https://github.com/AgoraIO/agora_doc_source/releases/tag/v4.1.0-bugfix-0302-framework

**Comment by atovpeko** [comment]
With 4.2.3 about to be published, I am closing this ticket. Thank you!
