### ISSUE TITLE
RTC 4.x iOS API doc, iOS only has sendCustomReportMessageEx and Android only has sendCustomReportMessage APIs

### ISSUE THREAD

**Issue by Monichen-agora** [AgoraIO/Docs-Source#1248]
iOS
https://api-ref.agora.io/en/video-sdk/ios/4.x/API/class_irtcengineex.html#ariaid-title23

Android
https://api-ref.agora.io/en/voice-sdk/android/4.x/API/class_irtcengine.html#ariaid-title114

Both should be available.

**Comment by billy-the-fish** [comment]
@dengyaxi , can you send me the tag where both methods are included in the API ref source please.

**Comment by Cilla-luodan** [comment]
Hi @Monichen-agora, as you can see, all methods in the EN API ref are organized by interface classes.
The Ex methods are included in the RtcEngineKitEx interface class, and the non-Ex methods are in the RtcEngineKit interface.

Here’re the links might help:
sendCustomReportMessage: https://api-ref.agora.io/en/video-sdk/ios/4.x/API/class_irtcengine.html#ariaid-title116
sendCustomReportMessageEx: https://api-ref.agora.io/en/voice-sdk/android/4.x/API/class_irtcengineex.html#ariaid-title26
