### ISSUE TITLE
UI builder link is wrong!

### ISSUE THREAD

**Issue by KyleQian007** [AgoraIO/Docs-Source#1272]
the correct link should : https://builder.agora.io/ui-builder/index.html, 
can you please update it? 
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/88830230/225824367-ac8db821-a8c2-40ea-9ff6-83226b247aa0.png">

**Comment by billy-the-fish** [comment]
Fixed: https://docs-git-flexible-classroom-updates-agora-gdxe.vercel.app/en/flexible-classroom/get-started/get-started-uibuilder?platform=android. 

Will publish today.
