### ISSUE TITLE
Flexible Classroom iOS Customize the classroom UI link is wrong

### ISSUE THREAD

**Issue by SunGiantor** [AgoraIO/Docs-Source#1276]
Url：https://docs.agora.io/en/flexible-classroom/develop/customize-ui?platform=ios

<img width="1660" alt="image" src="https://user-images.githubusercontent.com/6038975/225884473-88c88db4-bec2-453b-a85e-bb4438d8fa8f.png">

The address of this github should be:
https://github.com/AgoraIO-Community/CloudClass-iOS/tree/release/2.8.11

**Comment by billy-the-fish** [comment]
When you clone the repo you automatically go to the default, which is the latest branch. This step is not necessary. Updated the procedure to match this: https://docs-git-flexible-classroom-updates-agora-gdxe.vercel.app/en/flexible-classroom/develop/customize-ui?platform=ios#1-get-the-source-code-for-. And put in the correct repo :-).
