### ISSUE TITLE
Flexible classroom faq 

### ISSUE THREAD

**Issue by SunGiantor** [AgoraIO/Docs-Source#1302]
Please help supplement the faq related documentation.
<img width="1915" alt="image" src="https://user-images.githubusercontent.com/6038975/227875262-b27d2cc7-0c47-4e0c-af7f-3867249598ac.png">

Please refer to the Chinese document link as follows

https://docs.agora.io/cn/agora-class/faq

<img width="1507" alt="image" src="https://user-images.githubusercontent.com/6038975/227874495-cd382bf1-c5ec-4646-8902-ba9dfe17ff70.png">

**Comment by atovpeko** [comment]
Hi @SunGiantor our help articles are available here: https://docs.agora.io/en/help/integration-issues?platform=all-platforms&product=flexible-classroom If there are missing ones, please open a ticket with a link to the CN source, so we can update it. Thank you!
