### ISSUE TITLE
[Urgent] Update 4.0.0 release notes for all platforms

### ISSUE THREAD

**Issue by Cilla-luodan** [AgoraIO/Docs-Source#1305]
There's an update request to the release notes according to this jira: https://jira.agoralab.co/browse/CSD-55398
Target OS：iOS, Android, Unity (iOS, Android), Flutter (iOS, Android), RN
You can learn the diff from this pr: https://github.com/AgoraIO/agora_doc_source/pull/2873
Please make necessary changes on the number of section titles before you publish.

**Comment by Cilla-luodan** [comment]
Hi @billy-the-fish, a few changes have been made to the release notes of all platforms according to Jennifer's comments.
pr link: https://github.com/AgoraIO/agora_doc_source/pull/2881/files

**Comment by billy-the-fish** [comment]
@atovpeko, can you do this urgently please.
