### ISSUE TITLE
In Unity SDK, Test your implementation section has numbered list that goes 1,2,3...7, 3

### ISSUE THREAD

**Issue by tomkail** [AgoraIO/Docs-Source#1311]
Additionally, the content in 3 might be wrong? CAgoraImplementationDlg doesn't exist on my device and the instruction is confusing.

**Comment by hussain-khalid** [comment]
@tomkail can you share a link to the doc.

**Comment by tomkail** [comment]
Sorry, we’ve given up on Agora. Too many issues! Google the phrases in the
bug desc!
