### ISSUE TITLE
FCR iOS Demo quickstart

### ISSUE THREAD

**Issue by SunGiantor** [AgoraIO/Docs-Source#1327]
hi Iain:
The previous content of iOS's quickstart was correct, but recently it was discovered that the document in this area is incorrect. Has there been any recent updates that have overwritten the content of this document?

https://docs.agora.io/en/flexible-classroom/get-started/?platform=ios

the demo github link is 
git clone https://github.com/AgoraIO-Community/flexible-classroom-ios

The steps to get through the fcr are as follows:
1、git clone https://github.com/AgoraIO-Community/flexible-classroom-ios
2、cd flexible-classroom-ios
3、git checkout release/2.8.11
4、cd App
5、pod install

<img width="648" alt="image" src="https://user-images.githubusercontent.com/6038975/232687389-8ac1c65f-19c2-4958-b4fa-9739bd68f6fa.png">

<img width="1780" alt="image" src="https://user-images.githubusercontent.com/6038975/232677357-9cf28084-3550-4b9b-9e7d-c5bc634fa11f.png">

**Comment by billy-the-fish** [comment]
Awesome spot, thank you. Fixed: https://docs.agora.io/en/flexible-classroom/get-started/?platform=ios.
