### ISSUE TITLE
Downloads, Migration guide and Release notes for React

### ISSUE THREAD

**Issue by Kishan-Dhakan** [AgoraIO/Docs-Source#133]
Business case - developers need to easily be able to refer downloads, migration guides and release notes
Fix version - hard release
Subject Matter Expert - Iain. Ekaansh. Find the SDK, API ref and a get started here: https://docs-preprod.agora.io/en/live-streaming-premium-4.x-beta/landing-page?platform=React%20Native
Reviewer - @saudsami 
Scope - ILS, Video SDK, Voice SDK
Video SDK: download is https://docs.agora.io/en/video-call-4.x-beta/downloads?platform=All%20Platforms
Voice SDK: download is https://docs.agora.io/en/voice-call-4.x-beta/downloads?platform=All%20Platforms.
Acceptance criteria - developers must be able to easily be able to refer downloads, migration guides and release notes
Milestone branch -  https://github.com/AgoraIO/Docs-Source/tree/milestone4-react-native-documentation

**Comment by lemon-chen** [comment]
Migration guide for React Native:
[migration_guide_rn_ng.md](https://github.com/AgoraIO/Docs-Source/files/9643537/migration_guide_rn_ng.md)

**Comment by Kishan-Dhakan** [comment]
@lemon-chen could you also share the release notes for the same?

**Comment by lemon-chen** [comment]
Release notes for React Native Voice call:
[release_rn_audio_ng.md](https://github.com/AgoraIO/Docs-Source/files/9653060/release_rn_audio_ng.md)

**Comment by lemon-chen** [comment]
Release notes for React Native Video call and ILS:
[release_rn_ng.md](https://github.com/AgoraIO/Docs-Source/files/9653065/release_rn_ng.md)
