### ISSUE TITLE
FCR Enable and disable the whiteboard update

### ISSUE THREAD

**Issue by SunGiantor** [AgoraIO/Docs-Source#1330]
Hi Iain, the Chinese version of Enable and disable the whiteboard document has been launched. Currently, the document for this module overseas is old, and many methods are incorrect. The Chinese document is correct. Please help to replace and update the entire overseas document according to the Chinese document. Thank you very much

The link to enable and disable the whiteboard in Chinese is as follows:

web：
https://docs.agora.io/cn/agora-class/whiteboard_web?platform=Web
![1921681873727_ pic](https://user-images.githubusercontent.com/6038975/232956985-1bf88d40-96dd-4a07-bad4-9ef211ca1690.jpg)

iOS：
https://docs.agora.io/cn/agora-class/whiteboard_ios?platform=iOS

![1941681873756_ pic](https://user-images.githubusercontent.com/6038975/232957031-76bc478e-195a-4c3b-a8dc-279179e81a4b.jpg)

Android：
https://docs.agora.io/cn/agora-class/whiteboard_android?platform=Android
![1931681873743_ pic](https://user-images.githubusercontent.com/6038975/232957067-3716dec2-5385-48cb-b20b-e60644f3dbdf.jpg)

**Comment by billy-the-fish** [comment]
This is for https://docs.agora.io/en/flexible-classroom/develop/disable-whiteboard-module?platform=web
