### ISSUE TITLE
Need clearer docs!

### ISSUE THREAD

**Issue by tomkail** [AgoraIO/Docs-Source#1368]
We're super excited about this feature but we don't feel at all comfortable setting this up from this documentation. Can you make it more beginner friendly?

Edit - urgh this comment relates to this page. Seems that's not automatically referenced.
https://docs-beta.agora.io/en/real-time-transcription/get-started

**Comment by billy-the-fish** [comment]
Hi  there, 
   Thanks for reaching out. Let's join the dots more clearly for you. Can you please chat to  @saudsami about what would help so we can get you up and running easily. In the mean time, have you had a play with https://github.com/AgoraIO/agora-rtt-server so this part of the implementation process is clear. 

      Cheers

    Iain

**Comment by saudsami** [comment]
Added one-click deployment to Railway.
https://github.com/AgoraIO/agora-rtt-server/issues/1
