### ISSUE TITLE
Routine Document Optimization for Agora Chat

### ISSUE THREAD

**Issue by haoxiuwen** [AgoraIO/Docs-Source#1371]
**Business case**: Routine Document Optimization for Agora Chat

**Subject Matter Expert**:
- *Technical*:
- *Language*: Iain
- *PM*: only if essential

**Scope**: The products and documents to be updated. If you are not sure, leave it to Iain.

**Acceptance criteria**: The documentation is technically correct, easy to use, follows the template structure and
follows the Google Developer Style Guide.

**Additional valuable information**: Anything else that will help with this issue.

**Comment by haoxiuwen** [comment]
Modify Agora Chat Token (https://docs.agora.io/en/agora-chat/develop/authentication) and Webhook Doc (https://docs.agora.io/en/agora-chat/develop/setup-webhooks):

For the modifications, please see the following PR:
https://github.com/AgoraIO/agora_doc_source/pull/2839/files

For the new section "Experience token generation" in the Token, you can also use the images in the Quick Start of each platform, for example https://docs.agora.io/en/agora-chat/get-started/get-started-sdk?platform=android

**Comment by haoxiuwen** [comment]
For updates of other RESTful, Android and iOS Docs, please see the following PR:

https://github.com/AgoraIO/agora_doc_source/pull/3048

**Comment by atovpeko** [comment]
Progress: waiting for https://github.com/AgoraIO/Doc-Source-Private/milestone/1 to be approved and published, so that the part about token generation can be reused instead of copying.

**Comment by atovpeko** [comment]
Progress: changes from all linked PRs are transferred here. The part about token generation touches the same docs as https://github.com/AgoraIO/Doc-Source-Private/milestone/1, so it's best to wait for the milestone to merge, then pull, and revise the update to avoid content duplication.

**Comment by haoxiuwen** [comment]
Please modify the following documents about thread messages, reaction, and retrieve messages
https://github.com/AgoraIO/agora_doc_source/pull/3147/files

https://github.com/AgoraIO/agora_doc_source/pull/3167/files

**Comment by haoxiuwen** [comment]
For the Agora Chat SDK 1.1.2 for React Native, you can visit the following URL to get the release notes, API reference package, and the SDK link:
https://confluence.agoralab.co/display/ACS/React-Native

**Comment by haoxiuwen** [comment]
Please add the document for the following functions
a. Cross-border dedicated proxy
For the document, see PR:
It is recommended that the document is added here:

![image](https://github.com/AgoraIO/Docs-Source/assets/95393471/b32ab0f0-7708-4245-8152-4936e3fb95e1)

**Comment by haoxiuwen** [comment]
Please updates the modifications in the following PR to the official Chat website:

https://github.com/AgoraIO/agora_doc_source/pull/3294/files

This PR involves the following updates:

SDK APIs:
1. Add the message re-sending mechanism to the message overview doc.
2. Add the section of `Reconnection upon token expiration` in the token authentication doc.
3. Add how to send a location message for the web platform.
4. Optimize the description of how to retrieve the member list of a chat group for the Android/iOS platform.
5. Add a note to use attribute doc of all platforms to indicate that when you call the RESTful API of setting user attributes to set the user's nickname, avatar, contact information, email address, gender, signature, birthday and extension fields, you must pass the fixed keys to make sure that the client can obtain the settings.
6. Add errors for Android, iOS, and Web, like Android error code 105-110, 219-220, 501, 508, 1101, 1200, 1200.
7. Code/description updates.

REST API:
1. Remove group/chat room name restriction: remove the restriction of using the plus sign (+) and stashes
2. Add the `ext.em_ignore_notification` to the RESTful API of sending a message to indicate whether to send a silent message.
3. Add detailed descriptions of `nickname` in the RESTful API of registering a user
4. Add some limits, including the number of chat room/group members that can be muted, added to the allow list or block list at each call of the API.
5. Add detailed descriptions of `force` in the RESTful API of recalling a message.
6. Code/description updates.

**Comment by haoxiuwen** [comment]
Please update the August modifications in the following PR to the official Chat website:

https://github.com/AgoraIO/agora_doc_source/pull/3311/files

This PR involves the following updates:

1. Callback: update the UI screenshots and related parameter description.
2. Add description of user status changes triggered by user login and logout in the document of agora_chat_receive_webhook.md.
3. REST API for group creation: Add two parameters ''scale'' and `invite_need_confirm`
4. Differentiation between group and chat room: modify the description of offline message storage and add the description of historical message storage.
5. Modify the Flutter code segment of retrieve the messages in the specified conversation from the local database.

**Comment by atovpeko** [comment]
> Please add the document for the following functions a. Cross-border dedicated proxy b. IP allow list For the document, see PR: [AgoraIO/agora_doc_source#3183](https://github.com/AgoraIO/agora_doc_source/pull/3183) The two functions are not bound with any releases of Agora Chat.

@haoxiuwen there is already a doc for IP allowlist: https://docs.agora.io/en/agora-chat/develop/ip_whitelist?platform=android Should I merge those two together?

**Comment by haoxiuwen** [comment]
> > Please add the document for the following functions a. Cross-border dedicated proxy b. IP allow list For the document, see PR: [AgoraIO/agora_doc_source#3183](https://github.com/AgoraIO/agora_doc_source/pull/3183) The two functions are not bound with any releases of Agora Chat.
> 
> @haoxiuwen there is already a doc for IP allowlist: https://docs.agora.io/en/agora-chat/develop/ip_whitelist?platform=android Should I merge those two together?

For the IP whitelist on the official website, the IP whitelist contains the egresss IP addresses of the developer's server. These IP addresses are allowed to call RESTful APIs, while other IP addresses are disallowed. This ensures security. These IP addresses are added under Chat > Features > IP Whitelist. 

The IP allow list in PR 3183 (https://github.com/AgoraIO/agora_doc_source/pull/3183) contains IP addresses that are allowed to communicate through TCP/TLS 443. These IP addresses are of data centers of Agora Chat.  These IP addresses are added to the firewall allow list.

**Comment by haoxiuwen** [comment]
Please update the September modifications in the following PR to the official Chat website:
https://github.com/AgoraIO/agora_doc_source/pull/3318
This PR involves the following updates:
1. Chat room description: 
   a. Remove the indication of push message from the  chat room description as the push function is unavailable for chat rooms.
   b. Make clear that once going offline, a user automatically leaves the chat room after 2 minutes.
2. Modify the sample code in the message receipt document.
3. Change the maximum of users that a push label can contain to 20,000.
4. Changes the call frequency of a REST API

**Comment by haoxiuwen** [comment]
@atovpeko Please  add the following updates of web docs to the official Agora Chat website:

https://github.com/AgoraIO/agora_doc_source/pull/3332/files

**Comment by haoxiuwen** [comment]
@atovpeko Please change the link in the red box to the following:

https://learn.microsoft.com/en-us/azure/ai-services/translator/language-support

The issue should be fixed in the "Translate messages" document of each platform and framework, including Android, iOS, Web, Windows, Unity, Flutter, and React Native.

![image](https://github.com/AgoraIO/Docs-Source/assets/95393471/8ee0e050-32be-4b31-be03-5d7568fee825)

**Comment by haoxiuwen** [comment]
@atovpeko Please update the Flutter Quick Start document (https://docs.agora.io/en/agora-chat/get-started/get-started-sdk?platform=flutter):

1. Add the following to the red box:

// Notify the SDK that the Ul is ready, After the following method is executed, callbacks within 'ChatRoomEventHandler."
andChatGroupEventHandler can be triggered.
await ChatClient.getlnstance.startCallback();

![image](https://github.com/AgoraIO/Docs-Source/assets/95393471/383691ad-5521-40d6-bf24-4b3a9c99edb9)

2. Replace the code in the red box with the following:

ChatClient.getInstance.chatManager.addMessageEvent(
      "UNIQUE_HANDLER_ID",
      ChatMessageEvent(
        onSuccess: (msgId, msg) {
          _addLogToConsole("on message succeed");
        },
        onProgress: (msgId, progress) {
          _addLogToConsole("on message progress");
        },
        onError: (msgId, msg, error) {
          _addLogToConsole(
            "on message failed, code: ${error.code}, desc: ${error.description}",
          );
        },
      ),
    );

    ChatClient.getInstance.chatManager.removeMessageEvent("UNIQUE_HANDLER_ID");

![image](https://github.com/AgoraIO/Docs-Source/assets/95393471/332d3c64-709c-437a-a094-aebda37ee4cc)

**Comment by haoxiuwen** [comment]
@atovpeko Please add the following documentation updates to the official Agora Chat website.

This PR involves the following updates:
1. Optimize the sample code of sending a message to demonstrate how to send a message in a one-to-one chat, group chat or room chat
2. Add two HTTP status codes.

https://github.com/AgoraIO/agora_doc_source/pull/3347/files

**Comment by haoxiuwen** [comment]
@atovpeko Please replace the description in the red box with the following:

This feature is disabled for chat rooms by default. To enable it, contact support@agora.io. After this feature is enabled, when a user joins a chat room, the server sends the latest 10 historical messages to the client side via the message receiving callback. The number of historical messages sent to the new chat room member can be increased up to 200.

![image](https://github.com/AgoraIO/Docs-Source/assets/95393471/94d1ece3-eb54-4548-9567-518ed265a4fd)

The document URL: https://docs.agora.io/en/agora-chat/reference/group-overview?platform=android
