### ISSUE TITLE
[Android][4.x] MediaStreamInfo duration attribute

### ISSUE THREAD

**Issue by kevin-rabefaritra** [AgoraIO/Docs-Source#1378]
**Business case**: Specify the correct unit used by the `duration` attribute of `MediaStreamInfo`.

**Subject Matter Expert**:
- *Technical*:
- *Language*: Iain
- *PM*: only if essential

**Scope**:
Doc link: https://api-ref.agora.io/en/video-sdk/android/4.x/API/class_playerstreaminfo.html 

Since 4.x, the the `duration` attribute of `MediaStreamInfo` is in **milliseconds**, instead of **seconds**.
This may affect the implementation logic in case of misuse.

**Acceptance criteria**: The documentation is corrected.

**Additional valuable information**:
I have tested to read the attribute and can confirm the value is returned in milliseconds.

**Comment by dengyaxi** [comment]
Hi @billy-the-fish. Just a quick heads up! If there's any GitHub issue related to the 4.x API reference, please assign it to me if it's for the **web** platform. For other platforms, please assign it to Luodan.

**Comment by billy-the-fish** [comment]
Done, thank you @dengyaxi .

**Comment by Cilla-luodan** [comment]
The doc source is updated. Please use this tag for publish:  https://github.com/AgoraIO/agora_doc_source/releases/tag/v4.2.0-bugfix-0608

It is also mentioned in this issue: https://github.com/AgoraIO/Docs-Source/issues/1405
