### ISSUE TITLE
[Media Push] Update best practice

### ISSUE THREAD

**Issue by kelzr** [AgoraIO/Docs-Source#1388]
<img width="1260" alt="企业微信截图_39f24b00-ba24-4343-8893-40ebca5aa68d" src="https://github.com/AgoraIO/Docs-Source/assets/50696835/1f9e0bd5-9d69-4777-9caf-a2767d1fa3b9">

https://docs.agora.io/en/media-push/develop/integration-best-practices#create-rtmp-converter

After receiving feedback from technical support, I think the following updates can be made to the document:

_1. Update the selected sentence to:_

"In an audio-only scenario, you do not need to set `videoOptions` and its related fields by default. For special cases, see [Output SEI in audio-only scenarios](#sei)."

_2. Add a sub-section to the "Create" section:_

<a name = "sei"></a>
### Output SEI in audio-only scenarios

In an audio-only scenario, by default, you do not need to set `videoOptions` and its related fields. However, if you need to carry additional user information, such as volume, you can set SEI information with the `seiOptions` field in `videoOptions`.

If you want to output SEI information in Metadata or DataStream type carried by the user in an audio-only scenario and avoid video transcoding fees, follow these steps:
- Pass the SEI information to be output in `videoOptions.seiOptions`.
- Ensure that the width and height in `videoOptions.canvas` are set to 16 to avoid video transcoding fees.
- Pass the UID of the user who carries the SEI information in `rtcStreamUid` field in `videoOptions.layout`.

**Comment by atovpeko** [comment]
Done in the scope of and to be published with another update to the same docs: https://docs-staging-git-1481-service-quota-notification-agora-gdxe.vercel.app/en/media-push/develop/integration-best-practices#create-rtmp-converter
