### ISSUE TITLE
FCR Add a prompt to the configuration of the recording module

### ISSUE THREAD

**Issue by SunGiantor** [AgoraIO/Docs-Source#1390]
link:
https://docs.agora.io/en/flexible-classroom/get-started/enable-flexible-classroom?platform=web#configure-classroom-storage-and-recording

<img width="1343" alt="image" src="https://github.com/AgoraIO/Docs-Source/assets/6038975/be027630-59da-44cc-9485-be5aa2935e77">

Help add a description of the OSS configuration for the recording module.

”
The recording cofig can be selected as default, and the storage config must be selected as custom, otherwise the recording cannot be stored in your OSS account.“

Please refer to the prompts in the Chinese document

https://docportal.shengwang.cn/cn/agora-class/agora_class_configure?platform=All%20Platforms#%E9%85%8D%E7%BD%AE%E5%BD%95%E5%88%B6%E5%8A%9F%E8%83%BD

<img width="1410" alt="image" src="https://github.com/AgoraIO/Docs-Source/assets/6038975/b7500cc2-efdf-4e77-81c0-01b0640756d2">

**Comment by atovpeko** [comment]
Done within the 2.9.0 Flexible Classroom release.
