### ISSUE TITLE
[RTM 2.1.1 Web] Release notes and API reference

### ISSUE THREAD

**Issue by HeatherWYL** [AgoraIO/Docs-Source#1395]
Release notes:
[rtm2-release-notes .md](https://github.com/AgoraIO/Docs-Source/files/11571258/rtm2-release-notes.md)

API reference:
TODO

**Comment by atovpeko** [comment]
@HeatherWYL `rtmConfig` either does not have an explanation in the initial config, or it includes all the fields afterwards, in which case I believe some indentation is necessary. Could you please clarify? Thanks!

**Comment by HeatherWYL** [comment]
@atovpeko Please find `rtmConfig` docs in the following link:
https://github.com/AgoraIO/shengwang-doc-source/blob/rtm2.1.1-js-en/docs-api-reference/rtm2/toc-configuration/configuration.web.mdx#configrtmfrontmatterag_platform
