### ISSUE TITLE
[Android][4.x] ChannelMediaOptions enableAudioRecordingOrPlayout attribute

### ISSUE THREAD

**Issue by kevin-rabefaritra** [AgoraIO/Docs-Source#1402]
**Business case**: Clarify the meaning of the attribute `enableAudioRecordingOrPlayout` of the `ChannelMediaOptions` class.

**Subject Matter Expert**:
- *Technical*:
- *Language*: Iain

**Scope**: 
Doc link: https://api-ref.agora.io/en/video-sdk/android/4.x/API/class_channelmediaoptions.html
In this page, both `true` and `false` values of `enableAudioRecordingOrPlayout` are described as "_Do not enable audio capturing or playback._".
The description for `true` should be updated to "_enable audio capturing or playback_".

**Acceptance criteria**: The documentation is corrected.

**Additional valuable information**: Anything else that will help with this issue.

**Comment by Cilla-luodan** [comment]
Hi @kevin-rabefaritra, thanks for your feedback, we'll correct it in this week's update version.

**Comment by Cilla-luodan** [comment]
The doc is updated in the 4.2.1 release:  https://api-ref.agora.io/en/video-sdk/android/4.x/API/class_channelmediaoptions.html
<img width="460" alt="image" src="https://github.com/AgoraIO/Docs-Source/assets/85477033/d1914e4d-48d4-4604-8a2d-6e159fb8b3c2">
