### ISSUE TITLE
Update 4.x RTC migration guides

### ISSUE THREAD

**Issue by Cilla-luodan** [AgoraIO/Docs-Source#1404]
**Business case**: Update the migration guides according to this jira: https://jira.agoralab.co/browse/CSD-55929

**Subject Matter Expert**:
- *Technical*:
- *Language*: Iain
- *PM*: only if essential

**Scope**: 4.x RTC migration guide of all platforms

**Acceptance criteria**: -

**Additional valuable information**: For the changed content, see this pr:  https://github.com/AgoraIO/agora_doc_source/pull/3112/files

**Comment by billy-the-fish** [comment]
Will go out with the 4.2.2 native release.

**Comment by atovpeko** [comment]
Looks like this has been done so I'll close this ticket
