### ISSUE TITLE
[4.x RTC doc bugfix] Update API ref of all platforms

### ISSUE THREAD

**Issue by Cilla-luodan** [AgoraIO/Docs-Source#1406]
Hi Iain,
Please update the API refs according to this tag: https://github.com/AgoraIO/agora_doc_source/releases/tag/v4.2.0-bugfix-0615
Target OS: Windows, iOS, macOS, Android, RN, Electron, Flutter, Unity, Csharp

**Comment by billy-the-fish** [comment]
These changes are going out with the 4.2.1 release.
