### ISSUE TITLE
Things needed in the guide

### ISSUE THREAD

**Issue by ysc1995** [AgoraIO/Docs-Source#1412]
Please make sure there is information about:

- how to apply and stop ActiveFence content moderation on any channel and any user at any time. 

- how to control the channel/user management when a content moderation event is triggered. (suggests to use the Channel Management Restful api to kick user out of the channel which will trigger a statechange callback event on RTC)

The project setup steps need to change. Currently ActiveFence is developing the provisioning api, when that is done, customers can go to Agora console and activate the extension with a click of the button. For now, we can ask customer to send us an email to enable the extension with information like: Agora appid, customer name, customer email, customer preferred callback url, content moderation vendor name. After receiving the email, our team will manually contact ActiveFence and get the credential for this customer. After receiving that from ActiveFence, we will activate the extension for their appid and reply back to customer with their credentials they need. 
At the same time, ActiveFence will send an email to customer and provide them with their ActiveFence dashboard account information. Customer can use that information to login to ActiveFence dashboard. On the dashboard, customer has the ability to review the pictures. ActiveFence team will provide a documentation to explain this in detail later. We can add that in to the guide after receiving that.

**Comment by billy-the-fish** [comment]
https://docs-staging-git-279-write-the-implementation-983258-agora-gdxe.vercel.app/en/extensions-marketplace/develop/integrate/activefence?platform=ios.

**Comment by qiuyanli1990** [comment]
Since we can generate AF API key from here and also edit and delete it here 
![image](https://github.com/AgoraIO/Docs-Source/assets/58502052/4e3cf124-00a7-48df-8017-54eccee0d296)
Why we still need add the key info to another palce
![image](https://github.com/AgoraIO/Docs-Source/assets/58502052/eb626e2b-0223-462a-b989-c12b74a9a713)
By doing this we have to copy the key value, this is easily lead us to regenerate the AF API key when we need to put a key value here.

**Comment by qiuyanli1990** [comment]
Our integration guide did not mention step by step to add key in Key Management.  While the fields under this menu is quite confusing.

**Comment by qiuyanli1990** [comment]
> Our integration guide did not mention step by step to add key in Key Management. While the fields under this menu is quite confusing.
