### ISSUE TITLE
[4.2.1 RTC] Release Notes

### ISSUE THREAD

**Issue by Cilla-luodan** [AgoraIO/Docs-Source#1413]
Hi Iain,
The 4.2.1 SDK is released. 
Please update the Release Notes according to this tag: https://github.com/AgoraIO/agora_doc_source/releases/tag/v4.2.1

P.S. This tag contains the release notes for x-platforms that are not yet ready.  Pleases update the Native docs first.

**Comment by billy-the-fish** [comment]
Thanks Luodan, am I ok to republish the API ref from this tag at the same time? Cheers, Iain.

**Comment by Suri539** [comment]
Hi Iain, the 4.2.1 SDKs of x-platforms are released. Please update the release notes for x-platforms accordingly. Thanks! 
P.S. You can republish the API ref from the tag.

**Comment by billy-the-fish** [comment]
Done, thank you.
