### ISSUE TITLE
[4.x RTC 0629 doc bugfix] Update API ref of all platforms

### ISSUE THREAD

**Issue by Suri539** [AgoraIO/Docs-Source#1417]
Hello Iain, please update the API ref of all platforms based on the[ tag ](https://github.com/AgoraIO/agora_doc_source/releases/tag/v4.2.1-bugfix-0629). Thanks!
P.S. The diff may looks huge but most of them are only modifications of props in codeblocks rather than contents.

**Comment by littleGnAl** [comment]
Any update on this? Why update the doc need more than one week?

**Comment by billy-the-fish** [comment]
Done
