### ISSUE TITLE
Customer Documentation Update

### ISSUE THREAD

**Issue by Stephcrmy22** [AgoraIO/Docs-Source#1419]
Hi, 

We have a customer who was confused why there was FHD, 2K, and 2K+ on their console usage dashboard by using this document: https://docs.agora.io/en/video-calling/reference/billing-policies?platform=web#how-does-agora-calculate-service-minutes. The issue was resolved by providing the documentation regarding aggregation however, the customer suggested that we should update the posted document. 

Thanks!

**Comment by atovpeko** [comment]
Added a link to the aggregate resolution calculation/explanation: https://docs.agora.io/en/video-calling/reference/billing-policies?platform=android#calculation-approach-by-agora
