### ISSUE TITLE
Screen sharing issue of react-native-agora

### ISSUE THREAD

**Issue by LichKing-2234** [AgoraIO/Docs-Source#1420]
I find the `pod 'AgoraIrisRTC_iOS', '<version number>'` should be `pod 'AgoraRtcEngine_iOS', '<version number>'`

https://docs.agora.io/en/video-calling/develop/product-workflow?platform=react-native#project-setup

pls refer to https://docportal.shengwang.cn/cn/video-call-4.x/screensharing_rn_ng?platform=React%20Native#开发注意事项

**Comment by maxxfrazer** [comment]
@LichKing-2234 the react native SDK uses both, should it just use one?
https://github.com/AgoraIO-Extensions/react-native-agora/blob/main/react-native-agora.podspec#L20-L21

**Comment by LichKing-2234** [comment]
> @LichKing-2234 the react native SDK uses both, should it just use one?
> https://github.com/AgoraIO-Extensions/react-native-agora/blob/main/react-native-agora.podspec#L20-L21

just need to using native
