### ISSUE TITLE
HTML5 demo wesite is not working

### ISSUE THREAD

**Issue by sohuichoi** [AgoraIO/Docs-Source#1421]
when i click "join now" button, the following error occurs.
**PUT https://api-solutions-cn.agoralab.co/edu/companys/0/v1/rooms 401**

**Comment by lemon-chen** [comment]
Not sure I know what this issue is about.

**Comment by atovpeko** [comment]
@sohuichoi could you please provide more context for us so we can take care of this, please? Where is this button in the docs?

**Comment by atovpeko** [comment]
Closing this due to lack of input. Please feel free to open a new ticket if the issues persists and we'll make sure to address it. Thank you!
