### ISSUE TITLE
Update the API "InsertDocsStatic"

### ISSUE THREAD

**Issue by kbuchhagen** [AgoraIO/Docs-Source#1422]
the current wrong API provided in the doc, https://docs.agora.io/en/interactive-whiteboard/reference/uikit-sdk?platform=web#insertdocsstatic 

the correct API should be the following(Differences highlighted. BTW, it makes no sense that the customer needs to use the parameter as "ppt" for PDF in the API of static which "pdf" is the supported file type in dynamic API)
await fastboard.insertDocs({
              title: 'test.pdf',
              fileType: 'pdf',
              scenePath: '/pdf/a440b5906bd347b8ad1c026f76245b9d',
              scenes: [
                {
                  name: '1',
                  ppt: {
                    width: 734,
                    height: 950,
                    src: 'https://test-netless-s3.s3.eu-west-2.amazonaws.com/staticConvert/a440b5906bd347b8ad1c026f76245b9d/1.png',
                  }
                },
              ],
            });

**Comment by atovpeko** [comment]
Looks like this has been taken care of.
