### ISSUE TITLE
[New Releases] Update Cloud Recording

### ISSUE THREAD

**Issue by kelzr** [AgoraIO/Docs-Source#1425]
# Release Notes

https://docs.agora.io/en/cloud-recording/reference/release-notes

## 2023.07.05

The new features and improvements in this release are as follows:

- Adds support for the following regions of Alibaba Cloud storage:
  - `23`: CN_Nanjing
  - `24`: CN_Fuzhou
  - `25`: CN_Wulanchabu
  - `26`: CN_Northeast_2
  - `27`: CN_Southeast_7
- Updates the [Agora transcoding script](https://download.agora.io/acrsdk/release/cloud_recording_tools.v3.8.0.69-202302061216-release-prod.tar.gz) to reduce background noise.

# API Reference

https://docs.agora.io/en/cloud-recording/reference/rest-api/update

<img width="1301" alt="企业微信截图_043856a8-4243-474b-bd9d-fab8c961e0e0" src="https://github.com/AgoraIO/Docs-Source/assets/50696835/d73cff9c-9e5e-46cc-a2e9-b4516ede4c27">

<img width="816" alt="企业微信截图_b0537060-afb1-4537-94c1-baee3a792ba5" src="https://github.com/AgoraIO/Docs-Source/assets/50696835/1966f22e-498c-42a0-aa4d-1b745b79223f">

https://docs.agora.io/en/cloud-recording/reference/rest-api/start

<img width="1066" alt="企业微信截图_424552dd-f800-4fdf-b67d-388d20115b76" src="https://github.com/AgoraIO/Docs-Source/assets/50696835/1a7e260a-5c5d-4010-832d-7576e52770bd">

<img width="1255" alt="image" src="https://github.com/AgoraIO/Docs-Source/assets/50696835/1c4bcc9f-58f7-4e4c-830a-3fa3103c8c9c">

 - `23`: CN_Nanjing
 - `24`: CN_Fuzhou
 - `25`: CN_Wulanchabu
 - `26`: CN_Northeast_2
 - `27`: CN_Southeast_7

# All Docs

Delete "ApsaraVideo" or "ApsaraVideo for VoD" everywhere because we don't support it in the future.
Delete "Qiniu Cloud" temporarily because this cloud service is not usable for Agora Cloud Recording these days.

**Comment by kelzr** [comment]
https://confluence.agoralab.co/pages/viewpage.action?pageId=1244267515

<img width="791" alt="企业微信截图_eb49ae63-dfad-487c-9581-5859542f7691" src="https://github.com/AgoraIO/Docs-Source/assets/50696835/0380cb14-5126-4150-9cf9-7ee6c6b90b88">

这两条需求不属于 CN Documentation 团队负责的英文文档更新需求，需要产品经理直接和 EN DOcumentation 提需求。

**Comment by kelzr** [comment]
This issue serves as supplementary material for the cloud recording release requirement. I am not sure when the product manager will contact you for handling. I am sharing the information that the Chinese documentation team can provide for you here. @billy-the-fish

**Comment by saudsami** [comment]
Here's the staging link with the requested changes:
https://docs-staging-j9qkqgr5m-agora-gdxe.vercel.app/en/cloud-recording/reference/release-notes
Please let me know if you need anything further.
