### ISSUE TITLE
[4.2.2 RTC] Release Notes + API ref

### ISSUE THREAD

**Issue by Cilla-luodan** [AgoraIO/Docs-Source#1433]
Hi,
The docs for v4.2.2 are ready.
You can find the diff of the ditamaps in this url: https://github.com/AgoraIO/agora_doc_source/compare/v4.2.0-API-all-platforms-0524...v4.2.2
The release notes are in the old place.

**Comment by billy-the-fish** [comment]
Thank you

**Comment by Cilla-luodan** [comment]
A few changes are made based on internal feedbacks, the new tag is https://github.com/AgoraIO/agora_doc_source/releases/tag/v4.2.2-0724.
See this url for the latest diff: https://github.com/AgoraIO/agora_doc_source/compare/v4.2.2...v4.2.2-0724

Btw, the release notes of v4.2.0 are also updated, please update them as well.

**Comment by Cilla-luodan** [comment]
Here's a tip for you, just in case: the target x-platforms for v4.2.2 are Unity, Flutter, and Electron. Please ignore the updates of RN's release notes in the source files.
