### ISSUE TITLE
The field transcodeOptions.videoOptions.defaultPlaceholderImageUrl should be optional but marked as required.

### ISSUE THREAD

**Issue by zshbleaker** [AgoraIO/Docs-Source#1434]
**Business case**: How will this issue help our customers.

**Subject Matter Expert**:
- *Technical*: Dasun

**Scope**: The products and documents to be updated. If you are not sure, leave it to Iain.

https://docs.agora.io/en/media-push/develop/restful-api#http-request

**Acceptance criteria**: Just changed the `required` to `optional` of this field.

**Additional valuable information**: 

The transcodeOptions.videoOptions.defaultPlaceholderImageUrl field is marked as required, however it does not make any sense to require the generated RTMP stream must have a placeholder image. Just checked with the dev of Media Push and confirmed that it's not required.

**Comment by nirm2009** [comment]
Required change on this task was added on [macOS 'Video Calling SDK quickstart' page contains mentions/links specific to iOS #1423](https://github.com/AgoraIO/Docs-Source/issues/1423) task's PR commit at [](https://github.com/AgoraIO/Docs-Source/pull/1437/commits/84ece261e21509f866e65f96a51b1678825258b1).
