### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by nav198** [AgoraIO/Docs-Source#1443]
Documentation seems to be very easy to understand and yet it is complicated to implement the functionality of video calling in ios using Agora , Please do develop a user friendly approach . Thank You

**Comment by atovpeko** [comment]
VSDK docs are about to be fully updated and released to our [beta site](https://docs-beta.agora.io/en/). Do take a look next week :-) . I am closing this ticket since it will be an entirely new doc. Please open a new ticket, if needed, after update.
