### ISSUE TITLE
how to parse RTT onStreamMessage callback to get text

### ISSUE THREAD

**Issue by Nirav-Sanghani** [AgoraIO/Docs-Source#1447]
in this doc 

https://docs-beta.agora.io/en/real-time-transcription/get-started/#use-google-protobuf-generator-to-parse-text-data

it is mention that
"When transcription text is available, your app receives the onStreamMessage callback." 
i am getting call back but it is not clearly mention how to parse callback to get text. i have generated proto file and also generated javascript file form .proto file but do not know how to handle callback 

i am working on react native if you have any example code then i need it urgent as our broadcast application is live but caption is missing.

**Comment by EkaanshArora** [comment]
Hey here's an [example](https://github.com/AgoraIO-Extensions/react-native-agora/blob/762259b81587da7c9970e36834f087ee9c910950/example/src/examples/advanced/StreamMessage/StreamMessage.tsx#L149), does this help?

**Comment by Nirav-Sanghani** [comment]
@EkaanshArora  i am getting garbage value in  "data.toString()" 

below is log for text i am getting when speaking hello testing is there any way to remove garbage value 

Receive from uid:12345 
StreamId 49153:  �	H�vR
hello testingR
.`�j
transcribezen-US
