### ISSUE TITLE
Agora Console Project Management

### ISSUE THREAD

**Issue by The-Machine-Tango** [AgoraIO/Docs-Source#1452]
This is Derek, observed two things.
https://docs.agora.io/en/interactive-live-streaming/reference/manage-agora-account?platform=android#create-and-manage-projects

1. Agora Console doesn't support Delete projects, but the docs said the number of projects is up to 10 including Deteled projects which caused the customer confused;
2. It is noticed that in the CN doc, it says the number of projects is up to 20, but EN doc says 10.

**Comment by atovpeko** [comment]
Changed to 20 projects, will be published October 12
