### ISSUE TITLE
[4.2.2 RTC doc bugfix] Update API ref of Native platforms

### ISSUE THREAD

**Issue by Cilla-luodan** [AgoraIO/Docs-Source#1455]
This issue is used to trace Lily Qiu‘s request:
<img width="947" alt="image" src="https://github.com/AgoraIO/Docs-Source/assets/85477033/cba9ad90-2826-4b30-a625-fd2429f41e9e">

Please use this tag for publish: https://github.com/AgoraIO/agora_doc_source/releases/tag/v4.2.2-bugfix-0831

**Comment by atovpeko** [comment]
@Cilla-luodan same here, we're about to have 4.2.3 in a day or two, so I'll close this ticket, if that's ok.
