### ISSUE TITLE
Migrate the whiteboard docs. 

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#146]
Business case - developers need to easily implement RTM
Fix version - hard release
Subject Matter Expert - @billy-the-fish 
Reviewer - 
Scope - migrate  all docs from https://gitlab.com/agora-documentation/documentation-source/-/tree/milestone-clean-up-migrated-markdown/whiteboard to https://github.com/AgoraIO/Docs-Source/tree/main/interactive-whiteboard, plus new docs from CN source
Acceptance criteria - developers must be able to easily implement audio and voice effects functionality for electron
Milestone branch - https://github.com/AgoraIO/Docs-Source/issues/140

**Comment by dengyaxi** [comment]
@billy-the-fish We had a discussion about the whiteboard doc architecture. Our final proposal is:
- Overview
    - Interactive Whiteboard Overview
    - Core concepts ("Introduction" from [[Token Overview](https://docs.agora.io/en/whiteboard/whiteboard_token_overview?platform=Android)](https://docs.agora.io/en/whiteboard/whiteboard_token_overview?platform=Android); "Feature overview" from [[File Conversion Overview](https://docs.agora.io/en/whiteboard/file_conversion_overview?platform=Web)](https://docs.agora.io/en/whiteboard/file_conversion_overview?platform=Web); Scenes overview)
- Get Started
    - Enable and Configure Interactive Whiteboard Service
    - Quickstart (using whiteboard)
    - Quickstart with Starter Kit (using fastboard)
- Develop
    - Generate a Token at App Server [+ (Token Overview - Introduction)]
    - Use Whiteboard Tools
    - Manage Scenes
    - Display Files
    - Manage Room States
    - Custom Events
- RESTful API
    - Basic info
    - Generate a Token
    - Manage Rooms
    - Manage Screenshots
    - Manage Scenes
    - Convert Files [+ (Prerequisites + Start File Conversion) from [[File Conversion Overview](https://docs.agora.io/en/whiteboard/file_conversion_overview?platform=Web)](https://docs.agora.io/en/whiteboard/file_conversion_overview?platform=Web)]
- Reference
    - Release Notes for whiteboard
    - Release Notes for Starter Kit
    - API reference for Starter Kit
    - Pricing
    - Migrate from Netless to Agora
    - Security Practices
    - Token overview 剩余部分

**Comment by billy-the-fish** [comment]
Source is here: https://gitlab.com/agora-documentation/documentation-source/-/tree/milestone-clean-up-migrated-markdown/whiteboard

**Comment by billy-the-fish** [comment]
Dunnn
