### ISSUE TITLE
[4.2.2 RTC doc bugfix] Update API ref of Native platforms

### ISSUE THREAD

**Issue by Cilla-luodan** [AgoraIO/Docs-Source#1461]
This release contains fix of the jira: https://jira.agoralab.co/browse/DOC-3857

Please use this tag for publish: https://github.com/AgoraIO/agora_doc_source/releases/tag/v4.2.2-bugfix-0907

**Comment by atovpeko** [comment]
@Cilla-luodan sorry, I don't think Iain was able to update this in time. I'll close this since we're about to have 4.2.3 anyway, if that's ok with you.

**Comment by Bac1314** [comment]
Hi @atovpeko  Any update about this issue? 
 https://jira.agoralab.co/browse/DOC-3857

**Comment by atovpeko** [comment]
Hi @Bac1314. The API docs are already at 4.2.3, that's why this ticket is closed.
