### ISSUE TITLE
Audio route automatically updates from speaker to ear piece after muting local user in channel(Android sdk version 4.2.2)

### ISSUE THREAD

**Issue by HyperLightAlex** [AgoraIO/Docs-Source#1463]
As the title suggests, there seems to be an issue where if you initially set up the rtc engine with: `setDefaultAudioRoutetoSpeakerphone(true)` to enable audio to be routed to the speakerphone, if the local user mutes themselves or becomes muted, then the audio will be rerouted to the earpiece for the duration of the local user being muted. The audio route resumes though the speakerphone after the user is unmuted

setting `setDefaultAudioRoutetoSpeakerphone(true)` again after calling `muteRemoteAudioStream(<playerUId>, true)` to mute the player/local user seems to fix the problem, but this 'fix' seems unnecessary to have to use and the root issue should be resolved instead

**Comment by billy-the-fish** [comment]
Nice, add to https://docs.agora.io/en/video-calling/develop/product-workflow?platform=web please.

**Comment by HyperLightAlex** [comment]
@billy-the-fish @nirm2009 has there been any update on this?

**Comment by saudsami** [comment]
Hi @HyperLightAlex 
Have you tried upgrading to the latest version of the SDK?

**Comment by HyperLightAlex** [comment]
I am testing today, but from preliminary inspection it seems like the issue may have been resolved. I will comment results after more thorough testing

**Comment by HyperLightAlex** [comment]
Its seems as though this issues is fixed on the latest version(4.3.0 at the time of testing)

**Comment by saudsami** [comment]
Thanks for the update.
I will close this issue.
