### ISSUE TITLE
Link for Signaling webdemo 404 not found. 

### ISSUE THREAD

**Issue by Stephcrmy22** [AgoraIO/Docs-Source#1468]
Under the sample project part of Signaling document, 

Web demo link does not work https://webdemo.agora.io/agora-web-showcase/examples/Agora-Signaling-Tutorial-Web
![image](https://github.com/AgoraIO/Docs-Source/assets/128121761/0dc9fd9e-6df0-465b-9352-29f3df6b67fc)

**Comment by atovpeko** [comment]
Link removed upon consultation with Pavan, will be added back if there is a working one. Will be published October 12
