### ISSUE TITLE
Fix Errors in Server Gateway API Reference

### ISSUE THREAD

**Issue by HeatherWYL** [AgoraIO/Docs-Source#1471]
The Server Gateway SDK does not have the updateSimulcastStreamConfig method, we need to remove updateSimulcastStreamConfig and add setSimulcastStreamMode instead.

See API references in [html.zip](https://github.com/AgoraIO/Docs-Source/files/12699365/html.zip).

**Comment by saudsami** [comment]
The EN docs team does not generate the API reference. The CN team will need to make this change.
