### ISSUE TITLE
Switch between Doc and API reference

### ISSUE THREAD

**Issue by The-Machine-Tango** [AgoraIO/Docs-Source#1473]
If I am reviewing the doc of one product such as Agora Chat, and I want to check more APIs of that product by clicking API Reference, it will go back to the main page by showing default Voice Calling.

Reproduce Steps:
1. Go to https://docs.agora.io/en/agora-chat/overview/product-overview?platform=web
2. Click API Reference
3. The page goes to Voice Calling https://docs.agora.io/en/api-reference

What we need:
If I am reviewing the doc of one product, by clicking API reference, it needs to go to the API reference of the product I am viewing.

**Comment by billy-the-fish** [comment]
Nice point, 
- The  currently selected platform and product must be persistent through all pages in the docs site.
