### ISSUE TITLE
Release docs for Flexible Classroom v2.9.0 for Web and Electron

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#1474]
Flexible Classroom has released Web v2.9.0, and needs update on the docs. 
 
This release adds a Scene SDK which supports the new customized UI. See attached for the release notes and API Reference. You can also check the following links to see how they are organized on the CN doc site:

- Release notes: https://doc-internal.shengwang.cn/doc-new/fcr/doc/flexible-classroom/javascript/overview/release-notes
- API Reference: https://doc-internal.shengwang.cn/doc-new/fcr/api-ref/flexible-classroom/javascript/fcr-ui-scene

Apart form these two docs, updates on guides are also needed. Followings are links to the updated guides as well we their diffs on GitHub. You can check both and evaluate whether to apply the changes on the EN doc site:
 
- A newly added guide on the new UI:
   - Doc link: https://doc-internal.shengwang.cn/doc-new/fcr/doc/flexible-classroom/javascript/advanced-features/custom-ui-new
   - GitHub diff: https://github.com/AgoraIO/shengwang-doc-source/pull/326/files#diff-8c074e8a422a1d6e21387977d5a5c7c3b3795082d91fab1e21f22a6e397619e6
- Updates on how to set the fileNamePrefix parameter in the configure guide:
   - Doc link: https://doc-internal.shengwang.cn/doc-new/fcr/doc/flexible-classroom/javascript/get-started/configure
   - GitHub diff: https://github.com/AgoraIO/shengwang-doc-source/pull/326/files#diff-8575eaab3e028bafd9443478335454d9cd134da1e972a665f3d734f30a9b1178
- Updates on the command lines in the integration guide (Web and Electron):
   - Doc link: https://doc-internal.shengwang.cn/doc-new/fcr/doc/flexible-classroom/javascript/get-started/integrate
   - Doc link: https://doc-internal.shengwang.cn/doc-new/fcr/doc/flexible-classroom/electron/get-started/integrate
   - GitHub diff (Electron)：https://github.com/AgoraIO/shengwang-doc-source/pull/326/files#diff-78c31bbfdd76c99f8c3673a646ff00c60032d97d9d1bf2bdb9edc6edcbb11073
   - GitHub diff (Web): https://github.com/AgoraIO/shengwang-doc-source/pull/326/files#diff-c89034acaa1bcabbe454099db1ed1c6a5ab750e63283d47285603191526127b7 
- Updates on the command line in the quick-start guide (Web and Electron):
   - Doc link: https://doc-internal.shengwang.cn/doc-new/fcr/doc/flexible-classroom/electron/get-started/quick-start
   - Doc link: https://doc-internal.shengwang.cn/doc-new/fcr/doc/flexible-classroom/javascript/get-started/quick-start
   - GitHub diff (Electron): https://github.com/AgoraIO/shengwang-doc-source/pull/326/files#diff-a4c774abd01f323d240b06c041adec9f20c68727dc4685071849ada0a85d0037
   - GitHub diff (Web): https://github.com/AgoraIO/shengwang-doc-source/pull/326/files#diff-998f44963658a0ff2b9d2cf44207592af2d11d9cad8660650aa7c2749a5387ce
- Updates on the custom UI guide:
   - Doc link: https://doc-internal.shengwang.cn/doc-new/fcr/doc/flexible-classroom/javascript/advanced-features/custom-ui
   - GitHub diff: https://github.com/AgoraIO/shengwang-doc-source/pull/326/files#diff-7a22ecc90478c6883b0d9d7c29d0a5177c300f8380bcb224eddba7390adf2db2
- Updates on the widget tech:
   - Doc link: https://doc-internal.shengwang.cn/doc-new/fcr/doc/flexible-classroom/javascript/advanced-features/widget-tech
   - GitHub diff: https://github.com/AgoraIO/shengwang-doc-source/pull/326/files#diff-01db1e25ff6f0b60e9ce73478dcd68894cd448154e857255683dd19165c2bb56
- Updates on how to customize a widget:
   - Doc link: https://doc-internal.shengwang.cn/doc-new/fcr/doc/flexible-classroom/javascript/advanced-features/widget
   - GitHub diff: https://github.com/AgoraIO/shengwang-doc-source/pull/326/files#diff-02d1511d6b17379cf606049bbe7c44d3f2d1d07be85320e80b2b97a8da368555
- Updates on the RESTful API:
   - Doc link: https://doc-internal.shengwang.cn/doc-new/fcr/doc/flexible-classroom/javascript/restapi
   - GitHub diff: https://github.com/AgoraIO/shengwang-doc-source/pull/326/files#diff-d799b07138c254f46b68f28faa754c607f310ff1143ecb2a23b7c5291f545304
- Code updates in the Classroom SDK API Reference:
   - Doc link: https://doc-internal.shengwang.cn/doc-new/fcr/api-ref/flexible-classroom/javascript/classroom-sdk
   - GitHub diff: https://github.com/AgoraIO/shengwang-doc-source/pull/326/files#diff-b77856c2d79f048c97046caf208a9d2e279780d2a984e274dad397bf44dfbfb0
- Code updates in the Proctor SDK API Reference:
   - Doc link: https://doc-internal.shengwang.cn/doc-new/fcr/api-ref/flexible-classroom/javascript/proctor-sdk
   - GitHub diff: https://github.com/AgoraIO/shengwang-doc-source/pull/326/files#diff-c05eb6d8530d8052308b7c563b33600d4dfc1d584f873afdb7a1328ef0eae3bf
 
[api-ref.md](https://github.com/AgoraIO/Docs-Source/files/12736807/api-ref.md)
[release-notes-2.9.0.md](https://github.com/AgoraIO/Docs-Source/files/12736809/release-notes-2.9.0.md)

**Comment by atovpeko** [comment]
Closing this because we have created a milestone in the private repo with the same input, thank you
