### ISSUE TITLE
Set push notification link unavailable 

### ISSUE THREAD

**Issue by Stephcrmy22** [AgoraIO/Docs-Source#1478]
**SDK/Product**

Chat

**Business case**:
This will help our customers to navigate and find the correct reference for set push notification.

**Subject Matter Expert**:

**Doc Link**
https://docs.agora.io/en/agora-chat/restful-api/push-notification-management?platform=flutter#request-body

**Scope**:
Chat set notification link

**Acceptance criteria**:

N/A

**Additional valuable information**
The link is no longer available and redirects customer to overview page of chat.

**Comment by atovpeko** [comment]
Done, will be published October 12
