### ISSUE TITLE
Service quota notification

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#1481]
This is to tell customers the quota limit for the Agora service they use. In case the quota is not enough, customers need to contact support to increase the quota. 
The original request page from the developer is as follows:
- Media service (RTSC): https://confluence.agoralab.co/pages/viewpage.action?pageId=1355907634
- PCU/QPS/PCW limit: https://confluence.agoralab.co/pages/viewpage.action?pageId=660722404

You need to add the quota limit information into each corresponding doc. Followings are examples of how and where this information is added in the CN docs:

Product: Cloud Recording
Info to be added: PCW, QPS and stream number limit
CN doc link and diff: 
- https://docportal.shengwang.cn/cn/cloud-recording/integration_best_practices?platform=All%20Platforms
<img width="794" alt="企业微信截图_62ff9735-c346-4c08-953b-f6f407d4fbf1" src="https://github.com/AgoraIO/Docs-Source/assets/33219255/8eed3249-bb25-4b6a-a534-ea17a7db0464">

- https://docportal.shengwang.cn/cn/cloud-recording/webpage_best_practices?platform=All%20Platforms
<img width="721" alt="企业微信截图_00359b7e-dde4-4434-a70a-1cc2810b643f" src="https://github.com/AgoraIO/Docs-Source/assets/33219255/31b91269-ffc6-4001-a131-ed7603597ad0">

Product: Media Push
Info to be added: PCW and stream number limit
CN doc link: https://docportal.shengwang.cn/cn/media-push/media_push_best_practice?platform=All%20Platforms
<img width="1416" alt="企业微信截图_83c34e0a-7b35-404e-81f1-5549854f8acd" src="https://github.com/AgoraIO/Docs-Source/assets/33219255/dc1fbcb8-165c-47c1-8d75-dae7c01f4aad">

Product: Media Pull
Info to be added: PCW and stream number limit
CN doc link: https://docportal.shengwang.cn/cn/media-pull/media_inject_best_practice?platform=All%20Platform
<img width="1196" alt="企业微信截图_344c07e1-6d4d-4c11-b392-4912d7ff6581" src="https://github.com/AgoraIO/Docs-Source/assets/33219255/e9b9e7e9-1fe6-4728-a6f4-fbf02766250b">

Product: Signaling 1.x
Info to be added: QPS/PCW/DAU
CN doc link: https://docportal.shengwang.cn/cn/Real-time-Messaging/product_rtm?platform=All%20Platforms
<img width="1661" alt="企业微信截图_01124cad-84d3-44d7-bf62-5f5c5f92cb70" src="https://github.com/AgoraIO/Docs-Source/assets/33219255/1fb91f50-06a8-4da2-bc2e-668dca536a3c">

Product: Flexible Classroom
Info to be added: PCW
CN doc link: https://doc.shengwang.cn/doc/flexible-classroom/android/overview/product
<img width="1734" alt="企业微信截图_47957ab1-82fb-4f11-bbee-464e8275b272" src="https://github.com/AgoraIO/Docs-Source/assets/33219255/3b1ad84b-0a8d-4ff0-b4b9-ed25f0169a0b">

RTC (Native and Web)
Info to be added: PCW
CN doc link: https://doc.shengwang.cn/doc/rtc/android/overview/product-overview
<img width="1607" alt="企业微信截图_3194bb39-506e-4416-9995-ded01724928a" src="https://github.com/AgoraIO/Docs-Source/assets/33219255/2abe9e3d-c17f-40ea-a47c-9a96777877f4">

CDN streaming using client-side API, Cloud transcoder, Fusion CDN, IoT aPaaS, online KTV, RTC mini-program has no EN docs, so no update needed.

Speech-to-text and Agora Chat do not have public CN docs yet. You can check with PM and figure out where to add the info.

**Comment by dengyaxi** [comment]
Product: Broadcast Streaming
Doc to be updated: product overview
With a diff in [1007.zip](https://github.com/AgoraIO/Docs-Source/files/12837223/1007.zip) you can see what's changed in CN doc
