### ISSUE TITLE
Remote users

### ISSUE THREAD

**Issue by PedroDuarteD** [AgoraIO/Docs-Source#1484]
I am new in this platform, but i didn't find way to get all remote users from channel ?

**Comment by saudsami** [comment]
Hi
You use `onUserJoined` and `onUserOffline` events to keep track of users in the channel. Please refer to:
https://api-ref.agora.io/en/voice-sdk/android/4.x/API/class_irtcengineeventhandler.html#callback_irtcengineeventhandler_onuserjoined
The SDK also triggers the `onUserJoined` callback to report existing users in the channel when a user joins the channel.

Alternatively, you can use webhook notifications to keep track of users.
https://docs.agora.io/en/video-calling/develop/receive-notifications?platform=android#implement-online-user-status-tracking
