### ISSUE TITLE
fix reduce app size doc for Android

### ISSUE THREAD

**Issue by Nero-Hu** [AgoraIO/Docs-Source#1488]
https://docs.agora.io/en/video-calling/reference/downloads?platform=android

![image](https://github.com/AgoraIO/Docs-Source/assets/108781398/8b28f71d-02e3-423c-8363-b9832e95dd13)

It should be placed right after the table just like other platfoms: 

![image](https://github.com/AgoraIO/Docs-Source/assets/108781398/8ab6a53d-5f20-45cc-a62b-a64321f126c4)

**Comment by atovpeko** [comment]
Done: https://docs.agora.io/en/video-calling/reference/downloads?platform=android#plugin-list
