### ISSUE TITLE
[4.2.3 RTC doc bugfix] Update API ref for Native and x-platforms

### ISSUE THREAD

**Issue by Cilla-luodan** [AgoraIO/Docs-Source#1492]
Hi,
This is a regular bugfix version of API, we've made some updates based on internal feedbacks and self-discovered bugs.
Please update the API ref for all v4.2.3 Native and x-platforms.

Please use this tag for publish: https://github.com/AgoraIO/agora_doc_source/releases/tag/v4.2.3-bugfix-1019%26v4.2.1-unreal

**Comment by maxxfrazer** [comment]
@saudsami has this been implemented?

**Comment by saudsami** [comment]
v4.2.3 API refs have been published for all platforms.
