### ISSUE TITLE
Quickstart for MacOS

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#150]
Business case - developers need to easily implement Agora functionality using Video SDK in a MacOS
Fix version - hard release
Subject Matter Expert - @maxxfrazer . Find the SDK, API ref and a get started here: https://docs-preprod.agora.io/en/live-streaming-premium-4.x-beta/landing-page?platform=macOS
Reviewer - @nirm2009 
Scope - Get started for Video Calling, Voice Calling and ILS:
Video SDK: download is https://docs.agora.io/en/video-call-4.x-beta/downloads?platform=All%20Platforms
Voice SDK: download is https://docs.agora.io/en/voice-call-4.x-beta/downloads?platform=All%20Platforms.
Acceptance criteria - developers must be able to easily implement video and voice calling functionality for MacOS
Milestone branch - https://github.com/AgoraIO/Docs-Source/tree/milestone17-macos

**Comment by maxxfrazer** [comment]
Install for macOS will support Swift Package Manager on 4.0.0's launch at this location:
https://github.com/AgoraIO/AgoraRtcEngine_macOS

**Comment by maxxfrazer** [comment]
We do not need two macOS devices, two instances of the Agora app can run on one mac
