### ISSUE TITLE
[Bug]: Update FAQ (in-call vs media volume) to 4.x.x. 

### ISSUE THREAD

**Issue by Bac1314** [AgoraIO/Docs-Source#1500]
### Platform

iOS

### Platform details

https://docs.agora.io/en/help/integration-issues/system_volume

This FAQ is still based on 3.x.x SDK audio scenario e.g. chorus scenario is not mentioned. . Customer wants us to update this FAQ for 4.x.x. SDK. 

### Product

Interactive Live Streaming

### Business Case

Many customers don't know the difference between in-call and media volumes. This FAQ page is frequently used by our customers and internal agora team. Updating this FAQ will benefit both Agora internal team and customers. 

### Documentation Link

https://docs.agora.io/en/help/integration-issues/system_volume

### Acceptance Criteria

- The document must be updated based on the latest NG SDK scenarios

**Comment by Cilla-luodan** [comment]
The CN FAQ is wip, we'll post the url here when it's ready

**Comment by jinyuagora** [comment]
Hi @atovpeko , you can use this url as reference: https://doc.shengwang.cn/faq/integration-issues/system-volume.

**Comment by atovpeko** [comment]
Done: https://docs.agora.io/en/help/integration-issues/system_volume. Thank you for your input.
