### ISSUE TITLE
FCR Demo quickstart update

### ISSUE THREAD

**Issue by SunGiantor** [AgoraIO/Docs-Source#1503]
link:
https://docs.agora.io/en/flexible-classroom/get-started/?platform=web
and https://docs.agora.io/en/flexible-classroom/get-started/?platform=electron

1.delete "Lerna: A build system for managing and publishing multiple JavaScript/TypeScript packages."
<img width="1827" alt="image" src="https://github.com/AgoraIO/Docs-Source/assets/6038975/b10cb3e2-15b2-4dbd-a755-fd7886604a24">

2、delete "To install lerna, run the following command:"
<img width="1770" alt="image" src="https://github.com/AgoraIO/Docs-Source/assets/6038975/aedeca3c-aca4-4a2f-818d-7e97f390e35a">

**Comment by atovpeko** [comment]
Added to 2.8.8 review instance: https://docs-staging-git-milestone-55-fcr-2-8-8-agora-gdxe.vercel.app/en/flexible-classroom/get-started/?platform=web
