### ISSUE TITLE
[Bug]: Missing an important merge tool for cloud recording

### ISSUE THREAD

**Issue by EmmaAzureAgora** [AgoraIO/Docs-Source#1505]
### Platform

Other

### Platform details

Cloud Recording

### Product

Other

### Product details

Cloud Recording

### Business Case

https://docs.agora.io/en/cloud-recording/develop/manage-files#when-uploading-files-to-the-third-party-cloud-storage-fails
When cloud recorder quits abnormally, it will generate multiple recording files. i.e. A class recording is separated into 2 recording files. Customer needs one single file. In Chinese Document, we provide a merge tool. See this link: 
https://doc.shengwang.cn/doc/cloud-recording/restful/advanced-features/manage-recorded-files#%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%96%AD%E7%BD%91%E6%88%96%E8%BF%9B%E7%A8%8B%E8%A2%AB%E6%9D%80
<img width="1188" alt="Screenshot 2023-12-12 at 18 24 29" src="https://github.com/AgoraIO/Docs-Source/assets/61182922/b7696451-c3fe-4aa1-9973-45c304a98a8c">

We must include this tool in English document. Customer is complaining a lot that they have to manually handle such situations which add a lot of workloads for them.

### Documentation Link

https://docs.agora.io/en/cloud-recording/develop/manage-files#recorded-files-in-abnormal-conditions

### Acceptance Criteria

Cloud recording document misses a very important merge tool.

**Comment by atovpeko** [comment]
@EmmaAzureAgora you can review the work done in the attached PR - are you happy with the changes?
