### ISSUE TITLE
[Correction]: Differences on Interactive Live Streaming and Broadcast Streaming

### ISSUE THREAD

**Issue by morcena09** [AgoraIO/Docs-Source#1523]
### Platform

Web

### Product

Interactive Live Streaming

### Product details

Users mainly cannot identify the differences between Interactive LiveStreaming and Broadcast streaming.

- Additionally, the document provide samples the same as the communication profile | mode: rtc instead of specifying "live".

- There were also no sample specifications of the audience latency type which is crucial for identifying an Interactive LiveStreaming session apart from the Broadcast Streaming session. This somehow is present in the API example: https://github.com/AgoraIO/API-Examples-Web/blob/main/src/example/basic/basicLive/index.js#L77 ... but not in the documentation link sample codes.

- Manage user role section also appears to be missing.

### Business Case

To differentiate and utilize when to use Interactive Live Streaming and Broadcast streaming

### Documentation Link

https://docs.agora.io/en/interactive-live-streaming/get-started/get-started-sdk?platform=web#configure-an--instance-and-set-up-an-event-handler-1

and..

https://docs.agora.io/en/broadcast-streaming/get-started/get-started-sdk?platform=web#configure-an--instance-and-set-up-an-event-handler-1

### Acceptance Criteria

Document section much be precise on each topic, explaining the differences of topics appearing to be mostly similar.

### Additional Information

Discussed in slack section: https://agoraiodev.slack.com/archives/CPQP4GMJ9/p1708335648433199

**Comment by saudsami** [comment]
Reference app updated
