### ISSUE TITLE
[Documentation]: Provide ways to optimize app when using Broadcast Streaming

### ISSUE THREAD

**Issue by hrithikm2** [AgoraIO/Docs-Source#1524]
### Platform

Flutter

### Platform details

Using Agora RTC Engine SDK for broadcast streaming makes the app in the Release version go over 150MB in size. Some platform-specific guidance on reducing size is appreciated.

### Product

Broadcast Streaming

### Business Case

A smaller app size means quicker download and installation times, which can lead to a better user experience. This page shows you how to manually install the Video SDK and reduce the app size of the SDK-integrated app.

### Documentation Link

https://docs.agora.io/en/broadcast-streaming/reference/downloads?platform=flutter

### Acceptance Criteria

- The documentation must include ways to reduce the size of the app instead of suggesting to use of Voice SDK.

**Comment by atovpeko** [comment]
Ticket for tracking: https://jira.agoralab.co/browse/ENDOC-92. If you could open future tickets on this JIRA board, we will appreciate it. Thank you.
