### ISSUE TITLE
Is "AudioRecorderDeviceManager" a typo for "AudioRecordingDeviceManager"?

### ISSUE THREAD

**Issue by CloudsOtsubo** [AgoraIO/Docs-Source#1527]
### Platform

Unity

### Product

Voice Calling

### Business Case

Avoid confusion when migrating a project using AudioRecordingDeviceManager of AgoraSDK ver 3.* to ver 4.*.

### Documentation Link

https://docs.agora.io/en/video-calling/develop/migration-guide?platform=unity

### Scope

AudioRecorderDeviceManager → AudioRecordingDeviceManager

### Acceptance Criteria

none in particular

**Comment by atovpeko** [comment]
Assigned to Hussain: https://jira.agoralab.co/browse/ENDOC-116
