### ISSUE TITLE
[Bug]: Dynamically loading .so files is no longer permitted. 

### ISSUE THREAD

**Issue by blaisethomas** [AgoraIO/Docs-Source#1530]
### Platform

Android

### Platform details

An app distributed via Google Play may not modify, replace, or update itself using any method other than Google Play's update mechanism. Likewise, an app may not download executable code (such as dex, JAR, .so files) from a source other than Google Play. This restriction does not apply to code that runs in a virtual machine or an interpreter where either provides indirect access to Android APIs (such as JavaScript in a webview or browser).

https://support.google.com/googleplay/android-developer/answer/9888379?hl=en

### Product

Video Calling

### Business Case

https://support.google.com/googleplay/android-developer/answer/9888379?hl=en

### Documentation Link

https://support.google.com/googleplay/android-developer/answer/9888379?hl=en

### Acceptance Criteria

- The documentation should be updated to remove suggestions of ddynamically loading .so files.

**Comment by atovpeko** [comment]
JIRA ticket for tracking: https://jira.agoralab.co/browse/ENDOC-140
