### ISSUE TITLE
Consistency with package manager

### ISSUE THREAD

**Issue by tadaspetra** [AgoraIO/Docs-Source#1534]
At the top of the react quickstart, it uses npm, and then in the references, it uses yarn. Ideally, it would be best to have tabs for the popular ones, but at the least, they should be consistent.

<img width="850" alt="Screenshot 2024-04-22 at 2 24 44 PM" src="https://github.com/AgoraIO/Docs-Source/assets/60107328/4da5fc28-c01a-436d-b0ef-b43104f77624">

**Comment by atovpeko** [comment]
The docs have been updated and no longer use reference apps. Closing this as no longer relevant
