### ISSUE TITLE
 Error Codes are not documented in error reference page

### ISSUE THREAD

**Issue by a-oboh** [AgoraIO/Docs-Source#1535]
### Platform

Flutter

### Product

Chat

### Business Case

Adding documentation for the error codes will make it easier to understand what they mean when catching exceptions and help us fix issues faster.

### Documentation Link

https://docs.agora.io/en/agora-chat/reference/error-codes

### Acceptance Criteria

- The error codes should be documented for users

**Comment by atovpeko** [comment]
According to the responsible PO Lance Huang, since the page is already pointing to the relevant iOS and Android pages with error descriptions, no duplication of effort is needed. Thank you.
