### ISSUE TITLE
Flexible Classroom Secure authentication with tokens update

### ISSUE THREAD

**Issue by SunGiantor** [AgoraIO/Docs-Source#1538]
Flexible Classroom adopts the EducationTokenBuilder, which encapsulates AccessToken2 for generating the corresponding token. The process diagram, example code, and verification code in the oversea documentation for token generation are incorrect. Please refer to the Chinese documentation for assistance in adjusting them. Thank you

Please refer to this Chinese document and modify all the content of the English document accordingly, updating all the content. Thank you very much.

url:
https://docs.agora.io/en/flexible-classroom/develop/authentication-workflow?platform=web

refer to this url：
https://doc.shengwang.cn/doc/flexible-classroom/javascript/basic-features/generate-token#accesstoken2-%E7%94%9F%E6%88%90%E5%99%A8%E4%BB%A3%E7%A0%81

<img width="1427" alt="image" src="https://github.com/AgoraIO/Docs-Source/assets/6038975/688f46ef-5f48-46af-ad44-26c2d8617f31">
<img width="1333" alt="image" src="https://github.com/AgoraIO/Docs-Source/assets/6038975/1164a66f-9a5e-4f5f-8a0a-beee3edf3fe5">
<img width="1353" alt="image" src="https://github.com/AgoraIO/Docs-Source/assets/6038975/a9c24f41-b560-4bea-81ed-a80fb1aeea4f">
<img width="1473" alt="image" src="https://github.com/AgoraIO/Docs-Source/assets/6038975/7848c25a-442f-4ae2-9f1a-99b8936c599e">

**Comment by atovpeko** [comment]
Tracking: https://jira.agoralab.co/browse/ENDOC-247
