### ISSUE TITLE
FCR restful-api/classroom-api?platform=web#create-a-classroom update

### ISSUE THREAD

**Issue by SunGiantor** [AgoraIO/Docs-Source#1548]
URL:https://docs.agora.io/en/flexible-classroom/restful-api/classroom-api?platform=web#create-a-classroom
1、roomType add a value "10:Cloud Small classroom"
<img width="1744" alt="image" src="https://github.com/AgoraIO/Docs-Source/assets/6038975/007a34a9-10da-4608-902b-4a9a93067acf">

2.To create a Cloud Classroom, followings are the required parameters: 
update to ”To create a Cloud Small Classroom, followings are the required parameters:“

{
    ...
    "roomName":"{roomName}",
    "roomType":10,
    "roleConfig":{
        "2":{
            "defaultStream":{
                "audioState":1,
                "state":1,
                "videoState":1
            },
            "limit":49
        }
    },
  ...
}
<img width="1470" alt="image" src="https://github.com/AgoraIO/Docs-Source/assets/6038975/30816a53-450e-45d5-8a5d-78e6b32bf63f">

**Comment by Monichen-agora** [comment]
Here too: 
https://docs.agora.io/en/flexible-classroom/restful-api/classroom-api?platform=web#query-a-classroom

<img width="615" alt="Screenshot 2024-05-23 at 3 58 09 PM" src="https://github.com/AgoraIO/Docs-Source/assets/77456831/cccbf412-468c-47fb-9621-47ae4c22d13d">
