### ISSUE TITLE
Flutter Quickstart overly complicated

### ISSUE THREAD

**Issue by tadaspetra** [AgoraIO/Docs-Source#1549]
A general comment about the Flutter quickstart is that it is overly complicated for being a "quick start". The `messageCallback` and `eventCallback` seem to be an opinionated messaging system built along with the quickstart. This seems to be an extra feature, that is unnecessary to start. 

Not only that, those functions are not covered anywhere on this page. So, if a user copies all the code into their project, they will have errors.

Removing this messaging system would remove about 75% of the code in this snippet, making it much more readable. Any gaps left by this can be filled in with a paragraph above.

![Screenshot 2024-05-28 at 2 10 11 PM](https://github.com/AgoraIO/Docs-Source/assets/60107328/bfe061ab-8e85-4808-a732-3d456699f459)

There are other examples of unnecessary code throughout the document. For example `int localUid = -1` is declared, but never used. Same thing with `isBroadcaster`.

**Comment by atovpeko** [comment]
@tadaspetra I can't find this page in the current docs. Can you please check if there is still an issue?

**Comment by tadaspetra** [comment]
you are right, it's no longer there
