### ISSUE TITLE
Agora Documentation is not update date with the latest version of the `react-native-chat-uikit`

### ISSUE THREAD

**Issue by mudassiriqball** [AgoraIO/Docs-Source#1571]
### Platform

iOS

### Platform details

React Native iOS & Android

### Product

Chat UI Kit

### Product details

The latest version of the code has undergone major changes, which are not reflected in the current documentation. Key differences include:

**Components and Props**: The structure and usage of components and props have changed significantly. The props used in the new version are different from those described in the documentation.

**Removed Elements:** Several components, such as ChatFragment and UikitContainer, are no longer present in the updated version.

Please ensure to refer to the latest codebase for accurate implementation details. The current documentation is outdated and may lead to confusion.
[react-native-chat-uikit](https://github.com/AgoraIO-Usecase/AgoraChat-UIKit-rn/tree/main/packages/react-native-chat-uikit) latest version doest not contain `ChatFragment`, `UikitContainer` etc. Props are totally changed.

### Business Case

Documentation should be according to the latest version of the [react-native-chat-uikit](https://github.com/AgoraIO-Usecase/AgoraChat-UIKit-rn/tree/main/packages/react-native-chat-uikit)

### Documentation Link

https://docs.agora.io/en/agora-chat/get-started/get-started-uikit?platform=react-native

### Acceptance Criteria

Documentation should be according to the latest version of the [react-native-chat-uikit](https://github.com/AgoraIO-Usecase/AgoraChat-UIKit-rn/tree/main/packages/react-native-chat-uikit)

**Comment by atovpeko** [comment]
The docs are being updated, the latest draft is here: https://github.com/AgoraLab/agora-chat-uikit

**Comment by mudassiriqball** [comment]
> The docs are being updated, the latest draft is here: https://github.com/AgoraLab/agora-chat-uikit

-> 404, unable to access.

**Comment by atovpeko** [comment]
@saudsami could you please provide access to the repo.
