### ISSUE TITLE
Cloud Recording documentation includes seemingly irrelevant content

### ISSUE THREAD

**Issue by tadaspetra** [AgoraIO/Docs-Source#1578]
As I was exploring the Cloud Recording documentation, I clicked on the "Core Concepts" to understand how Cloud Recording works under the hood. This page, however doesn't mention Cloud Recording, and is a general Agora concepts page. 

![Xnapper-2024-07-15-15 44 08](https://github.com/user-attachments/assets/24244872-a3ed-46ee-882b-a22c466f2e82)

**Comment by saudsami** [comment]
Added cloud-recording concepts
