### ISSUE TITLE
[Bug]: incomplete syntax in create chat group line

### ISSUE THREAD

**Issue by SidRao1331** [AgoraIO/Docs-Source#1580]
### Platform

Web

### Product

Chat

### Business Case

Cuts down time in exploring what is causing the issue

### Documentation Link

https://docs.agora.io/en/agora-chat/client-api/chat-group/manage-chat-groups?platform=web#create-and-destroy-a-chat-group

### Scope

the create chat group document must be updated

conn.createGroup(option).then((res) => console.log(res));

there is a check in the agora-chat.js that is as follows

          function d(e3) {
            if (!e3 || !e3.data)
              throw Error("Invalid parameter");
 
when option is sent it populates e3 but not e3.data despite the parameters being correct, hence the parameters need to be sent as
conn.createGroup({ data: options });

### Acceptance Criteria

conn.createGroup(option).then((res) => console.log(res));

there is a check in the agora-chat.js that is as follows
          function d(e3) {
            if (!e3 || !e3.data)
              throw Error("Invalid parameter");
 
when option is sent it populates e3 but not e3.data despite the parameters being correct, hence the parameters need to be sent as
conn.createGroup({ data: options });

**Comment by atovpeko** [comment]
@SidRao1331 should the sample code be updated like this then?

```
conn.createGroup(option).then((res) => console.log(res));
      function d(e3) {
        if (!e3 || !e3.data)
          throw Error("Invalid parameter");
```

**Comment by SidRao333** [comment]
@atovpeko no I think removing e3.data from the if condition should work. In the documentation they dont send the option via data, there is nothing under e3 called data so e3.data not existing is causing the issue.

**Comment by SidRao1331** [comment]
@atovpeko Yes this would make it work. It would be inconsistent with other sdk commands but it would work.
