### ISSUE TITLE
The "Volume control and mute" for ReactJS doesn't cover how to do this.

### ISSUE THREAD

**Issue by tadaspetra** [AgoraIO/Docs-Source#1593]
I feel like this is a core feature, and should be covered so beginners are not lost

**Comment by digitallysavvy** [comment]
@hussain-khalid was this integrated or can you provide an update as to why this was closed?

**Comment by hussain-khalid** [comment]
Yes, we've developed some documentation that will be published soon. In the meantime, you can try these samples to address your issue:  
[Agora Video SDK Samples for ReactJS](https://github.com/AgoraIO/video-sdk-samples-reactjs).
