### ISSUE TITLE
[4.5.0 RTC Native platforms] Release Notes&API Refs

### ISSUE THREAD

**Issue by Suri539** [AgoraIO/Docs-Source#1600]
Hi,

The v4.5.0 API refs and release notes for **native platforms** are ready. You can find the english source at this tag: https://github.com/AgoraIO/agora_doc_source/tree/v.4.5.0-native-source/dita/RTC-NG.

You can find the english release notes for native platforms in agora_doc_source/markdown/RTC 4.x/release-notes/en-US/native and do the editing work if needed. 

For the English API ref, please see this PR: https://github.com/AgoraIO/agora_doc_source/pull/3828/files. We have made a quick review on the language. @atovpeko Please leave your comments on the PR if you find it is necessary to modify the wording. Thanks!

**Comment by Suri539** [comment]
Hi,

There's something wrong with the tag as it should not be tagged on the english translation commit. Please try this one: https://github.com/AgoraIO/agora_doc_source/releases/tag/v.4.5.0-native-source I've checked the changes are included.
________________________________
发件人: Saud ***@***.***>
发送时间: 2024年11月18日 20:04
收件人: AgoraIO/Docs-Source ***@***.***>
抄送: Fan,Yuanyuan ***@***.***>; Author ***@***.***>
主题: Re: [AgoraIO/Docs-Source] [4.5.0 RTC Native platforms] Release Notes&API Refs (Issue #1600)


Hi,
It seems that this tag does not include updates to the ditamap files in dita\RTC-NG\
Can you please check?

―

**Comment by Suri539** [comment]
Hi, a new API was required to be included in the RTC 4.5.0 native release on last Friday. Please ensure this newly-added API is also included in the EN docs.
The english source of this API: https://github.com/AgoraIO/agora_doc_source/commit/4ac9bd8735539017f8f78103bc048186a665e40c
The ditamap diff:
https://github.com/AgoraIO/agora_doc_source/pull/3840/files#diff-043357f3801caf9b9274647381b06f8d9ec592c43837c46698d069c65101b74b

**Comment by saudsami** [comment]
Updated
There was a missing files in the api folder and some missing keys. I copied these from the CN folder to make it work.

**Comment by saudsami** [comment]
The following file was missing:
en-US/dita/RTC-NG/API/api_rte_destroy.dita

The following files were missing the `Destroy_Rte` key:
en-US/dita/RTC-NG/config/keys-rtc-ng-api-cpp.ditamap
‎en-US/dita/RTC-NG/config/keys-rtc-ng-api-java.ditamap

**Comment by Suri539** [comment]
> The following file was missing: en-US/dita/RTC-NG/API/api_rte_destroy.dita
> 
> The following files were missing the `Destroy_Rte` key: en-US/dita/RTC-NG/config/keys-rtc-ng-api-cpp.ditamap ‎en-US/dita/RTC-NG/config/keys-rtc-ng-api-java.ditamap
> 
> Please let me know when the english source is updated.

The updated source is in #1602 and I've checked that the api_rte_destroy.dita file and  maps can be found here: https://github.com/AgoraIO/agora_doc_source/compare/v.4.5.0-native-source...4.5.0-API-update
