### ISSUE TITLE
[Bug]: Not able to see Agora Error Codes 

### ISSUE THREAD

**Issue by Aditya-Thakur-369** [AgoraIO/Docs-Source#1601]
### Platform

All or multiple (please specify)

### Platform details

I am not able to view Agora Error Codes in Agora Docs `https://docs.agora.io/en/agora-chat/reference/error-codes?platform=flutter`,So i am having issue cause i am getting an error code -102 and i am unable to find and fix it.

### Product

Other

### Business Case

I am not able to view Agora Error Codes in Agora Docs `https://docs.agora.io/en/agora-chat/reference/error-codes?platform=flutter`,So i am having issue cause i am getting an error code -102 and i am unable to find and fix it.

### Subject Matter Expert

I am not able to view Agora Error Codes in Agora Docs `https://docs.agora.io/en/agora-chat/reference/error-codes?platform=flutter`,So i am having issue cause i am getting an error code -102 and i am unable to find and fix it.

### Documentation Link

https://docs.agora.io/en/agora-chat/reference/error-codes?platform=flutter

### Acceptance Criteria

I am not able to view Agora Error Codes in Agora Docs `https://docs.agora.io/en/agora-chat/reference/error-codes?platform=flutter`,So i am having issue cause i am getting an error code -102 and i am unable to find and fix it.

**Comment by saudsami** [comment]
Refer to the error codes for [Android](https://docs.agora.io/en/agora-chat/reference/error-codes?platform=android) and iOS.

**Comment by Aditya-Thakur-369** [comment]
It is for flutter !

**Comment by saudsami** [comment]
The error codes and descriptions are the same.
