### ISSUE TITLE
Downloads, Migration guide and Release notes for macOS

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#163]
Business case - developers need to create the best quality connection for each channel and workflow
Subject Matter Expert - @maxxfrazer . Find the SDK, API ref and a get started here: https://docs-preprod.agora.io/en/live-streaming-premium-4.x-beta/landing-page?platform=MacOS
Reviewer - @nirm2009
Scope - Existing docs: https://github.com/AgoraIO/Docs-Source/blob/milestone4-flutter/interactive-live-streaming/reference/release-notes.mdx, https://github.com/AgoraIO/Docs-Source/blob/milestone4-flutter/interactive-live-streaming/reference/downloads.mdx, https://github.com/AgoraIO/Docs-Source/blob/milestone4-flutter/interactive-live-streaming/develop/migration-guide.mdx.
Acceptance criteria - developers must be able to easily implement video and voice calling functionality for MacOS
Milestone branch - https://github.com/AgoraIO/Docs-Source/tree/milestone17-macos

**Comment by lemon-chen** [comment]
Migration guide for macOS: 
[migration_mac.md](https://github.com/AgoraIO/Docs-Source/files/9643511/migration_mac.md)

**Comment by lemon-chen** [comment]
Release notes for macOS 4.0.1:
- Voice call: 
[release_mac_audio_ng.md](https://github.com/AgoraIO/Docs-Source/files/9655235/release_mac_audio_ng.md)
- Video call and ILS:
[release_mac_ng.md](https://github.com/AgoraIO/Docs-Source/files/9655238/release_mac_ng.md)
