### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#166]
Business case - developers need to easily implement Agora functionality using Video SDK in a Windows App
Fix version - hard release
Subject Matter Expert - Iain. Find the SDK, API ref and a get started here: https://docs-preprod.agora.io/en/live-streaming-premium-4.x-beta/custom_video_source_windows_ng?platform=Windows. Write in C++
Reviewer - team
Scope - Get started for Video Calling, Voice Calling and ILS. Existing doc: https://github.com/AgoraIO/Docs-Source/blob/main/interactive-live-streaming/get-started/get-started-sdk.mdx. 
Estimated - rough guess, 22 days overall
Acceptance criteria - developers must be able to easily implement video calling functionality for MacOS
Milestone branch - https://github.com/AgoraIO/Docs-Source/tree/milestone18-windows

**Comment by hussain-khalid** [comment]
![image](https://user-images.githubusercontent.com/72780625/197972390-7a0f7134-2040-46d9-aebe-2328fbfac2c7.png)

**Comment by hussain-khalid** [comment]
My procedure is  [here](https://github.com/AgoraIO/Docs-Source/tree/166-quickstart-windows)

**Comment by hussain-khalid** [comment]
.
