### ISSUE TITLE
Integrate a token generator 

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#169]
Business case - developers need to easily implement Agora functionality using Video SDK in a Windows App
Fix version - hard release
Subject Matter Expert - Iain. Find the SDK, API ref and a get started here: https://docs-preprod.agora.io/en/live-streaming-premium-4.x-beta/custom_video_source_windows_ng?platform=Windows. Write in C++
Reviewer - team
Scope - Existing doc: https://github.com/AgoraIO/Docs-Source/blob/main/interactive-live-streaming/develop/integrate-token-generation%20copy.mdx. Add the C++ implementation. 
Acceptance criteria - developers must be able to easily implement video calling functionality for Windows
Milestone branch - https://github.com/AgoraIO/Docs-Source/tree/milestone18-windows

**Comment by Pankajg123** [comment]
closed as merged.
