### ISSUE TITLE
Downloads, Migration guide and Release notes for Electron

### ISSUE THREAD

**Issue by hussain-khalid** [AgoraIO/Docs-Source#186]
Business case - developers need to easily implement core features
Fix version - hard release
Subject Matter Expert - @billy-the-fish , @lemon-chen:  Find the SDK, API ref and a get started here: https://docs-preprod.agora.io/en/live-streaming-premium-4.x-beta/landing-page?platform=Electron, Existing docs: https://github.com/AgoraIO/Docs-Source/blob/milestone4-flutter/interactive-live-streaming/reference/release-notes.mdx, https://github.com/AgoraIO/Docs-Source/blob/milestone4-flutter/interactive-live-streaming/reference/downloads.mdx, https://github.com/AgoraIO/Docs-Source/blob/milestone4-flutter/interactive-live-streaming/develop/migration-guide.mdx. 
Reviewer - @Kishan-Dhakan 
Scope - ILS, Video SDK, Voice SDK. Careful, it ain't the same for voice.
Video SDK: download is https://docs.agora.io/en/video-call-4.x-beta/downloads?platform=All%20Platforms
Voice SDK: download is https://docs.agora.io/en/voice-call-4.x-beta/downloads?platform=All%20Platforms.
Acceptance criteria - developers must be able to easily implement video and voice calling functionality for flutter
Milestone branch - https://github.com/AgoraIO/Docs-Source/milestone/1.

**Comment by lemon-chen** [comment]
Migration guide for Electron: 
[migration_guide_electron_ng.md](https://github.com/AgoraIO/Docs-Source/files/9643532/migration_guide_electron_ng.md)

**Comment by lemon-chen** [comment]
Release notes for Electron voice call: 
[release_electron_audio_ng.md](https://github.com/AgoraIO/Docs-Source/files/9653085/release_electron_audio_ng.md)

**Comment by lemon-chen** [comment]
Release notes for Electron video call and ILS:
[release_electron_ng.md](https://github.com/AgoraIO/Docs-Source/files/9653094/release_electron_ng.md)
