### ISSUE TITLE
Review migrated docs: Agora Analytics

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#191]
Review the migrated docs for AA, find broken links, missing information, obsolete content, and improper architecture.

**Comment by dengyaxi** [comment]
@billy-the-fish A wrap-up for our architecture discussions for Analytics:

What we both agree:
- Overview
- Reference

What needs further thoughts:
A "Develop" section doesn't go well with this product. 
- Do we just group them using product name such as Video Calling and Chat?
- Or do we add another top layer called "Analyze"? In this way it would be `Analyze/Video Calling/Call Inspector/Call Inspector Overview`. If so, the "Call Inspector Overview" CANNOT be nested under a collapsible menu on the new site
