### ISSUE TITLE
Review migrated docs: Cloud Recording

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#192]
Review the migrated docs for Cloud Recording, find broken links, missing information, obsolete content, and improper architecture.

**Comment by Chuchun1991** [comment]
The platform selector is useless for server-side docs.

**Comment by Chuchun1991** [comment]
You may add Cloud recording related concepts into Core concepts.

**Comment by Chuchun1991** [comment]
Quickstart
The link is not jumping to the correct location. This issue needs to be checked in the full text.
<img width="755" alt="image" src="https://user-images.githubusercontent.com/78007051/185339043-d041ae93-da79-4384-8ae3-0e9b1b0d59e0.png">
The title of "Start recording" is different with other steps.
<img width="263" alt="image" src="https://user-images.githubusercontent.com/78007051/185339701-6032c60e-f25c-4c2d-af5b-d4c1df7f71dc.png">
<img width="771" alt="image" src="https://user-images.githubusercontent.com/78007051/185340436-d050fb69-0045-41f8-ac83-46285dab0020.png">
<img width="786" alt="image" src="https://user-images.githubusercontent.com/78007051/185348041-6d8d15cf-eebe-44a8-88c9-9a5992a0011f.png">

**Comment by Chuchun1991** [comment]
Pricing
- Recording Audio should be Recording video
<img width="674" alt="image" src="https://user-images.githubusercontent.com/78007051/185362806-5488a2b3-8f0b-48a6-965a-7ae39aa806cb.png">

**Comment by Chuchun1991** [comment]
Release notes
Agora Native 3.x SDK v1.7.0,  Agora Native 4.x SDK v4.0.0 or later.
<img width="478" alt="image" src="https://user-images.githubusercontent.com/78007051/185368681-240beea2-6099-485e-8114-3f4730332ed1.png">

**Comment by Chuchun1991** [comment]
Composite recording
Add the sentence in the short description:
This guide includes the key steps in using the Cloud Recording RESTful API to make an composite recording.

**Comment by Chuchun1991** [comment]
Web page recording
Delete this attention:
<img width="781" alt="image" src="https://user-images.githubusercontent.com/78007051/185536671-3ce769d6-5b9e-43c3-89b3-44a401e5df38.png">

**Comment by Chuchun1991** [comment]
Capture screenshots
<img width="802" alt="image" src="https://user-images.githubusercontent.com/78007051/185536773-e4e2d328-669d-4371-bf5a-092a5ea57d31.png">

**Comment by Chuchun1991** [comment]
Play recorded files online
Introduction -> Overview

**Comment by Chuchun1991** [comment]
Set Video Layout
image missing
<img width="757" alt="image" src="https://user-images.githubusercontent.com/78007051/185537858-c509ca6f-b0f0-4261-92ad-c4901b7fb886.png">
<img width="584" alt="image" src="https://user-images.githubusercontent.com/78007051/185537923-c2d03c41-ac7c-4a87-b235-fd0d1457b22a.png">
<img width="732" alt="image" src="https://user-images.githubusercontent.com/78007051/185537936-229c8977-e829-468d-ad4b-e1421b32fd71.png">
<img width="761" alt="image" src="https://user-images.githubusercontent.com/78007051/185537969-544a5053-e87f-4a3a-9433-51bcfeea29ad.png">

**Comment by Chuchun1991** [comment]
Some guides are the next steps of individual recording, some guides are the next steps of composite recording, and some guides are the next steps of web page recording, and we should show their order and hierarchical structure.

**Comment by Chuchun1991** [comment]
Most of the images are not shown.

**Comment by Chuchun1991** [comment]
Rest API -> RESTful API
Rest and RESTful API are different, and Agora uses RESTful API.
<img width="298" alt="image" src="https://user-images.githubusercontent.com/78007051/185538765-4e645081-b5ff-42eb-991a-6fccd3aaa266.png">
