### ISSUE TITLE
Sample project for voice calling is actually for broadcasting

### ISSUE THREAD

**Issue by xiaov8** [AgoraIO/Docs-Source#194]
Agora provides an open source interactive live broadcast example project [JoinChannelAudio](https://github.com/AgoraIO/API-Examples/tree/4.0.0-beta/Android/APIExample/app/src/main/java/io/agora/api/example/examples/basic) on GitHub for your reference.

**Comment by billy-the-fish** [comment]
Hi, 
    Just to double check, we are talking about the sample link in the product overview, right: https://agoradocs.vercel.app/voice-calling/overview/product-overview. If so,. I'm not sure that the samples link can go to anywhere other than the root of the API samples. The samples are organized by platform; when the end user is on the product overview, we don't know which platform they have chosen. If there are a platform independent voice samples i'd love to link to them.

**Comment by atovpeko** [comment]
@xiaov8 please let me know if Iain's reply was sufficient and I will close this ticket if so.

**Comment by atovpeko** [comment]
Closing the ticket. Please open a new one if there is still an issue. Thank you :-)
