### ISSUE TITLE
Review rewritten and migrated docs: RTC 4.x

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#197]
Review the migrated docs for RTC 4.x to find broken links, missing information, obsolete content, and improper architecture.

Use the following branches to review:
- `main` for the Docs repo
- `main` for the docs submodule (Docs-Source repo)

**Comment by Cilla-luodan** [comment]
Ensure event quality：
The title doesn't clearly state the purpose of this guide, could you consider optimizing it?
I think the word "event" is a little misleading.

**Comment by Chuchun1991** [comment]
Implement the authentication workflow with Video SDK
Why pass a temp token here？This step is pre-step to retrieve a token from the server.
<img width="923" alt="Add variables1" src="https://user-images.githubusercontent.com/78007051/184785867-3b908e2a-ef96-4ebd-b1bb-5d0a0eb86741.png">

**Comment by Chuchun1991** [comment]
Integrate a token generator
Prerequisites:
* An Agora project with the [App Certificate](https://docs.agora.io/en/Agora%20Platform/manage_projects?platform=All%20Platforms#manage-your-app-certificates) enabled.
* We recommend to use an RTC token based on uid, you may add a note in the doc.

**Comment by Chuchun1991** [comment]
Live streaming over multiple channels
Set the source channel info and set the destination channel info should be in the method call. You may add the two steps into the method call step.
<img width="740" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/78007051/184787352-b6118ff9-3579-488b-8ec9-be6954b897b4.png">

**Comment by dengyaxi** [comment]
We should add "Agora Voice SDK" in Reference > Glossary, because it is mentioned in ILS docs
<img width="945" alt="image" src="https://user-images.githubusercontent.com/73678648/185529458-162b84e8-57ca-4a8b-a22e-d0d61f2b1655.png">

**Comment by dengyaxi** [comment]
Closing this issue because all review comments are converted into actions
