### ISSUE TITLE
[4.x SDK] Upgrade token guide to token 007

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#220]
Token 007 is officially out on August 18th, which adds a privilege_expire parameter: https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/java/src/main/java/io/agora/media/RtcTokenBuilder2.java. The Integrate a Token Generator guide should be upgraded to reflect this change.

**Comment by nirm2009** [comment]
On some platforms, updating token guides to token 007 is blocked because new changes aren't available in some npm/github repos.
Repos without token 007 changes:
In https://docs.agora.io/en/interactive-live-streaming/develop/integrate-token-generation#project-setup
> For Web, Electron, React Native: https://www.npmjs.com/package/agora-access-token
> For Windows, Unity: https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/csharp/src/AgoraIO
