### ISSUE TITLE
Catch-up updates: Chat

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#221]
- Business case: the new site needs to present up-to-date documentation for each product
- Scope: every single doc that has been updated since 15:36 on August 2 （**8 月 2 日下午 15:36 分**后有过更新的文档，以 [articlev2](https://articlev2.agoralab.co/) 里显示的更新时间为准）
- Acceptance criteria: List every doc either by title or slug

**Comment by jinyuagora** [comment]
A display issue due to the reuse logic occurred when a product supports several platforms; however, a topic covers only some of them.
<img width="1909" alt="image" src="https://user-images.githubusercontent.com/101544891/191461247-f478c5ad-b87c-4c45-9d0d-fbe26e253113.png">

**Comment by jinyuagora** [comment]
Some of the topics have been changed after the 1st round migration. On my radar:
- [ ] Token
- [ ] Offline push - Flutter & RN

**Comment by jinyuagora** [comment]
Conspicuous indenting of 2nd headers & 3rd headers in ToC. Fairly conspicuous esp. for a large page. Take Content moderation as an example:
<img width="1907" alt="image" src="https://user-images.githubusercontent.com/101544891/191465928-74544f4e-ea4e-4093-8404-55987ece6fd7.png">

**Comment by jinyuagora** [comment]
No rendering for note / warning / alert info.
<img width="1912" alt="image" src="https://user-images.githubusercontent.com/101544891/191470888-dcec6426-087e-4a36-a3c4-3fee4cbd8095.png">

**Comment by dengyaxi** [comment]
All comments resolved in #401
