### ISSUE TITLE
[4.x SDK] Add startEchoTest to the quality guide

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#227]
To ensure the call quality, not only the network quality should be tested, but also whether the hardware or device is working properly. On mobile platforms, that is, Android and iOS, startEchoTest is the only method that tests both the network quality and the device. We need to add this function.

**Comment by billy-the-fish** [comment]
I seem to recall that we took this out because the callback was not working. I'll check with the team. If it works again and we have time we will add it. However, probably post release.

**Comment by billy-the-fish** [comment]
The callback that was not working is https://agora-api-reference.vercel.app/video-sdk/electron/4.0.0-beta.2/API/class_irtcengineeventhandler.html#callback_ontokenprivilegewillexpire, I believe this is true for all platforms. @hussain-khalid, @saudsami, can you please try with the latest SDK release and see if things have improved.

**Comment by saudsami** [comment]
Added Echo test to the Android video-calling and voice-calling docs. 
The code works well with the latest SDK.
The updated doc is available in this branch:
https://github.com/AgoraIO/Docs-Source/tree/384-review-android-docs-and-validate-code-with-the-latest-sdk

**Comment by saudsami** [comment]
On the Flutter platform, only the audio echo test is available but it does not work in SDK 6.0.0-rc.2

**Comment by hussain-khalid** [comment]
In electron, startEchoTest is not working. it gives -110 error when I run the method. Here is my code:
[echotest.txt](https://github.com/AgoraIO/Docs-Source/files/9636330/echotest.txt)

**Comment by hussain-khalid** [comment]
This call is not working: https://agora-api-reference.vercel.app/video-sdk/electron/4.0.0-beta.2/API/class_irtcengineeventhandler.html#callback_ontokenprivilegewillexpire. I tried using onRequestToke and its working.

**Comment by hussain-khalid** [comment]
I am facing same problem in Unity. The StartEchoTest method does not work.
