### ISSUE TITLE
(Nice to have)[4.x SDK] Update the Android and iOS screen share guide

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#228]
In 4.0.0, both Android and iOS add the startScreenCapture method for screen sharing. The current screen share guides use native method for this feature and should be updated.
API Reference for startScreenCapture on Android: https://docs-preprod.agora.io/en/video-call-4.x-beta/API%20Reference/java_ng/v4.0.0-beta.2/API/class_irtcengine.html#api_startscreencapture_ng; 
on iOS:  https://confluence.agoralab.co/display/TEKP/4.0.0+API+EN#id-4.0.0APIEN-Screencapture(iOS)

**Comment by billy-the-fish** [comment]
@saudsami , @nirm2009 , can you update for android, iOS and MacOS please.

**Comment by saudsami** [comment]
Updated the Android doc and tested the code.

**Comment by nirm2009** [comment]
Closing the issue since `AgoraEngine.startScreenCapture` is already used on POC3 docs for both iOS, macOS platforms.
