### ISSUE TITLE
[4.x SDK] Add pricing and disable Cloud Proxy to the cloud proxy guide

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#229]
The Pricing and billing section of the Cloud Proxy is missing and should be added: https://docs.agora.io/en/Video/cloudproxy_native?platform=iOS#pricing-and-billing

The disable Cloud Proxy button was a requirement specially made for overseas customers so that they can easily turn the service off on Console. The doc is also added per this request.

The original guide follows the requirement that everything on cloud proxy should be on one page, and the input was from Yaniv's team. So if we want to do this quick, we can add them back as is.

**Comment by billy-the-fish** [comment]
Added to https://github.com/AgoraIO/Docs-Source/pull/394.

**Comment by lemon-chen** [comment]
I don't see the information updated in Cloud Proxy in #394

**Comment by dengyaxi** [comment]
Reopen this issue because cloud proxy is still missing

**Comment by billy-the-fish** [comment]
So, I have updated the page to make deactivation a bit more obvious, it was always there. Cloud proxy billing is in the pricing page with all the other pricing, and has been there for a while: https://agoradocs.vercel.app/interactive-live-streaming/reference/pricing#-billing. 

The idea is to have related information in one place so it is easier to find.
