### ISSUE TITLE
(Nice to have)[4.x SDK] Deprecate setAudioProfile(profile, scenario) in the  audio and voice effect guide

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#230]
setAudioProfile(profile, scenario) is deprecated and replaced by setAudioProfile(profile) and setAudioScenario(scenario). The old method can still be used, but is deprecated in the API Reference and API example. Should be updated.

**Comment by saudsami** [comment]
Updated the code in Android and Flutter docs
