### ISSUE TITLE
(Nice to have)[4.x SDK] Add spatial audio to Audio and voice effects for Android and iOS

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#231]
Spatial audio will be supported for Android and iOS when 4.0.0 is out. Should add it to the voice effect guide.

**Comment by billy-the-fish** [comment]
Please change the title to "3D Spatial Audio”.

For the iOS not supported,  please add:

"If you want to develop now and not wait for the new docs, contact support@agora.io for assistance".

**Comment by billy-the-fish** [comment]
@nirm2009, if you look https://github.com/AgoraIO/API-Examples/blob/4.0.0-GA/iOS/APIExample/Examples/Advanced/SpatialAudio/SpatialAudio.swift, you will find the code you need for spatial audio.

**Comment by billy-the-fish** [comment]
Done.
