### ISSUE TITLE
[4.x SDK] Audio route change principles and examples are missing

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#233]
Audio route is an important feature on mobile platforms, and how it changes according to the users' behavior needs to be documented. https://docs.agora.io/en/live-streaming-premium-4.x-beta/audio_route_ng?platform=Android comes from the developer's note and needs to be added.

**Comment by billy-the-fish** [comment]
I think this is just about there, but in short form: https://agoradocs.vercel.app/video-calling/develop/audio-and-voice-effects#understand-the-tech. 

Do you think we need more?

**Comment by lemon-chen** [comment]
How different APIs (setEnableSpeakerphone and setDefaultAudioRouteToSpeaker) work on the audio route, and how the end user's behavior changes the audio route together with the example.

The audio route guide is not about calling the APIs to change the route, but how the audio route changes when calling an API or when the end user plugs or unplugs a hardware.

**Comment by billy-the-fish** [comment]
Hmm, ok. 

Sadly, I pushed this change to the wrong branch. Can you review in https://github.com/AgoraIO/Docs-Source/pull/430 please.
