### ISSUE TITLE
[4.x SDK] Remove temp token from the authentication workflow guide

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#234]
Why pass a temp token here？The next step is to retrieve a token from the server.
---
![image](https://user-images.githubusercontent.com/73678648/185869660-be9c27c7-fc01-4407-9fb3-664ec3033339.png)

**Comment by billy-the-fish** [comment]
The variable is used later in the code. It is temporary because all tokens are, in their nature, temporary. Not technically wrong so leave as is.
