### ISSUE TITLE
[4.x SDK] Add Agora Voice SDK in Glossary

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#239]
Agora Voice SDK is mentioned in ILS docs but not explained
----
![image](https://user-images.githubusercontent.com/73678648/185874692-6008e0d5-6b88-4358-afcf-78f7c348999b.png)

**Comment by billy-the-fish** [comment]
Pr: https://github.com/AgoraIO/Docs-Source/pull/430

**Comment by dengyaxi** [comment]
validated in PR
