### ISSUE TITLE
[4.x SDK] Recommend developers to generate tokens based on user ID, rather than user account

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#241]
In the Integrate a token generator guide, we should emphasize that generating tokens based on user ID is best practice. Although `buildTokenWithAccount` is supported, it is not recommended to use for some reason

You can either add a note to highlight this information, or hide `buildTokenWithAccount` in the guides

**Comment by billy-the-fish** [comment]
@Dasun, can you update this while you add the docs for the new token generation libraries please.
