### ISSUE TITLE
(Nice to have)[4.x SDK] Use createCustomVideoTrack to implement custom video source

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#243]
4.0.0 added createCustomVideoTrack to implement the feature of custom video source. Compared with setExternalVideoSource, this is a more advanced API that can capture multiple video track. The API Reference draft is here: https://confluence.agoralab.co/display/TEKP/4.0.0+API+EN#id-4.0.0APIEN-Customvideosource

**Comment by hussain-khalid** [comment]
@lemon-chen, the reference draft requires credentials:
![image](https://user-images.githubusercontent.com/72780625/192027411-b58312a0-7b54-42ec-8b40-c815fd50b396.png)

**Comment by billy-the-fish** [comment]
The API is here: https://api-ref.agora.io/en/voice-sdk/android/4.x/API/class_irtcengine.html#api_irtcengine_createcustomvideotrack
