### ISSUE TITLE
[4.x SDK][Web] Known Issues and Workarounds is missing

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#244]
“Known Issues and Workarounds” is missing
---------------
This doc provides important information. Should add it back
https://docs.agora.io/en/Video/web_sdk_known_issues?platform=Web

**Comment by billy-the-fish** [comment]
Hmmmm. This should be in release notes, not as a main doc.

**Comment by dengyaxi** [comment]
@billy-the-fish Hi. Is there any updates on this doc?

**Comment by billy-the-fish** [comment]
@hussain-khalid, can you add the attached file as a section in the Web readme please. 

[web_sdk_known_issues.md](https://github.com/AgoraIO/Docs-Source/files/9640490/web_sdk_known_issues.md)
