### ISSUE TITLE
[4.x SDK][Web] What's the plan for Media Processing Extensions docs

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#245]
Features such as noise reduction and virtual background are offered through extensions (independent npm packages). To use these features, developers need to integrate both the SDK and the extension.

See https://docs.agora.io/en/Video/virtual_background_web_ng?platform=Web

**Comment by billy-the-fish** [comment]
Let's add this to the great extension debate. If it's an extension from Marketplace, it should be there.

**Comment by billy-the-fish** [comment]
I added this extension to the, extensions: -). The code is in https://github.com/AgoraIO/Docs-Source/pull/427.

**Comment by dengyaxi** [comment]
If you take a closer look at the current TOC: https://docs.agora.io/en/video-call-4.x/virtual_background_web_ng?platform=Web, there are three extensions: virtual background, AI denoiser, and image enhancement. But only the former two are included in Marketplace.

For now the product strategy is: they are first and foremost an additional feature of the Web 4.x SDK, and it's only optional to put them on Marketplace. So we still need to figure out a place in the 4.x TOC. 

Maybe add this section in "Develop"?

**Comment by billy-the-fish** [comment]
I will leave as is, discuss with Emily and co and sort this post release. 

Why? If this is part of VSDK, the doc needs to be rewritten to match the 4.x docs, or added to a doc. Also, it is a nice example to use in the discussion as to what an  extension is. If we use the extensions mechanism to add features, fine. But in that case, we have to put it into a story.

**Comment by billy-the-fish** [comment]
Decision was taken to add all three extensions to the develop section. Can you supply me with the source for the image enhancer so that can be added as well please.

**Comment by dengyaxi** [comment]
FYI. Please be sure to mark image enhancer as beta. Thanks

[image_enhancer.md](https://github.com/AgoraIO/Docs-Source/files/9661128/image_enhancer.md)
[noise-reducer.md](https://github.com/AgoraIO/Docs-Source/files/9661130/noise-reducer.md)
