### ISSUE TITLE
Modify the architecture for Analytics docs

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#252]
A wrap-up for our architecture discussions for Analytics:

**What we both agree:**
- Overview
- Reference

**What needs further thoughts:**
A "Develop" section doesn't go well with this product. 
- Do we just group them using product name such as Video Calling and Chat?
- Or do we add another top layer called "Analyze"? In this way it would be `Analyze/Video Calling/Call Inspector/Call Inspector Overview`. If so, the "Call Inspector Overview" CANNOT be nested under a collapsible menu on the new site

**Comment by dengyaxi** [comment]
@billy-the-fish Any great ideas? I know you are pretty occupied but we do need to figure it out asap. The hard launch is around the corner.

You can revisit the latest docset here: https://docs.agora.io/en/Agora%20Analytics/aa_guide?platform=All%20Platforms

Thanks in advance

**Comment by billy-the-fish** [comment]
I see this is done. Let's do a review when you are back from holiday.
