### ISSUE TITLE
[Cloud Recording] Fix title and format in Quickstart

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#262]
Fix the spaces
--------
![image](https://user-images.githubusercontent.com/73678648/186842450-976d02f7-7b57-495f-8c24-cfb450a688ef.png)

**Comment by dengyaxi** [comment]
The title of "Start recording" is different with other steps.
![Uploading image.png…]()

**Comment by dengyaxi** [comment]
The section title "Implement the cloud recording >> Start recording" does not align with other steps.

**Comment by dengyaxi** [comment]
"Authenticate Your Users with Token" should not link to "Implement Basic HTTP authentication". It's the same doc for RTC tokens. See https://docs.agora.io/en/cloud-recording/token_server?platform=RESTful.

**Comment by Kishan-Dhakan** [comment]
Fixed the spacing issue.

> The section title "Implement the cloud recording >> Start recording" does not align with other steps.

This is already fixed in the current main branch.
