### ISSUE TITLE
[Cloud Recording] Add "Authenticate Your Users with Token" in Reference 

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#263]
"Authenticate Your Users with Token" is missing in the docset. Cloud Recording uses RTC tokens to authenticate

**Comment by billy-the-fish** [comment]
@dengyaxi , this is the API token stuff, right? If so include https://github.com/AgoraIO/Docs-Source/blob/main/shared/common/_restful-authentication.mdx  with the correct condition filters for the token part.

**Comment by billy-the-fish** [comment]
Please keep this ticket open. I seem to remember fixing this in another ticket.
