### ISSUE TITLE
Catch-up updates: Cloud Recording

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#265]
Release notes
Agora Native 3.x SDK v1.7.0, Agora Native 4.x SDK v4.0.0 or later.

![image](https://user-images.githubusercontent.com/73678648/186850696-587e7445-60b2-4276-be0a-250c346bca0e.png)

**Comment by billy-the-fish** [comment]
What is Agora Native SDK?

**Comment by Chuchun1991** [comment]
It means Agora SDK for native platforms.
I think the v1.7.0 or v1.12 is too early and rarely used, so the Compatibility here is not a useful information, we can delete the whole section.

**Comment by billy-the-fish** [comment]
Go for it.

**Comment by billy-the-fish** [comment]
I've mad the change and am adding it to other small post-release changes.
