### ISSUE TITLE
(Nice to have)[Cloud Recording] Architecture can be more clear

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#269]
@Chuchun1991 is the tech writer for Cloud Recording. Here is what she thinks about the current architecture:
"Some guides are the next steps of individual recording, some guides are the next steps of composite recording, and some guides are the next steps of web page recording, and we should show their order and hierarchical structure."

**Comment by billy-the-fish** [comment]
Please put the order you are thinking of in here and we can update.

**Comment by billy-the-fish** [comment]
@Chuchun1991, do you have a proposed order?

**Comment by Chuchun1991** [comment]
Sorry I forgot to comment. You can refer to the Chinese document structure to see if you can make some adjustments based on EN document structure.
https://docs.agora.io/cn/cloud-recording/landing-page?platform=RESTful

**Comment by atovpeko** [comment]
Updated to be more in line with the CN version: https://docs.agora.io/en/cloud-recording/overview/product-overview
