### ISSUE TITLE
Intro needed

### ISSUE THREAD

**Issue by embkim** [AgoraIO/Docs-Source#296]
Hi Iain - this page needs a title. Thanks! -e

**Comment by billy-the-fish** [comment]
:-), which page?

**Comment by yamasite** [comment]
@embkim Please clarify. Thanks

**Comment by embkim** [comment]
@billy-the-fish @yamasite I thought the "Suggest an edit" also captured the page. Shouldn't it? I don't remember which page it was anymore, sorry! I'll click around again...-emily

**Comment by billy-the-fish** [comment]
Sigh, it should do. I'll ask if shuvo can add it to the workflow.
