### ISSUE TITLE
First sentence in Media Push overview intro

### ISSUE THREAD

**Issue by ghuddy** [AgoraIO/Docs-Source#299]
Change to: 
Agora Media Push enables you to upload audio and video streams from Agora channels to a Content Delivery Network (CDN) to reach a larger audience.

Sentence changed to remove "pull" from sentence to avoid confusion with Media Pull

**Comment by dengyaxi** [comment]
Fixed in https://github.com/AgoraIO/Docs-Source/commit/35974efda4f44f8e96e50f39461880eb5cefee1a

Will merge before the second internal test
