### ISSUE TITLE
[4.x SDK] Remove media inject from the migration guide

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#311]
Client-side media inject (or injecting an online stream, or Media Pull) has kicked off sunset plans. Better to remove it from the Web migration guide
<img width="826" alt="image" src="https://user-images.githubusercontent.com/73678648/188582962-8242d1e5-d7ca-4651-8c82-a32c895ec463.png">

**Comment by billy-the-fish** [comment]
In Pr: https://github.com/AgoraIO/Docs-Source/pull/431
