### ISSUE TITLE
[post launch] Broadcast Streaming api folder change

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#324]
Hi there, 
   Looks good. One thing, the REST API will be included in the API ref. @lemon-chen is adding the reference now. Can you please move the `restful-api` folder into `shared/broadcast-streaming` directory and update any l inks to point to the external API ref. Please use the <Link to="{{global.BROADCAST_STREAMING_API_REF_REST}}/FOLDER/FILENAME">LINKNAME</Link> linkage. (You will need to create the BROADCAST_STREAMING_API_REF_REST variable in globas.js ).
   We are going to publish the latest updated content today. Do you think this will take you a long time? If so, we can merge as is and make a ticket to update the API ref afterwards. Up to you.
   
      Cheers

     Iain

_Originally posted by @billy-the-fish in https://github.com/AgoraIO/Docs-Source/issues/259#issuecomment-1231393953_

**Comment by billy-the-fish** [comment]
I'm clearing all the unassigned tickets. Can you assign this to the correct writer please.

**Comment by billy-the-fish** [comment]
@dengyaxi I don't understand this ticket. Can we close it?

**Comment by dengyaxi** [comment]
Sure. This can be done when Broadcast Streaming becomes GA in RoW
