### ISSUE TITLE
A few Video Calling copy edits 

### ISSUE THREAD

**Issue by ghuddy** [AgoraIO/Docs-Source#371]
- first word in intro: "Agora's" --> "Agora"
- primary button text: "View UIKit quickstart" --> "UI Kit quickstart"
- button text: "View quickstart" --> "SDK quickstart"
- in Features, AI-powered audio enhancement: "3D Spatial audio" --> "3D spatial audio"

**Comment by Kishan-Dhakan** [comment]
Points 2 and 3 are done in https://github.com/AgoraIO/Docs/pull/27. 1 and 4 are done in https://github.com/AgoraIO/Docs-Source/pull/425.
