### ISSUE TITLE
Cloud Proxy

### ISSUE THREAD

**Issue by bradfordagora** [AgoraIO/Docs-Source#378]
Hi, 

Looks like we are missing Cloud Proxy from the new Docs site. 

Thanks,
Bradford

**Comment by billy-the-fish** [comment]
Hi Bradford, 
   The docs are there, we are just using a more descriptive title: https://agoradocs.vercel.app/video-calling/develop/cloud-proxy. This doc is included for every VSDK based product. 
     Cheers
     
     Iain
