### ISSUE TITLE
Catch-up updates: Media Push & Media Inject (now Media Pull)

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#385]

**Comment by Chuchun1991** [comment]
Enable Media Push 的图都没有了。

**Comment by Chuchun1991** [comment]
API call rate limits的最后两行行，需要改为：
In a project, the rate limit for the rate of updating a specified Converter is 50 times per second.
In a project, the rate limit for the rate of getting the status of a specified Converter is 50 times per second.

**Comment by dengyaxi** [comment]
Add a link to 3.x client-side docs in Develop

**Comment by dengyaxi** [comment]
done via #474
