### ISSUE TITLE
Validate 4.x quickstart for all platforms using v4.0.0 SDK

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#387]
We've discovered a breaking API change from **v4.0.0-beta** to **v4.0.0-rc** in Unity SDK. Following the current quickstart with the latter SDK will get errors. 

Please validate the current quickstarts for all platforms using the latest SDK (either v4.0.0-rc or v4.0.0) before the hard release. Note that for Flutter, the version number is v6.0.0

Known API changes include:
- joinChannel

**Comment by billy-the-fish** [comment]
Hi Yaxi, 
   The team are validating against the latest releases this week as part of their milestones. There are already issues assigned for this work. 

    Cheers

    Iain
