### ISSUE TITLE
Buttons on all product overview pages

### ISSUE THREAD

**Issue by ghuddy** [AgoraIO/Docs-Source#396]
General update to buttons on all overview pages (where applicable):
"View UI Kit quickstart" --> "UI Kit quickstart" 
"View quickstart" --> "SDK quickstart"

**Comment by billy-the-fish** [comment]
Hi Garrett, 
     Totally agree, but this needs to be done in the Doc build repo. Can you add the ticket here please.  https://github.com/AgoraIO/Docs/issues.

   Cheers

    Iain
