### ISSUE TITLE
[Cleanup - Signaling] Incomplete display for Linux Java and Linux C++

### ISSUE THREAD

**Issue by jinyuagora** [AgoraIO/Docs-Source#411]
Signaling Linux is separated into **Linux Java** and **Linux C++**. Some incomplete display issues occur on the following pages:
- Release notes
- Limitations
- SDK quickstart
- Run the sample project
- Manage connection states
- Call invitation
- Geofencing
- Downloads
- Supported platforms
- API reference

**Comment by jinyuagora** [comment]
Possible reason - A finer-grained platform config is required for this product.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/101544891/191700792-51b2b176-ce80-48f1-8b17-97fc739a104a.png">

**Comment by billy-the-fish** [comment]
The source is setup for the two platforms. As you say, need to update products.js to make this visible. This is for @Mr-spShuvo. 

@jinyuagora, can you close this issue and re-create it in https://github.com/AgoraIO/Docs/issues.

**Comment by billy-the-fish** [comment]
In PR: https://github.com/AgoraIO/Docs-Source/pull/433.
