### ISSUE TITLE
[Cleanup - Signaling] Missing sample code

### ISSUE THREAD

**Issue by jinyuagora** [AgoraIO/Docs-Source#413]
Missing content for Geofencing (macOS).
![image](https://user-images.githubusercontent.com/101544891/191703906-24a8f31d-8d44-4d5f-9442-dbd40ecb598c.png)
<img width="425" alt="企业微信截图_c1327e11-34c5-4220-a115-713fdbaa83b1" src="https://user-images.githubusercontent.com/101544891/191704043-f610919a-a13b-4682-bc13-f7f732445221.png">

**Comment by billy-the-fish** [comment]
In PR: https://github.com/AgoraIO/Docs-Source/pull/433
