### ISSUE TITLE
[Cleanup - Signaling] Redundant doc in ToC

### ISSUE THREAD

**Issue by jinyuagora** [AgoraIO/Docs-Source#415]
I don't think this page is needed. It seems incomplete and has nothing to do with Signaling.
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/101544891/191705061-a3dbee8f-7eae-4305-b975-a880b95046f8.png">

**Comment by billy-the-fish** [comment]
In PR: https://github.com/AgoraIO/Docs-Source/pull/433
