### ISSUE TITLE
4.x guides: sample code in Audio and voice effects needs to be updated

### ISSUE THREAD

**Issue by Suri539** [AgoraIO/Docs-Source#416]
hi there! setAudioProfile(AUDIO_PROFILE_TYPE profile, AUDIO_SCENARIO_TYPE scenario) is deprecated in all native platforms.
<img width="775" alt="image" src="https://user-images.githubusercontent.com/84306751/191705034-5f055b0e-cbad-4b53-a8b9-d8019be3676e.png"> 
Now we use setAudioProfile(profile) to set the audio profile and setAudioScenario for audio scenarios. Therefore, the sample code in the Audio and voice effects for Android should be updated.

**Comment by saudsami** [comment]
Code updated in 
https://github.com/AgoraIO/Docs-Source/tree/384-review-android-docs-and-validate-code-with-the-latest-sdk
