### ISSUE TITLE
[4.X SDK] Update the error code guide to reflect the new logic

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#422]
The current error code guide for 4.x can be removed. All error messages are 
- reported in this callback: https://docs.agora.io/en/video-call-4.x/API%20Reference/windows_ng/API/class_irtcengineeventhandler.html#callback_irtcengineeventhandler_onerror, with the ERR_CODE_TYPE enumeration
- reported in the corresponding callback
- returned in the return value of every method

**Comment by billy-the-fish** [comment]
In PR: https://github.com/AgoraIO/Docs-Source/pull/434

I agree we should do a troubleshooting guide. Let's add it to our post-release planning.
