### ISSUE TITLE
Catch-up updates: Interactive Whiteboard

### ISSUE THREAD

**Issue by FayHaifei** [AgoraIO/Docs-Source#426]
**Platform Web missing**—— Shuvo has added

**Updates** @Nero-Hu 
file_conversion_overview (/interactive-whiteboard/reference/file-conversion-deprecated): Added static conversion support
whiteboard_file_conversion: Added static conversion support/updated images field
join_whiteboard_room_android: Updated to v2.16.21
join_whiteboard_room_ios: Updated to v2.16.21
join_whiteboard_room_web: Updated to v2.16.21
release_whiteboard_ios: Updated to v2.16.24
release_whiteboard_android: Updated to v2.16.24
release_whiteboard_web: Updated to v2.16.24

**Content missing:**  @FayHaifei 
whiteboard_file_conversion_old
fastboard_api_android 
fastboard_api_ios
fastboard_api_web
whiteboard_tool 
present_files
present_files_android  
present_files_ios 
qps_based_pricing

**Comment by Nero-Hu** [comment]
**Content missing:**
file_conversion_overview_old

**Comment by dengyaxi** [comment]
@billy-the-fish @atovpeko We are already working on these updates :) No worries
