### ISSUE TITLE
[4.x Web] Cannot find Optimization Mode

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#441]
Optimization Mode is a Web-only guide. Please add it to the 4.x docset.
 Link: https://docs.agora.io/en/video-call-4.x/optimization_mode_web_ng?platform=Web

Source file
[optimization-mode.md](https://github.com/AgoraIO/Docs-Source/files/9645501/optimization-mode.md)

**Comment by billy-the-fish** [comment]
@saudsami, any chance you could find a place for this in the call quality guiide.

**Comment by saudsami** [comment]
Done.
The code was already there in the web doc. I have added a platform-specific explanation of optimization modes under the **Understand the tech** section.
