### ISSUE TITLE
4.x Web does not support raw video and audio processing

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#444]
The "not implemented" message is embedded in the near end of the doc. Should move it up to the beginning

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/73678648/192261607-33abf350-43f5-4a81-9ad8-573f1199fddc.png">

**Comment by billy-the-fish** [comment]
Done: https://agoradocs.vercel.app/interactive-live-streaming/develop/stream-raw-audio-and-video
