### ISSUE TITLE
Catch-up updates: Analytics

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#445]
Top-level TOC:
- Overview
- Analyze
  - Video/Voice SDK
    - Call Inspector (+ Call details breakdown 合成一篇）
    - Data Insights
    - [Real-time Monitoring](https://docs.agora.io/en/Agora%20Analytics/aa_monitor?platform=All%20Platforms)
    - [Alert Notifications](https://docs.agora.io/en/Agora%20Analytics/aa_alarm?platform=All%20Platforms)
    - [Embed in a secure portal](https://docs.agora.io/en/Agora%20Analytics/aa_embeded?platform=All%20Platforms)
  - Chat SDK
    - Data Insights
- Reference
  - Call Inspector Glossary 
  - [Chat Glossary](https://docs.agora.io/en/Agora%20Analytics/analytics_agora_chat_glossary?platform=All%20Platforms)

**Comment by dengyaxi** [comment]
Update the following docs:
- Release notes
- Call Inspector overview (add link for troubleshooting manual)

**Comment by billy-the-fish** [comment]
Looks good. Can we keep the section title to Analyze please. 

Keep sentence case for the doc titles please.
