### ISSUE TITLE
Updates to Interactive Whiteboard overview 

### ISSUE THREAD

**Issue by ghuddy** [AgoraIO/Docs-Source#471]
@billy-the-fish 
Page: https://agoradocs.vercel.app/interactive-whiteboard/overview/product-overview

Updated introduction:
Agora Interactive Whiteboard enables developers to integrate real-time visual collaboration features into their applications. The Interactive Whiteboard SDK gives developers the ability to customize real-time whiteboards for their specific use case. For projects that require the fastest integration, try Agora Fastboard that couples Interactive Whiteboard with a default UI. ​Interactive Whiteboard and Fastboard can be used alone or to add visual collaboration to Voice Calling, Video Calling, and Interactive Live Streaming.

Updated features:
**Editing and room tools** 
Includes standard tools for drawing, writing, notations, and erasing with advanced tools for content sharing, multi-user editing, use case scenario control, room management, and more. 

**File conversion** 
Server-side file conversion transcodes files for presentation on the whiteboard, including support for converting PPT, PPTX, Word, and PDF files to images, and  PPTX files to web pages.  

**Extensions** 
Powerful extensions in [netless-app](https://github.com/netless-io/netless-app) help extend the functionality of your whiteboard experience and [window-manager](https://github.com/netless-io/window-manager) can be used to load and manage extensions on the whiteboard. 

**SDK options** 
Choose from two SDKs: Interactive Whiteboard SDK allows experienced developers to provide substantial customization while Fastboard SDK provides a ready-to-use UI for a faster build. 

**RESTful APIs** 
RESTful APIs provide token generation, room management, screenshot management, scene management, and file conversion features. 

**Stability and reliability** 
Agora's globally distributed and clustered server system and backup and disaster recovery plans work together to guarantee high availability of the whiteboard service.

**Comment by billy-the-fish** [comment]
Done
