### ISSUE TITLE
Search and destroy old links

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#473]
Search for anything with API%20Reference in it and replace with the new links. Same for the FQDN (docs.agora.io). Any any other sort of strange link you find while you are doing this.

**Comment by dengyaxi** [comment]
Nicely put. The CN team is still making updates to some docs, so we will take care of any links in the following products:

- Analytics
- Whiteboard
- Media Push
- Media Pull

Please kindly note @billy-the-fish @hussain-khalid

**Comment by hussain-khalid** [comment]
thank you @dengyaxi

**Comment by billy-the-fish** [comment]
@dengyaxi , Whiteboard should be fine, @atovpeko went over those docs yesterday.

**Comment by dengyaxi** [comment]
Adding 3.x SDK to our scope of checking links.
