### ISSUE TITLE
link fixing Saud

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#495]
Saud, can you fix these links please

  { **FIxed**
  "url": "`/en/agora-class/faq/agora_class_custom_properties/'",
  "name":       "`How can I set user properties?'",
  "Parent URL": "https://docs-staging.agora.io/en/flexible-classroom/reference/classroom-sdk/, line 14, col 69011",
  "Real URL": "https://docs-staging.agora.io/en/agora-class/faq/agora_class_custom_properties/",
  "Result": "Error: 404 Not Found"
  }, { **Does not exist**
  "url": "`/en/agora-chat/restful-api/restful-overview/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace'",
  "Parent URL": "https://docs-staging.agora.io/en/agora-chat/restful-api/restful-overview/, line 14, col 29935",
  "Real URL": "https://docs-staging.agora.io/en/agora-chat/restful-api/restful-overview/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  },
{ **Works**
  "url": "`/en/agora-chat/restful-api/get-started/enable/'",
  "name":       "`enabled and configured Chat in the Console'",
  "Parent URL": "https://docs-staging.agora.io/en/agora-chat/restful-api/restful-overview/, line 31, col 14",
  "Real URL": "https://docs-staging.agora.io/en/agora-chat/restful-api/get-started/enable/",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/agora-chat/restful-api/develop/generate-app-tokens/'",
  "name":       "`Authentication with App Token'",
  "Parent URL": "https://docs-staging.agora.io/en/agora-chat/restful-api/restful-overview/, line 32, col 75",
  "Real URL": "https://docs-staging.agora.io/en/agora-chat/restful-api/develop/generate-app-tokens/",
  "Result": "Error: 404 Not Found"
  }, { **Does not exist**
  "url": "`/en/agora-analytics/reference/api/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace'",
  "Parent URL": "https://docs-staging.agora.io/en/agora-analytics/reference/api/, line 14, col 29454",
  "Real URL": "https://docs-staging.agora.io/en/agora-analytics/reference/api/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  },
{ **Fixed**
  "url": "`/en/agora-analytics/reference/develop/call-inspector/call-search/'",
  "name":       "`Call Inspector'",
  "Parent URL": "https://docs-staging.agora.io/en/agora-analytics/reference/api/, line 17, col 4",
  "Real URL": "https://docs-staging.agora.io/en/agora-analytics/reference/develop/call-inspector/call-search/",
  "Result": "Error: 404 Not Found"
  }, { **Fixed**
  "url": "`/en/agora-analytics/reference/develop/data-insight/'",
  "name":       "`Data Insights'",
  "Parent URL": "https://docs-staging.agora.io/en/agora-analytics/reference/api/, line 20, col 4",
  "Real URL": "https://docs-staging.agora.io/en/agora-analytics/reference/develop/data-insight/",
  "Result": "Error: 404 Not Found"
  },
{ **Fixed**
  "url": "`/en/agora-analytics/reference/develop/monitor/'",
  "name":       "`Real-time Monitoring'",
  "Parent URL": "https://docs-staging.agora.io/en/agora-analytics/reference/api/, line 23, col 4",
  "Real URL": "https://docs-staging.agora.io/en/agora-analytics/reference/develop/monitor/",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/agora-analytics/reference/reference/restful-authentication/'",
  "name":       "`basic HTTP authentication'",
  "Parent URL": "https://docs-staging.agora.io/en/agora-analytics/reference/api/, line 27, col 61",
  "Real URL": "https://docs-staging.agora.io/en/agora-analytics/reference/reference/restful-authentication/",
  "Result": "Error: 404 Not Found"
  }, { **Fixed**
  "url": "`/en/agora-analytics/reference/api/glossary/#appid'",
  "name":       "`App ID'",
  "Parent URL": "https://docs-staging.agora.io/en/agora-analytics/reference/api/, line 65, col 540",
  "Real URL": "https://docs-staging.agora.io/en/agora-analytics/reference/api/glossary/#appid",
  "Result": "Error: 404 Not Found"
  }, { **Fixed**
  "url": "`./glossary#appid'",
  "name":       "`App ID'",
  "Parent URL": "https://docs-staging.agora.io/en/agora-analytics/reference/api/, line 265, col 12",
  "Real URL": "https://docs-staging.agora.io/en/agora-analytics/reference/api/glossary/#appid",
  "Info": "Redirected to"
  },
{ **Does not exist**
  "url": "`/en/cloud-recording/reference/rest-api/rest/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace'",
  "Parent URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/, line 12, col 29460",
  "Real URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  },
{ **Works**
  "url": "`/en/cloud-recording/reference/develop/individual-mode/'",
  "name":       "`Individual recording'",
  "Parent URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/, line 14, col 5",
  "Real URL": "https://docs-staging.agora.io/en/cloud-recording/reference/develop/individual-mode/",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/cloud-recording/reference/develop/composite-mode/'",
  "name":       "`Composite recording'",
  "Parent URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/, line 15, col 5",
  "Real URL": "https://docs-staging.agora.io/en/cloud-recording/reference/develop/composite-mode/",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/cloud-recording/reference/develop/screen-capture/'",
  "name":       "`Capture screenshots'",
  "Parent URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/, line 16, col 5",
  "Real URL": "https://docs-staging.agora.io/en/cloud-recording/reference/develop/screen-capture/",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/cloud-recording/reference/develop/webpage-mode/'",
  "name":       "`Web page recording'",
  "Parent URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/, line 17, col 5",
  "Real URL": "https://docs-staging.agora.io/en/cloud-recording/reference/develop/webpage-mode/",
  "Result": "Error: 404 Not Found"
  },
{ **Fixed**
  "url": "`/en/cloud-recording/reference/rest-api/rest/rest/#project-setup'",
  "name":       "`Quickstart'",
  "Parent URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/, line 22, col 69",
  "Real URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/rest/#project-setup",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/cloud-recording/reference/rest-api/restful-authentication/'",
  "name":       "`basic HTTP authentication'",
  "Parent URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/, line 23, col 99",
  "Real URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/restful-authentication/",
  "Result": "Error: 404 Not Found"
  }, {  **Works**
  "url": "`/en/cloud-recording/reference/rest-api/rest/acquire/'",
  "name":       "`acquire'",
  "Parent URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/, line 35, col 14",
  "Real URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/acquire/",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/cloud-recording/reference/rest-api/rest/start/'",
  "name":       "`start'",
  "Parent URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/, line 36, col 15",
  "Real URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/start/",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/cloud-recording/reference/rest-api/rest/stop/'",
  "name":       "`stop'",
  "Parent URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/, line 37, col 14",
  "Real URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/stop/",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/cloud-recording/reference/rest-api/rest/query/'",
  "name":       "`query'",
  "Parent URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/, line 39, col 43",
  "Real URL": "https://docs-staging.agora.io/en/cloud-recording/reference/rest-api/rest/query/",
  "Result": "Error: 404 Not Found"
  }, { **Does not exist**
  "url": "`/en/extensions-marketplace/develop/implement/provisioning/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace'",
  "Parent URL": "https://docs-staging.agora.io/en/extensions-marketplace/develop/implement/provisioning/, line 14, col 29460",
  "Real URL": "https://docs-staging.agora.io/en/extensions-marketplace/develop/implement/provisioning/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  }, { **Fixed**
  "url": "`/en/extensions-marketplace/develop/implement/provisioning/signature_algorithm/'",
  "name":       "`signature algorithm'",
  "Parent URL": "https://docs-staging.agora.io/en/extensions-marketplace/develop/implement/provisioning/, line 30, col 1618",
  "Real URL": "https://docs-staging.agora.io/en/extensions-marketplace/develop/implement/provisioning/signature_algorithm/",
  "Result": "Error: 404 Not Found"
  },
{ **Does not exist**
  "url": "`/en/extensions-marketplace/develop/implement/usage/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace'",
  "Parent URL": "https://docs-staging.agora.io/en/extensions-marketplace/develop/implement/usage/, line 14, col 29460",
  "Real URL": "https://docs-staging.agora.io/en/extensions-marketplace/develop/implement/usage/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  }, { **Does not exist**
  "url": "`/en/media-pull/reference/restful-api/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace'",
  "Parent URL": "https://docs-staging.agora.io/en/media-pull/reference/restful-api/, line 14, col 29455",
  "Real URL": "https://docs-staging.agora.io/en/media-pull/reference/restful-api/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  }, { **Fixed**
  "url": "`/en/extensions-marketplace/develop/implement/develop/signature-algorithm/'",
  "name":       "`signature algorithm'",
  "Parent URL": "https://docs-staging.agora.io/en/extensions-marketplace/develop/implement/usage/, line 29, col 1928",
  "Real URL": "https://docs-staging.agora.io/en/extensions-marketplace/develop/implement/develop/signature-algorithm/",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/media-pull/reference/restful-api/restful-authentication/'",
  "name":       "`RESTful API authentication'",
  "Parent URL": "https://docs-staging.agora.io/en/media-pull/reference/restful-api/, line 30, col 191",
  "Real URL": "https://docs-staging.agora.io/en/media-pull/reference/restful-api/restful-authentication/",
  "Result": "Error: 404 Not Found"
  }, { **Fixed**
  "url": "`/en/media-pull/reference/restful-api/glossary/#app=id'",
  "name":       "`App ID'",
  "Parent URL": "https://docs-staging.agora.io/en/media-pull/reference/restful-api/, line 37, col 63",
  "Real URL": "https://docs-staging.agora.io/en/media-pull/reference/restful-api/glossary/#app=id",
  "Result": "Error: 404 Not Found"
  }, { **Fixed**
  "url": "`/en/media-pull/reference/restful-api/message-notification-service/'",
  "name":       "`Message Notification Service'",
  "Parent URL": "https://docs-staging.agora.io/en/media-pull/reference/restful-api/, line 466, col 18",
  "Real URL": "https://docs-staging.agora.io/en/media-pull/reference/restful-api/message-notification-service/",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/media-pull/reference/restful-api/manage-your-agora-account/#generate-a-temporary-token'",
  "name":       "`Generate an RTC temporary token'",
  "Parent URL": "https://docs-staging.agora.io/en/media-pull/reference/restful-api/, line 156, col 104",
  "Real URL": "https://docs-staging.agora.io/en/media-pull/reference/restful-api/manage-your-agora-account/#generate-a-temporary-token",
  "Result": "Error: 404 Not Found"
  }, { **Does not exist**
  "url": "`/en/media-push/develop/restful-api/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace'",
  "Parent URL": "https://docs-staging.agora.io/en/media-push/develop/restful-api/, line 14, col 29455",
  "Real URL": "https://docs-staging.agora.io/en/media-push/develop/restful-api/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  }, { **Fixed**
  "url": "`/en/media-push/develop/restful-api/restful-authentication/'",
  "name":       "`RESTful API authentication'",
  "Parent URL": "https://docs-staging.agora.io/en/media-push/develop/restful-api/, line 16, col 191",
  "Real URL": "https://docs-staging.agora.io/en/media-push/develop/restful-api/restful-authentication/",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/media-push/develop/overview/product-overview/#features'",
  "name":       "`Media Push Features'",
  "Parent URL": "https://docs-staging.agora.io/en/media-push/develop/restful-api/, line 61, col 453",
  "Real URL": "https://docs-staging.agora.io/en/media-push/develop/overview/product-overview/#features",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/media-push/develop/reference/restful-type-definition/#audiooptions'",
  "name":       "`audioOptions'",
  "Parent URL": "https://docs-staging.agora.io/en/media-push/develop/restful-api/, line 66, col 3286",
  "Real URL": "https://docs-staging.agora.io/en/media-push/develop/reference/restful-type-definition/#audiooptions",
  "Result": "Error: 404 Not Found"
  },
{ **Fixed**
  "url": "`/en/media-push/develop/restful-api/restful-type-definition/#layout'",
  "name":       "`RtcStreamView'",
  "Parent URL": "https://docs-staging.agora.io/en/media-push/develop/restful-api/, line 66, col 5660",
  "Real URL": "https://docs-staging.agora.io/en/media-push/develop/restful-api/restful-type-definition/#layout",
  "Result": "Error: 404 Not Found"
  },
  { **Fixed**
  "url": "`/en/media-push/develop/restful-api/set-vertical-layout/'",
  "name":       "`Set Vertical Layout'",
  "Parent URL": "https://docs-staging.agora.io/en/media-push/develop/restful-api/, line 66, col 5035",
  "Real URL": "https://docs-staging.agora.io/en/media-push/develop/restful-api/set-vertical-layout/",
  "Result": "Error: 404 Not Found"
  }, { **Does not exist**
  "url": "`/en/video-calling/reference/restful-authentication/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace'",
  "Parent URL": "https://docs-staging.agora.io/en/video-calling/reference/restful-authentication/, line 14, col 29971",
  "Real URL": "https://docs-staging.agora.io/en/video-calling/reference/restful-authentication/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  },
{ **Does not exist**
  "url": "`/en/video-calling/develop/migration-guide/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace'",
  "Parent URL": "https://docs-staging.agora.io/en/video-calling/develop/migration-guide/, line 14, col 29971",
  "Real URL": "https://docs-staging.agora.io/en/video-calling/develop/migration-guide/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  },
{ **Fixed**
  "url": "`/en/video-calling/develop/migration-guide/migration-guide/#migration-steps'",
  "name":       "`Migration steps'",
  "Parent URL": "https://docs-staging.agora.io/en/video-calling/develop/migration-guide/, line 18, col 4",
  "Real URL": "https://docs-staging.agora.io/en/video-calling/develop/migration-guide/migration-guide/#migration-steps",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/video-calling/develop/get-started/get-started-sdk/'",
  "name":       "`Get started'",
  "Parent URL": "https://docs-staging.agora.io/en/video-calling/develop/migration-guide/, line 26, col 8",
  "Real URL": "https://docs-staging.agora.io/en/video-calling/develop/get-started/get-started-sdk/",
  "Result": "Error: 404 Not Found"
  }, { **Does not exist**
  "url": "`/en/video-calling/reference/pricing/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace'",
  "Parent URL": "https://docs-staging.agora.io/en/video-calling/reference/pricing/, line 14, col 29971",
  "Real URL": "https://docs-staging.agora.io/en/video-calling/reference/pricing/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/video-calling/reference/reference/billing-policies/#agoras-free-of-charge-policy-for-the-first-10000-minutes'",
  "name":       "`10,000 free-of-charge minutes'",
  "Parent URL": "https://docs-staging.agora.io/en/video-calling/reference/pricing/, line 18, col 136",
  "Real URL": "https://docs-staging.agora.io/en/video-calling/reference/reference/billing-policies/#agoras-free-of-charge-policy-for-the-first-10000-minutes",
  "Result": "Error: 404 Not Found"
  },
{ **Works**
  "url": "`/en/video-calling/reference/reference/glossary/#channel'",
  "name":       "`channel'",
  "Parent URL": "https://docs-staging.agora.io/en/video-calling/reference/pricing/, line 22, col 112",
  "Real URL": "https://docs-staging.agora.io/en/video-calling/reference/reference/glossary/#channel",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/video-calling/reference/develop/cloud-proxy/'",
  "name":       "`Cloud Proxy'",
  "Parent URL": "https://docs-staging.agora.io/en/video-calling/reference/pricing/, line 38, col 74",
  "Real URL": "https://docs-staging.agora.io/en/video-calling/reference/develop/cloud-proxy/",
  "Result": "Error: 404 Not Found"
  }, { **Does not exist**
  "url": "`/en/3.x/video-calling/introduction/product-overview/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace'",
  "Parent URL": "https://docs-staging.agora.io/en/3.x/video-calling/introduction/product-overview/, line 14, col 30210",
  "Real URL": "https://docs-staging.agora.io/en/3.x/video-calling/introduction/product-overview/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  }, { **Does  not exist**
  "url": "`mailto:support.agora.io'",
  "name":       "`contact our sales'",
  "Parent URL": "https://docs-staging.agora.io/en/3.x/video-calling/introduction/pricing/, line 99, col 170",
  "Real URL": "mailto:support.agora.io",
  "" : ""
  },
{ **Does not exist**
  "url": "`/en/video-calling/reference/manage-agora-account/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace'",
  "Parent URL": "https://docs-staging.agora.io/en/video-calling/reference/manage-agora-account/#generate-a-temporary-token, line 14, col 29971",
  "Real URL": "https://docs-staging.agora.io/en/video-calling/reference/manage-agora-account/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/video-calling/agora-analytics/overview/product-overview/'",
  "name":       "`Agora Analytics overview'",
  "Parent URL": "https://docs-staging.agora.io/en/video-calling/reference/manage-agora-account/#generate-a-temporary-token, line 130, col 195",
  "Real URL": "https://docs-staging.agora.io/en/video-calling/agora-analytics/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  }, {  **Works**
  "url": "`/en/video-calling/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace overview'",
  "Parent URL": "https://docs-staging.agora.io/en/video-calling/reference/manage-agora-account/#generate-a-temporary-token, line 134, col 124",
  "Real URL": "https://docs-staging.agora.io/en/video-calling/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  }, { **Does not exist**
  "url": "`/en/video-calling/overview/core-concepts/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace'",
  "Parent URL": "https://docs-staging.agora.io/en/video-calling/overview/core-concepts/, line 14, col 29971",
  "Real URL": "https://docs-staging.agora.io/en/video-calling/overview/core-concepts/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  },
{ **Does not exist**
  "url": "`/en/video-calling/overview/develop/authentication-workflow/'",
  "name":       "`user authentication'",
  "Parent URL": "https://docs-staging.agora.io/en/video-calling/overview/core-concepts/, line 44, col 142",
  "Real URL": "https://docs-staging.agora.io/en/video-calling/overview/develop/authentication-workflow/",
  "Result": "Error: 404 Not Found"
  }, { **Does not exist**
  "url": "`/en/video-calling/overview/reference/manage-agora-account/#get-the-app-certificate'",
  "name":       "`Manage app certificates'",
  "Parent URL": "https://docs-staging.agora.io/en/video-calling/overview/core-concepts/, line 46, col 244",
  "Real URL": "https://docs-staging.agora.io/en/video-calling/overview/reference/manage-agora-account/#get-the-app-certificate",
  "Result": "Error: 404 Not Found"
  }, { **Does not exist**
  "url": "`/en/interactive-live-streaming/overview/develop/authentication-workflow/'",
  "name":       "`user authentication'",
  "Parent URL": "https://docs-staging.agora.io/en/interactive-live-streaming/overview/core-concepts/, line 44, col 142",
  "Real URL": "https://docs-staging.agora.io/en/interactive-live-streaming/overview/develop/authentication-workflow/",
  "Result": "Error: 404 Not Found"
  }, { **Does not exist**
  "url": "`/en/interactive-live-streaming/overview/core-concepts/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace'",
  "Parent URL": "https://docs-staging.agora.io/en/interactive-live-streaming/overview/core-concepts/, line 14, col 30635",
  "Real URL": "https://docs-staging.agora.io/en/interactive-live-streaming/overview/core-concepts/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  }, { **Works**
  "url": "`/en/interactive-live-streaming/overview/reference/manage-agora-account/#get-the-app-certificate'",
  "name":       "`Manage app certificates'",
  "Parent URL": "https://docs-staging.agora.io/en/interactive-live-streaming/overview/core-concepts/, line 46, col 244",
  "Real URL": "https://docs-staging.agora.io/en/interactive-live-streaming/overview/reference/manage-agora-account/#get-the-app-certificate",
  "Result": "Error: 404 Not Found"
  }, { 
  "url": "`/en/interactive-live-streaming/get-started/reference/manage-agora-account/#create-an-agora-account'",
  "name":       "`account'",
  "Parent URL": "https://docs-staging.agora.io/en/interactive-live-streaming/get-started/get-started-sdk/, line 48, col 29",
  "Real URL": "https://docs-staging.agora.io/en/interactive-live-streaming/get-started/reference/manage-agora-account/#create-an-agora-account",
  "Result": "Error: 404 Not Found"
  }, { **Does not exist**
  "url": "`/en/interactive-live-streaming/get-started/get-started-sdk/extensions-marketplace/overview/product-overview/'",
  "name":       "`Extensions Marketplace'",
  "Parent URL": "https://docs-staging.agora.io/en/interactive-live-streaming/get-started/get-started-sdk/, line 14, col 30635",
  "Real URL": "https://docs-staging.agora.io/en/interactive-live-streaming/get-started/get-started-sdk/extensions-marketplace/overview/product-overview/",
  "Result": "Error: 404 Not Found"
  }, { **Does not exist**
  "url": "`/en/interactive-live-streaming/get-started/reference/downloads/'",
  "name":       "`Downloads'",
  "Parent URL": "https://docs-staging.agora.io/en/interactive-live-streaming/get-started/get-started-sdk/, line 214, col 4",
  "Real URL": "https://docs-staging.agora.io/en/interactive-live-streaming/get-started/reference/downloads/",
  "Result": "Error: 404 Not Found"
  },

**Comment by saudsami** [comment]
Checked all the links and added comments in **bold** above.
**Works** => The link mentioned is not the same as the actual link in the docs. The actual link works.
**Does not exist** => Most of these are named "Extensions Marketplace" but they do not exist in the document.
**Fixed** => Something was changed and it works now.
