### ISSUE TITLE
Modify Cloud Gateway to Server Gateway.

### ISSUE THREAD

**Issue by HeatherWYL** [AgoraIO/Docs-Source#510]
Hi @billy-the-fish , the following contents need to be modified to Server Gateway:
1. On the API reference page: https://docs.agora.io/en/api-reference/
<img width="960" alt="wecom-temp-48af4d2ef1e9d257112ed3e4a15b9dc5" src="https://user-images.githubusercontent.com/52630616/193212780-4001d206-25ea-44d9-bf47-cef91a33ab36.png">

2. On the Download SDK page: https://docs.agora.io/en/sdks/?platform=linux
<img width="675" alt="wecom-temp-b37aa2e4ce0d2a3487b6594713f3a0c2" src="https://user-images.githubusercontent.com/52630616/193212798-c33f8ed8-d1d2-462d-8eca-0962f876643d.png">

3. The name and link need to be modified.
https://docs.agora.io/en/server-gateway/develop/send-receive-media-streams/#api-reference
<img width="608" alt="wecom-temp-28716197834137299dfeebe6d0745f75" src="https://user-images.githubusercontent.com/52630616/193212827-9f707365-70ba-4294-b83b-825d748159a0.png">

**Comment by billy-the-fish** [comment]
Fixed with https://github.com/AgoraIO/Docs-Source/issues/554.

**Comment by billy-the-fish** [comment]
Done.

**Comment by HeatherWYL** [comment]
Hi @billy-the-fish, the item 3 has not been fixed. The link (https://api-ref.agora.io/en/on-premise-recording-sdk/linux-cpp/3.x/index.html) is wrong. The correct one is "https://api-ref.agora.io/en/cloud-gateway-sdk/linux-cpp/3.x/index.html".

**Comment by HeatherWYL** [comment]
Hi @billy-the-fish, the item 3 has not been fixed. The link (https://api-ref.agora.io/en/on-premise-recording-sdk/linux-cpp/3.x/index.html) is wrong. The correct one is "https://api-ref.agora.io/en/cloud-gateway-sdk/linux-cpp/3.x/index.html".
