### ISSUE TITLE
Add SD-RTN TM

### ISSUE THREAD

**Issue by embkim** [AgoraIO/Docs-Source#517]
Hi - please update SD-RTN references to include TM everywhere. Thank you! -emily

![Screen Shot 2022-09-30 at 8 39 31 AM](https://user-images.githubusercontent.com/103133793/193307028-748a2ad3-d25f-4e78-9dbd-a56a8822d7d0.png)
![Screen Shot 2022-09-30 at 8 40 11 AM](https://user-images.githubusercontent.com/103133793/193307030-a7b46b6a-a80e-475a-8b69-abffa75bf318.png)

**Comment by billy-the-fish** [comment]
Done
