### ISSUE TITLE
Media Player or Media Playing?

### ISSUE THREAD

**Issue by embkim** [AgoraIO/Docs-Source#521]
From @frank005:
Shouldn't this be called media player (not media playing) ? https://docs.agora.io/en/video-calling/develop/play-media/

**Comment by billy-the-fish** [comment]
In our step to move away from naming docs after features we moved to Media Playing. Now I think about it a bit more, Media Player, like Spatial audio, is an industry standard term. I agree with this update. 

@saudsami, can you have a look at this please. It should just be updating the variable.

**Comment by saudsami** [comment]
Fixed
