### ISSUE TITLE
API Reference not listed in Page menu for all platforms

### ISSUE THREAD

**Issue by embkim** [AgoraIO/Docs-Source#522]
From @frank005: 
In this page (https://docs.agora.io/en/video-calling/develop/custom-video-and-audio/) if you switch between platforms, you'll see that API Reference in the right menu is not available for every platform so it disappears.

**Comment by billy-the-fish** [comment]
@Kishan-Dhakan, some of the API refs have ### titles, and some ####. Can you align so they all have the same heading level please.

**Comment by Kishan-Dhakan** [comment]
Sure @billy-the-fish

**Comment by billy-the-fish** [comment]
Incidentally, this is for all docs. Please do a global search and replace.

**Comment by Kishan-Dhakan** [comment]
@billy-the-fish I've pushed this in the branches for #615, https://github.com/AgoraIO/Docs-Help/pull/8, and  https://github.com/AgoraIO/Docs-Source-Legacy/pull/19.
