### ISSUE TITLE
Platforms listed without content

### ISSUE THREAD

**Issue by embkim** [AgoraIO/Docs-Source#523]
From @frank005: 
https://docs.agora.io/en/agora-chat/develop/callkit/ - Unity Flutter and RN are all missing, why have them in the UI ?
My comment: We don't display non-existing platforms for some other products, like On-Premise recording.

**Comment by billy-the-fish** [comment]
Yup, we do. 
The idea is that instead of playing magic buttons, we have all the platforms for the product. If the feature  we say it is not there.
