### ISSUE TITLE
Not using proxy

### ISSUE THREAD

**Issue by embkim** [AgoraIO/Docs-Source#525]
From @frank005:
This is not using proxy
In your browser, navigate to the [Agora web demo](https://webdemo.agora.io/agora-websdk-api-example-4.x/basicVideoCall/index.html) and update App ID, Channel, and Token with the values for your temporary token, then click Join.
https://docs.agora.io/en/video-calling/develop/cloud-proxy/?platform=Android
<img width="997" alt="Screen Shot 2022-09-30 at 2 59 08 PM" src="https://user-images.githubusercontent.com/103133793/193393441-f5e877b4-c04f-4b43-8122-64c2bbaec34d.png">
From emily: I also notice this page seems to be missing a variable. A number of places say "in your" without the following noun.
![Screen Shot 2022-09-30 at 10 02 06 PM](https://user-images.githubusercontent.com/103133793/193393466-291937ca-39e6-4cbb-acc1-85904da52bed.png)
![Screen Shot 2022-09-30 at 10 02 12 PM](https://user-images.githubusercontent.com/103133793/193393467-d849fa04-fe82-436c-a0aa-e3ae0830e31c.png)
![Screen Shot 2022-09-30 at 10 02 17 PM](https://user-images.githubusercontent.com/103133793/193393468-614a06bc-9a70-4890-91c0-4fa3022946bc.png)

**Comment by billy-the-fish** [comment]
This is an interesting one. The variable in the URL is Android (Upper case A), not android (lower case a). By setting the incorrect variable Frank is unsetting the workflow. 
The theory is that if the platform is not set, we revert to Android as default. @Mr-spShuvo, can we update the site so incorrect platform attributes also revert to Android.

**Comment by Mr-spShuvo** [comment]
There is a counter logic for not-allowed platform. For now please make sure, everything is written correctly.

**Comment by billy-the-fish** [comment]
Closing here and moving to https://github.com/AgoraIO/Docs/issues/47.
