### ISSUE TITLE
Remove any links to ?platform=

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#529]
The platform= flat in the URLs is no longer necessary and could go wrong. Please remove all the tags and make sure the URLs they are valid.

**Comment by Kishan-Dhakan** [comment]
Done in https://github.com/AgoraIO/Docs-Source/pull/645, https://github.com/AgoraIO/Docs-Source-Legacy/pull/20, and https://github.com/AgoraIO/Docs-Help/pull/10
