### ISSUE TITLE
Original ticket for reference: Update docs for raw and custom video

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#530]
We have received the following feedback. Tadas, can you work with @saudsami on updating this doc. 

I really appreciate Blaise relaying my feedback and I’m happy to share my experience.

The new documentation portal looks reassuring. Hopefully the content is being actively added and improved as well.

I use Agora’s Flutter SDK, and my issues are relevant for the latest "stable" release (6.0.0). My problems are mainly with the so-called “advanced" features of Custom Video Source and Raw Data Processing. I will focus on the insufficient documentation, poor code examples and missing error messages.

Abstract for Both Features

Both Custom Video Source and Raw Data Processing are documented only nominally and the docs raise more questions than they answer. The docs just reiterate the names of functions and internal parameters without ever attempting to provide broader context or insight. They're also ridden with errors throughout. I can go into details on each of the errors separately, but those are the kinds of errors that could only be made by someone who didn’t really understand what they were documenting at all. The demo apps and code snippets are impractical, unrealistic, and don’t really help me to understand the tooling either (more on this below).

What I want as an average-level generalist, is to be able to understand just enough about these features in order to implement my specific technical requirements and move on already to building my business, instead of having to acquire deep expertise in things that I will never need again. The “advanced features” don’t allow for that, and the general attitude to them seems to be that nobody beneath the pay grade of Agora’s own video engineers should even touch these two features.

Docs for Custom Video Source

Custom Video Source is necessary to do something as trivial as allowing my end-users to switch between a wide-angle lens and a zoom lens while live streaming from their smartphones. This is especially relevant for my use-case (remote shopping), but it will also be relevant for live-streamed events and virtual experiences in general.

NB: Most smartphones since 2018 have multiple back-facing cameras, but Agora SDK still doesn’t give me access to them. This arbitrary and outdated restriction to a single back camera forces me to implement a custom-made video-capturing module from scratch just to utilize all the cameras on a given device. Custom Video Source is the feature that I have to use to push video frames to the Agora Engine.

There is nothing in the docs or code examples to tell me how to configure Agora’s ingestion mechanism depending on my technical requirements: what the different image format options are, how to choose the right format, how to prepare the data for being ingested into SDK, what are the best practices for not overusing CPU or RAM, and what other questions I should be asking to put together an optimal integration for me. Instead of all this, the docs [just show how to load a tiny PNG image file from the device storage and push it to the SDK](https://apc01.safelinks.protection.outlook.com/?url=http%3A%2F%2Femail.awatar.net%2Fc%2FeJxVjjtuxiAQhE9jOizAmEdBkSYXyAkWWPyjYLDw4_whiVJEGo12pG-0g44rJbVWZuUkupRWINkxK5OPK6fGMkZl0omC9YpKHYRCBR4UnyT7OKB_kpcTXHorPS6AyK2NKEz0RgtuV8vQCFLc67qOc1reJvE-FFs4Z9hahzm3kbEOe3LERgOUkuv2DeGDpR3jCvd5tZ3-AlAjhTv-9Cax5P0ouGO9KNB_3NnuHpB09-S-5ZphLvkeo__efgHtJ08v&data=05%7C01%7CIain%40agora.io%7C83ee803cb58d4b30d15508daa5552714%7C602753743eaa49c283c3cc189d126981%7C0%7C0%7C638004082395096117%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IgRDs250t%2FsuRAKZRqjANKnqrt2oSIwNqKNsG0PNzUQ%3D&reserved=0) as a faux-video frame, which is just bizarre.

So far, my attempts to set up Custom Video Source resulted either in non-informative errors, or a memory overflow (CUS-27136), but I don’t even know whether it’s me doing something wrong, or there’s a bug in the SDK itself, of which there’ve been plenty lately. Also, the SDK NG now has two separate ways to integrate Custom Video Source, and I in my support tickets I already had two people give me two mutually-exclusive answers as to which should be used.

Docs for Raw Video Data Processing

A Raw Data interceptor is necessary to implement any kind of real-time video filter on the capturing device (e.g. a smartphone). My use-case is actually more simple than that, yet I still had to get in touch with support to find out how to make it work, and after 3 days of back and forth, I’m yet to be provided with any helpful info.

This Raw Data feature allows you to set up an image processing step somewhere in the pipeline between the camera and the video encoder. You can write custom code to manipulate images and send them back to the SDK to be compressed and transmitted.

For this function to work, it needs to read the current image that comes through the pipeline, manipulate the image, and push it back to the pipeline. If I was writing the docs, I would show exactly that: how to read the data, and how to write it back, and what type of data we’re dealing with here, so that a developer only had to figure out how to process that specific type of data according to his specific technical requirements. Instead, the docs show [how to print certain properties (like width and height) of the captured frame into the application log](https://apc01.safelinks.protection.outlook.com/?url=http%3A%2F%2Femail.awatar.net%2Fc%2FeJw1j0GOwyAMRU8Tdo4SCiRZsOhmLjAncIJJ0RBAQNPrl6YaybJs6b8nm_SolJgmNcuRGW2tROb0sAi7GjnCvAwDCDtZwGVVIKaNK1K4oho7MfwmzH_sodeFZm4bsRCNYpaWhDKqKfg8KMmRef2oNZXudu_4TysTt9LjHjP2LradQmunMxRhQ-9d2D8hOsnH1KZSM-EBGV-AT-MiYDBwxS_dzR3J00GhQspxo1KaAKK9gK_1A3xRgxVZ1qfLuwsOe--e7ZP_W940DVdh&data=05%7C01%7CIain%40agora.io%7C83ee803cb58d4b30d15508daa5552714%7C602753743eaa49c283c3cc189d126981%7C0%7C0%7C638004082395096117%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y6aFi3zjHMYL2hPgVfVO0tB12mpUQRjVO7UUQyng9G0%3D&reserved=0), which is even more bizarre than the PNG example.

So far, my attempt to integrate this feature only led me to discover that someone completely forgot to properly set up the above mentioned pipeline inside the SDK (CUS-27144). I am yet to hear from support on how to write back the data once it’s manipulated (CUS-27117).

Error Messages (for both features)

When it comes to “advanced features”, error messages aren’t informative. They aren’t specific, contain no actionable details. If they did, maybe I could figure out at least some things by trying different inputs and seeing what messages the SDK outputs as it runs into errors. 

Without error messages, code debugging cannot realistically be done without involving an Agora engineer who has access to the closed-source codebase in C++, who understands it, and who’s capable to find out what really happens when I push a video frame to the SDK, and the error message is literally “-2” (see CUS-27136).

Perhaps, the sparse documentation I pointed out before could be sufficient for a team that includes a specialist in video encoding, an iOS and Android SDK specialist, and a C/C++ programmer. But even with that team at hand you’d need coherent error messages to conveniently and confidently make use of these features.

I’m an average mid-level coder who has none of the deep expertise outlined above, but if Agora had good docs and error messages, I’d be able to understand just enough about these features in order to implement my specific technical requirements and move on to building my actual business, rather than becoming an expert in things that I will never need again.

Happy to go into details on any of this if necessary.

Thanks!

**Comment by vakrolme** [comment]
Any progress on either raw video data or custom video source, @billy-the-fish @saudsami? 

With Raw Data, it seems like the crux of the problem comes down to a single line of code that would overwrite a frame's buffer with another buffer.

Here's the corresponding bit from Android SDK documentation:
```java
 videoFrame.replaceBuffer(buffer, 270, videoFrame.getTimestampNs());
 ```

This line needs to be "translated" from Android SDK into a Flutter-SDK-compatible snippet, as there is no direct equivalent to the `replaceBuffer()` method in Flutter SDK itself.

**Comment by vakrolme** [comment]
I'm being told by Jay Albo in the CUS-23422 thread that implementing a custom capturer for a Flutter SDK-based app would require one to write the capturer on the platform side (i.e. not in Dart, but rather in Swift and Java). I don' t know how accurate that is, but this might affect your plan to use custom capturer scenario as a basis for code snippets in the Custom Video Source documentation for Flutter @billy-the-fish.
