### ISSUE TITLE
Links for Migration guides from 3.x to 4.x are missing throughout the docs

### ISSUE THREAD

**Issue by tadaspetra** [AgoraIO/Docs-Source#532]
For example this is linked from the Android Release notes https://docs.agora.io/en/develop/migration-guide
![Screen Shot 2022-10-03 at 1 11 20 PM](https://user-images.githubusercontent.com/60107328/193648440-c5051aca-e14b-416d-aa68-b66d15a84b45.png)

**Comment by benghui-agora** [comment]
This same problem exists in the API reference at https://api-ref.agora.io/en/voice-sdk/web/4.x/index.html
