### ISSUE TITLE
Screenshots show China Standard Time

### ISSUE THREAD

**Issue by frank005** [AgoraIO/Docs-Source#534]
Please update the screenshots to not show China Standard Time. This is a US/RoW doc, it should anything else but CST
https://docs.agora.io/en/agora-analytics/analyze/video-voice-sdk/data-insight

**Comment by atovpeko** [comment]
Updated to UTC: https://docs.agora.io/en/agora-analytics/analyze/video-voice-sdk/data-insight#getting-started
