### ISSUE TITLE
Recording links broken

### ISSUE THREAD

**Issue by frank005** [AgoraIO/Docs-Source#536]
<img width="231" alt="Screen Shot 2022-10-03 at 12 14 51 PM" src="https://user-images.githubusercontent.com/56936412/193659766-891b41ce-be42-48b8-8e69-49efd42011bd.png">

**Comment by saudsami** [comment]
Checked both locally and on the https://docs.agora.io/en/cloud-recording/get-started/getstarted
The links work.
