### ISSUE TITLE
POSTman collection link is wrong

### ISSUE THREAD

**Issue by frank005** [AgoraIO/Docs-Source#537]
Sample project
Agora provides a [Postman collection](https://github.com/AgoraIO/Agora-RESTful-Service/blob/master/cloud-recording/README.md), which contains sample requests of RESTful API for a cloud recording. You can use the collection to quickly grasp the basic functionalities of the Cloud Recording RESTful APIs. You only need to import the collection to Postman and set your environment variables.
https://docs.agora.io/en/cloud-recording/get-started/getstarted?platform=All%20Platforms

Please update the POSTman collection link to this:
https://docs.agora.io/en/cloud-recording/get-started/getstarted?platform=All%20Platforms

**Comment by frank005** [comment]
@billy-the-fish - This is NOT updated

**Comment by frank005** [comment]
https://documenter.getpostman.com/view/6319646/SVSLr9AM

**Comment by billy-the-fish** [comment]
Hi Frank, 
   I really love this postman collection. Is this officially supported? I'd really like move all our REST APIs to one place. I was originally thinking of using Swagger, but your postman collection seems even better.  In the mean time, if you could update this linke please @nirm2009 
     Cheers
     
      Iain

**Comment by frank005** [comment]
@billy-the-fish - Yes, you can treat it as officially supported. The github that is referenced is more then 3 years old and has wrong information, the postman we created is up to date and works properly.

**Comment by billy-the-fish** [comment]
Done: https://docs.agora.io/en/cloud-recording/get-started/getstarted. Have started the discussion about this collection as the official API ref.
