### ISSUE TITLE
Name of whiteboard reference page is weird

### ISSUE THREAD

**Issue by frank005** [AgoraIO/Docs-Source#544]
Is the name of this page correct, it looks weird
File conversion overview:deprecated

https://docs.agora.io/en/interactive-whiteboard/reference/file-conversion-overview-deprecated

This page too: https://docs.agora.io/en/interactive-whiteboard/reference/whiteboard-api/file-conversion-deprecated

**Comment by atovpeko** [comment]
@billy-the-fish what are we changin this to then?

**Comment by frank005** [comment]
This should be closed now since its fixed @atovpeko @billy-the-fish
