### ISSUE TITLE
Extension marketplace sample doesn't make any sense

### ISSUE THREAD

**Issue by frank005** [AgoraIO/Docs-Source#546]
Here: https://docs.agora.io/en/extensions-marketplace/overview/product-overview
Click sample: https://github.com/AgoraIO/API-Examples/tree/dev/4.0.0-GA/Android/APIExample/agora-simple-filter

**Comment by billy-the-fish** [comment]
I had this feedback:

I think the sample here is a general example: https://github.com/AgoraIO/API-Examples/tree/dev/4.0.0-GA/Android/APIExample/agora-simple-filter This might be the only general demo we have right now.
There are individual demo code for each extensions. They can be found in the console. For example: https://github.com/symblai/symbl-agora-Android-app

So I think we are doing the best we can. I will contact Christ Bo and ask him if we have a better sample.

**Comment by billy-the-fish** [comment]
@cristianbo, can you tell me which sample we should use please.

**Comment by atovpeko** [comment]
@billy-the-fish @cristianbo any updates here?
