### ISSUE TITLE
Bose PinPoint is listed twice

### ISSUE THREAD

**Issue by frank005** [AgoraIO/Docs-Source#547]
<img width="292" alt="Screen Shot 2022-10-03 at 1 35 32 PM" src="https://user-images.githubusercontent.com/56936412/193677474-e17facec-b8ab-4748-bedf-803b6fe621ee.png">

https://docs.agora.io/en/extensions-marketplace/develop/integrate/pinpoint
https://docs.agora.io/en/extensions-marketplace/develop/integrate/bose-pinpoint

**Comment by billy-the-fish** [comment]
https://docs.agora.io/en/extensions-marketplace/develop/integrate/bose-pinpoint. Done.
