### ISSUE TITLE
RTM is listed as 1.5.1 twice in the SDK downloads

### ISSUE THREAD

**Issue by frank005** [AgoraIO/Docs-Source#548]
<img width="649" alt="Screen Shot 2022-10-03 at 1 44 02 PM" src="https://user-images.githubusercontent.com/56936412/193678837-c2fe26e5-65bf-4c73-ae9c-f9e82e850514.png">

https://docs.agora.io/en/sdks?platform=linux

**Comment by billy-the-fish** [comment]
https://docs.agora.io/en/sdks?platform=linux, done.
