### ISSUE TITLE
Direct download for interactive whiteboard just loads github

### ISSUE THREAD

**Issue by frank005** [AgoraIO/Docs-Source#550]
https://docs.agora.io/en/sdks?platform=macos
https://docs.agora.io/en/sdks?platform=web
https://docs.agora.io/en/sdks?platform=ios
https://docs.agora.io/en/sdks?platform=android

**Comment by billy-the-fish** [comment]
updated to be package manager only: https://docs.agora.io/en/sdks?platform=android
