### ISSUE TITLE
Downloads for Cloud gateway / server gateway do not work

### ISSUE THREAD

**Issue by frank005** [AgoraIO/Docs-Source#555]
<img width="669" alt="Screen Shot 2022-10-03 at 2 20 31 PM" src="https://user-images.githubusercontent.com/56936412/193684811-02cb65f4-7a66-4799-96ce-479275a3f182.png">

https://docs.agora.io/en/server_gateway/server_gateway_run_demo?platform=Linux
https://docs.agora.io/en/server_gateway/integrate_java_sdk?platform=Linux

**Comment by billy-the-fish** [comment]
@Kishan-Dhakan, as you are the download King, can you have a look at this one as well please.
