### ISSUE TITLE
Cloud gateway / server gateway versions do not match on downloads vs. API reference

### ISSUE THREAD

**Issue by frank005** [AgoraIO/Docs-Source#556]
Downloads reference 3.6 : https://docs.agora.io/en/sdks?platform=linux

API reference refers to 3.7.0 and 3.8.0
<img width="933" alt="Screen Shot 2022-10-03 at 2 22 22 PM" src="https://user-images.githubusercontent.com/56936412/193685135-98352262-77cf-47b2-a1cf-22ffa4bd5cbf.png">

**Comment by atovpeko** [comment]
This has been fixed
