### ISSUE TITLE
Error codes are missing for 3.x

### ISSUE THREAD

**Issue by frank005** [AgoraIO/Docs-Source#558]
Error codes: https://docs.agora.io/en/live-streaming-premium-legacy/error_rtc?platform=All%20Platforms

Nothing is on the new site and the API reference is broken: https://api-ref.agora.io/en/voice-sdk/ios/3.x/docs/headers/Agora-Objective-C-API-Overview.html

During API calls, the SDK may returns error codes and warning codes. See Error Codes and Warning Codes.

**Comment by lemon-chen** [comment]
Here: https://docs.agora.io/en/3.x/voice-calling/reference/error-codes
