### ISSUE TITLE
Live streaming standard is missing

### ISSUE THREAD

**Issue by frank005** [AgoraIO/Docs-Source#559]
How to use live streaming standard is missing from the docs. It gives some info in the overview but thats it.
It is also missing from the pricing page (it was on vercel 12 days ago)

**Comment by billy-the-fish** [comment]
Hi @frank005, totally right, this is not clear enough. 

What I propose is:
* A paragraph explaining how to set audienceLatencyLevel in both the quickstart and call quality docs. 
* Update the https://docs.agora.io/en/interactive-live-streaming/reference/pricing#unit-pricing section to emphasize the difference between ILS and ILS Premium. 
* Use the text in the Interactive Live Streaming premium section in https://www.agora.io/en/products/interactive-live-streaming/ to explain. 


Please approve or make a counter-suggestion and we will get this published ASAP.

**Comment by frank005** [comment]
makes sense to me! @billy-the-fish

**Comment by billy-the-fish** [comment]
@saudsami, can you quickly implement these changes please.
