### ISSUE TITLE
URGENT: SDK Quick Start for Unity Video Calling SDK Link Hardlinked to 4.0.0 Beta, and download doesn't work from SDKs section

### ISSUE THREAD

**Issue by alekben** [AgoraIO/Docs-Source#560]
Under SDK Quickstart -> Unity -> Project setup -> Integrate Video SDK -> Unzip [Video SDK], the Video SDK link is hardlinked to:
https://download.agora.io/sdk/release/Agora_Unity_RTC_SDK_4.0.0-beta.1_FULL.zip

From SDKs -> Unity -> Direct Download, however, the 4.0.0 SDK link is:

https://download.agora.io/sdk/release/Agora_Unity_RTC_SDK_4.0.0_FULL.zip

**Comment by alekben** [comment]
Actually, https://download.agora.io/sdk/release/Agora_Unity_RTC_SDK_4.0.0_FULL.zip doesn't even work.
So from SDKs -> Unity -> Direct Downloads, the developer can't download the Unity SDK.

**Comment by alekben** [comment]
Forgot the v, this works:
https://download.agora.io/sdk/release/Agora_Unity_RTC_SDK_v4.0.0_FULL.zip

This in SDKs -> Unity -> Direct Downloads, does not:
https://download.agora.io/sdk/release/Agora_Unity_RTC_SDK_4.0.0_FULL.zip

**Comment by billy-the-fish** [comment]
All good: https://docs.agora.io/en/sdks?platform=unity.
