### ISSUE TITLE
Fix the 3.x and help links

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#565]
Tracking bug:

3,x: https://github.com/AgoraIO/Docs-Source-Legacy/issues/16
Help: https://github.com/AgoraIO/Docs-Help/issues/6

**Comment by Kishan-Dhakan** [comment]
Will be resolved by:
https://github.com/AgoraIO/Docs-Help/pull/8
https://github.com/AgoraIO/Docs-Source/pull/615
