### ISSUE TITLE
Please leave your redirect requests here:

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#569]
Hi all, 
   This page is to aggregate all the redirect requests. Please add your request as a comment in the following format:

Link: 
Page link found in:

**Comment by fishkarl** [comment]
Link: 
https://docs.agora.io/en/video-legacy/cdn_streaming_apple
https://docs.agora.io/en/live-streaming-premium-legacy/inject_stream_restful_overview?platform=All%20Platforms
https://docs.agora.io/en/live-streaming-premium-legacy/cloudproxy_native?platform=Android
https://docs.agora.io/en/Voice/cloud_proxy_web_ng?platform=We

Page link found in : not exist

**Comment by billy-the-fish** [comment]
This comment from Kevin Wu and associated file: 

The number of redirects is also limited to 1000. If there are still some dead links, it cannot be completely solved by redirection. Because my Japanese customers here have sorted out the link of agora documents similar to FAQ, there are about 700 links in it, and there are still many links in it that are dead links

[DocLink_japanese_customers.xlsx](https://github.com/AgoraIO/Docs-Source/files/9714132/DocLink_japanese_customers.xlsx)

**Comment by billy-the-fish** [comment]
@赵文君(Kate) 这个是符合预期的，新英文站的链接规则和中文站不一样，新英文站上对应的是这个：https://api-ref.agora.io/en/voice-sdk/ios/4.x/API/class_irtcengine.html#api_irtcengine_enableencryption

**Comment by fishkarl** [comment]
Link:
https://docs.agora.io/en/live-streaming-premium-legacy/API%20Reference/react_native/classes/rtcengine.html#createwithcontext
@billy-the-fish I cannot find it on English website.

**Comment by billy-the-fish** [comment]
Added from https://github.com/AgoraIO/Docs-Source/issues/580.
https://docs.agora.io/en/Agora%20Platform/ncs#signature
https://docs.agora.io/en/Agora%20Platform/ncs
