### ISSUE TITLE
Soft launch content review - Android & iOS

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#57]

**Comment by Cilla-luodan** [comment]
Migration guide
1. It's important to clarify that the diff is based on v3.7.0 and v4.0.0. "v3.xs" means all 3.x versions, that's not accurate.
2. This current guide is for BETA version, lots of changes are no longer exist in GA version. Refer to latest CN doc:https://confluence.agoralab.co/pages/viewpage.action?pageId=1027868012
3. format issue：
<img width="737" alt="image" src="https://user-images.githubusercontent.com/85477033/182280021-cb7f1c0d-3779-46a7-a3f8-d0ca5fc306cd.png">

**Comment by lemon-chen** [comment]
Under Voice Calling, the following articles use Video SDK when it should be Voice SDK:

**Comment by lemon-chen** [comment]
Under Voice Calling, steps 6 in Test your implementation describes starting an interactive live streaming event. It should be starting a voice call.

**Comment by lemon-chen** [comment]
Under Voice Calling, Integrate an Extension into your app (Android & iOS) > Understand the tech, it says "Web extension"

**Comment by kelzr** [comment]
Under Product overview for Video Calling, a dismatch description:
<img width="449" alt="企业微信截图_2a116b6d-4347-43b6-bd28-5c01b56e13db" src="https://user-images.githubusercontent.com/50696835/182284687-8eaea1f3-9080-48dd-8ed3-c08bf81d357a.png">

**Comment by kelzr** [comment]
Strange period before each bullet:
<img width="927" alt="企业微信截图_68e3ffc2-e6a0-402d-9621-aacb576016e6" src="https://user-images.githubusercontent.com/50696835/182284791-8b6c3ce9-61f8-4eec-803a-699920f6b242.png">

**Comment by kelzr** [comment]
I guess we don't develop this feature currently, could you please explain more?
<img width="377" alt="企业微信截图_6ca0d355-fae5-4507-bb61-f8ef4cdbf30a" src="https://user-images.githubusercontent.com/50696835/182284912-2d6563dd-dfbe-4636-aa08-0a4145a61cd2.png">

**Comment by Cilla-luodan** [comment]
Implement product workflow
1. I can't tell the purpose of this guide from the title, it's better to summarize the task of this guide in the title.
2. It seems that the difference between this guide and the quick start is volument control and screensharing, why not deviding this guide into two guides?

**Comment by kelzr** [comment]
"AI-powered video enhancement" is recommend to add into this page: https://agoradocs-internal.netlify.app/video-calling/overview/product-overview

**Comment by lemon-chen** [comment]
![企业微信截图_e7531374-4322-4333-8cc5-478631f92842](https://user-images.githubusercontent.com/33219255/182286026-4554c881-7e5f-4319-9789-49905135ed35.png)

**Comment by Cilla-luodan** [comment]
Implement raw video and audio processing
Is it normal for sub-headings to be larger than super-headings?
<img width="473" alt="wecom-temp-c0eae6b8fb97751a664970c437e332a7" src="https://user-images.githubusercontent.com/85477033/182286230-2dcca5f6-1917-4308-adb3-b502c9cdaf05.png">

**Comment by lemon-chen** [comment]
![企业微信截图_e7531374-4322-4333-8cc5-478631f92842](https://user-images.githubusercontent.com/33219255/182286026-4554c881-7e5f-4319-9789-49905135ed35.png)

**Comment by lemon-chen** [comment]
Manage your Agora account > Submit a Ticket, this page needs to update: https://docs.agora.io/en/Agora%20Platform/ticket?platform=All%20Platforms

**Comment by Cilla-luodan** [comment]
Release notes
1.  The content needs to be updated to v4.0.0 (not beta), the Chinese release note is ready, do you need us to translate it into English or you can handle it? url: https://confluence.agoralab.co/pages/viewpage.action?pageId=1016431888
<img width="523" alt="image" src="https://user-images.githubusercontent.com/85477033/182287385-ccf70d23-227b-4646-b984-bf16d0adcf89.png">

**Comment by kelzr** [comment]
<img width="1205" alt="企业微信截图_21bb8910-f48e-4464-bc42-f15dd179beb4" src="https://user-images.githubusercontent.com/50696835/182288130-54219cfd-2669-443d-9a53-31b4331d64ac.png">

wrong format

**Comment by kelzr** [comment]
Maybe we can make this font size larger? It's too smaller now, I think.

<img width="1209" alt="企业微信截图_f895bc37-a42c-4844-98c7-ed4a7b1eda0c" src="https://user-images.githubusercontent.com/50696835/182288414-b2ca7305-93fc-4ea4-b29b-88386741f9ee.png">

**Comment by pmmgithub** [comment]
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/45590614/182288482-dc49b99c-09a5-43d3-8243-cd6d412f0cae.png">

**Comment by lemon-chen** [comment]
This article: https://agoradocs-internal.netlify.app/video-calling/reference/firewall is outdated. Did we change RTM to Signaling on purpose？

**Comment by lemon-chen** [comment]
This article: https://agoradocs-internal.netlify.app/video-calling/reference/firewall is outdated. Did we change RTM to Signaling on purpose？

**Comment by lemon-chen** [comment]
The two titles under Interactive Live Streaming

![企业微信截图_233b91a2-2741-4bea-9e12-d77801edbb11](https://user-images.githubusercontent.com/33219255/182289170-b53cae73-b77a-410c-a0aa-85022125d295.png)

**Comment by kelzr** [comment]
<img width="1266" alt="企业微信截图_acdab948-7979-458c-8397-68e1a2f73c17" src="https://user-images.githubusercontent.com/50696835/182305690-75260cd5-38a3-434a-b2d0-ddfeccbc1e64.png">

<img width="618" alt="企业微信截图_e296a9ea-6ac3-44ce-bf7f-e75cfad30b1f" src="https://user-images.githubusercontent.com/50696835/182305771-c11bf73f-7084-4dfe-9d64-e9abd1162ba5.png">

**Comment by kelzr** [comment]
<img width="858" alt="企业微信截图_5ce4218d-dbb8-46f7-b0cc-6a9c1651651e" src="https://user-images.githubusercontent.com/50696835/182306620-33e11f3e-005f-4baf-8115-e2a9cdc39184.png">

typo

**Comment by pmmgithub** [comment]
<img width="834" alt="image" src="https://user-images.githubusercontent.com/45590614/182314889-8eeb336b-f637-4bde-9097-72cd43268c6e.png">
This link doesn't direct me to the right place, still the same section on the same page. Might need to update the URL.
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/45590614/182315188-fbae2603-9948-47e0-af62-80796940ad4d.png">
Need to change this title to title case, or change the others to sentence case to keep consistency.
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/45590614/182322433-cddcdff9-f95b-4678-8e03-f5a5da06d52b.png">
In the Manage Your Agora Account guide, I clicked the link to Agora Analytics overview (https://agoradocs-internal.netlify.app/agora-analytics/overview/product-overview/). It seems some texts are missing, and the image doesn't display (not sure whether it's because my connection issues)

**Comment by Chuchun1991** [comment]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/78007051/182346205-f8c7257d-5756-45b6-a244-39e0f92a74cc.png">
Sequence number for steps is better.

**Comment by Chuchun1991** [comment]
The content of "Downloads" for iOS is not manually install Video SDK, but use CocoaPods to integrate.

**Comment by Mr-spShuvo** [comment]
> Under Product overview for Video Calling, a dismatch description: <img alt="企业微信截图_2a116b6d-4347-43b6-bd28-5c01b56e13db" width="449" src="https://user-images.githubusercontent.com/50696835/182284687-8eaea1f3-9080-48dd-8ed3-c08bf81d357a.png">
> 
> @Mr-spShuvo, this is for you.

Resolved!

**Comment by Mr-spShuvo** [comment]
> I guess we don't develop this feature currently, could you please explain more? <img alt="企业微信截图_6ca0d355-fae5-4507-bb61-f8ef4cdbf30a" width="377" src="https://user-images.githubusercontent.com/50696835/182284912-2d6563dd-dfbe-4636-aa08-0a4145a61cd2.png">
> 
> @Mr-spShuvo this is for youu

I don't write content. It has been provided to me. Please refer this to Garret

**Comment by Cilla-luodan** [comment]
Error message guide
1. 4.0.0 SDK no longer has onWarning callback and warning codes.
2. This guide is the same as v3.x Error Codes and Warning Codes, however, the error codes of v4.0 are not all alligned with v3.x. Refer to: https://docs-preprod.agora.io/cn/video-call-4.x-beta/API%20Reference/java_ng/v4.0.0/API/class_irtcengineeventhandler.html#ariaid-title25
3.  Technically, this is not a "guide" but a “reference", you might want to change the title?

**Comment by lemon-chen** [comment]
Close this issue and track unresolved comments in other threads
