### ISSUE TITLE
Broken links in Help

### ISSUE THREAD

**Issue by ghuddy** [AgoraIO/Docs-Source#579]
Broken/bad links on three Help pages:

Page: https://docs.agora.io/en/help/integration-issues/token_cohost/#2-change-the-app-logic
Broken link: [Upgrade authentication mechanism](https://docs.agora.io/en/video-calling/develop/authentication-workflow).
- clicking the link adds /help to the URL and throws a 404

Page: https://docs.agora.io/en/help/integration-issues/video_profile/#__docusaurus
Broken link:
[Set the bitrate](https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/java/classio_1_1agora_1_1rtc_1_1video_1_1_video_encoder_configuration.html#a4b090cd0e9f6d98bcf89cb1c4c2066e8)
- clicking the link throws a 404

Page: https://docs.agora.io/en/help/integration-issues/log#set-the-log-file
Broken link (CN link): iOS/macOS
° sharedEngineWithConfig]
(https://docs.agora.io/cn/Interactive%20Broadcast/API%20Reference/oc/Classes/AgoraR
tcEngineKit.html#//api/name/sharedEngineWithConfig:delegate:)
- link directs to CN Docs site

**Comment by billy-the-fish** [comment]
@saudsami , this last link is still broken. Can you quickly fix please.
