### ISSUE TITLE
Soft launch UX review

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#58]
When right clicking an article to browse it on a new tab, the article always takes Web as the platform. And when I click "Android", it shows
![企业微信截图_5f1ed92f-4696-4625-8199-4190eea88b50](https://user-images.githubusercontent.com/33219255/182292140-ab34deee-d265-4591-b82e-8a062e0766a6.png)

**Comment by pmmgithub** [comment]
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/45590614/182288206-7c762fa8-d0d5-441e-947b-56ae13295133.png">
Heading level 1 is nearly the same size as heading level 2. not sure whether this is an expected behavior.

**Comment by lemon-chen** [comment]
When clicking API Reference or SDKs, API Reference and SDKs are not rendered with the blue background
![企业微信截图_a1b0ff92-da76-49bb-ba0f-56924190c47f](https://user-images.githubusercontent.com/33219255/182291688-742dd717-f2a7-4cd5-9c6d-5e137ff3655c.png)

**Comment by pmmgithub** [comment]
On the home page, I choose SDK or UIKit and I'm redirected to the corresponding doc page. Then I cannot go back to the home page using the Go Back feature of web browser.
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/45590614/182330324-3d4da00b-dd83-40e3-9cde-b42fd6f3bbf5.png">

**Comment by pmmgithub** [comment]
<img width="208" alt="image" src="https://user-images.githubusercontent.com/45590614/182331364-ae2eb402-a8f4-4804-a709-946781902a36.png">
I click the "Help" and "Signup" buttons and nothing happens. Will they be available on the launch date?

**Comment by Chuchun1991** [comment]
Content Moderation is not GA overseas and has no official EN docs. Bot it is on DP.
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/78007051/182340577-450456ea-d30e-49e6-8387-7f7441a87b29.png">

**Comment by Chuchun1991** [comment]
The back button doesn't work for all docs except "product overview".
