### ISSUE TITLE
Leave Call Button

### ISSUE THREAD

**Issue by Taimoor20** [AgoraIO/Docs-Source#583]
In UI Kit quickstart, there is no button to leave the call, kindly add that too. Or if it exists, do let me know how can I get that in my project.

**Comment by frank005** [comment]
@Taimoor20  - Can you send a link to the docs? Which platform? Is this video, audio, live streaming, etc?
This seems like a demo needs to be updated, not specifically the docs?

**Comment by billy-the-fish** [comment]
@maxxfrazer, can you tell me if we need to update the docs or contemplate a change to UIKIt.

**Comment by Taimoor20** [comment]
You have to update the docs and change to UIKit too.

**Comment by maxxfrazer** [comment]
I'm assuming this is for iOS Video UI Kit?
If so, there is not an end call button added there, as it's usually custom per platform or use-case. But [adding a button](https://github.com/AgoraIO-Community/VideoUIKit-iOS/wiki/Full-Agora-UIKit-Guide#adding-more-buttons-with-agoravideoviewerdelegate-) is in the full guide, along with [leaveChannel](https://agoraio-community.github.io/VideoUIKit-iOS/documentation/agorauikit/agoravideoviewer/leavechannel(stoppreview:_:)) in the API Reference. Hopefully those two help with how to add a button to Video UI Kit.

Full guide on our blog here:
https://www.agora.io/en/blog/how-to-create-ios-mac-os-video-streaming-app-3-lines-of-code/

It's in need of some minor updates, but almost everything would stay the same. We might want to bring over some of those to our official docs site in the coming months.
