### ISSUE TITLE
https://docs.agora.io/en/broadcast-streaming/overview/product-overview

### ISSUE THREAD

**Issue by timin1970** [AgoraIO/Docs-Source#584]
Can we pls remove this page and all the Broadcast Streaming sub pages from the live docs site.

https://docs.agora.io/en/broadcast-streaming/overview/product-overview

**Comment by frank005** [comment]
This is FCDN and is in beta so at best, it shouldn't be removed by labeled beta.

**Comment by billy-the-fish** [comment]
@saudsami, can you add the word Beta in the product overview and for the dropdown. Have a look in the PR associiated with https://github.com/AgoraIO/Docs-Source/issues/601 and you can see what I did to de-beta-ize chat. If you do the opposite to beta-ize Broadcast Streaming please.

**Comment by saudsami** [comment]
done
