### ISSUE TITLE
React Native Web Multiple Channel Connect Example App

### ISSUE THREAD

**Issue by mayankjanmejay** [AgoraIO/Docs-Source#588]
https://docs.agora.io/en/interactive-live-streaming/develop/live-streaming-over-multiple-channels/#implement-joining-multiple-channels

Hey it would be nice to have the GitHub repo link to a app. That way I or other devs just need to copy your project to get things up and running.

**Comment by billy-the-fish** [comment]
Hi @mayankjanmejay, 
    Thanks for the feedback. The theory is that you can cut and paste this code into your project and it will run. However, we have been thinking about publishing the get started projects to github so you can work from there.  What do you think?

    Cheers

    Iain

**Comment by billy-the-fish** [comment]
Hello again @mayankjanmejay,
    I thought you would like this issue: https://github.com/AgoraIO/Docs-Source/issues/721. We will add links to sample code for each feature in the docs. 
        Cheers
        
        Iain
