### ISSUE TITLE
[RTE] A feature name change

### ISSUE THREAD

**Issue by kelzr** [AgoraIO/Docs-Source#593]
<img width="916" alt="截屏2022-10-09 17 09 01" src="https://user-images.githubusercontent.com/50696835/194748159-b9d51db3-c4c6-4f1e-845b-28edd8025f9e.png">

**Comment by billy-the-fish** [comment]
@nirm2009 , can you do this at the same time as https://github.com/AgoraIO/Docs-Source/issues/598 please.

**Comment by billy-the-fish** [comment]
Done: https://docs.agora.io/en/video-calling/develop/ai-denoiser and in other mentions in the site.
