### ISSUE TITLE
Add download link for MediaPlayer Kit on the SDK page

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#597]
Name: Agora MediaPlayer Kit

Download link:

- Android v1.3.0: https://download.agora.io/sdk/release/Agora_Media_Player_for_Android_rel.v1.3.0_14564_ffmpeg_player_lite_20210723_1234.zip

- iOS v1.3.0: https://download.agora.io/sdk/release/Agora_Media_Player_for_iOS_rel.v1.3.0_53009_ffmpeg_player_lite_20210702_1606.zip

- macOS v1.3.0: https://download.agora.io/sdk/release/Agora_Media_Player_for_Mac_rel.v1.3.0_31754_ffmpeg_player_lite_20210716_1813.zip

- Windows (x86) v1.3.0: https://download.agora.io/sdk/release/Agora_Media_Player_for_Windows_x86_rel.v1.3.0_63393_ffmpeg_player_lite_20210727_1117.zip

- Windows (x64) v1.3.0: https://download.agora.io/sdk/release/Agora_Media_Player_for_Windows_x64_rel.v1.3.0_63392_ffmpeg_player_lite_20210727_1117.zip

**Comment by billy-the-fish** [comment]
@Kishan-Dhakan, can you transfer this issue to https://github.com/AgoraIO/Docs/issues please. When you have completed we will merge all of your issues in that repo.

**Comment by Kishan-Dhakan** [comment]
Sure @billy-the-fish

**Comment by Kishan-Dhakan** [comment]
Moved to https://github.com/AgoraIO/Docs/issues/45
