### ISSUE TITLE
[Extensions Marketplace] Add BytePlus and update DeepAR

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#598]
Hi @billy-the-fish Per requests from the product side, please assign high priority to the following doc updates:

1. Update https://docs.agora.io/en/extensions-marketplace/develop/integrate/deepar with the latest source file [deepAR-latest.md](https://github.com/AgoraIO/Docs-Source/files/9743636/deepAR-latest.md)

2. Add BytePlus under the `Develop/Integrate extensions` section. The extension supports Android and iOS. Source file:
 - [BytePlus_api.md](https://github.com/AgoraIO/Docs-Source/files/9743698/BytePlus_api.md)
 - [BytePlus_guide.md](https://github.com/AgoraIO/Docs-Source/files/9743701/BytePlus_guide.md)

**Comment by billy-the-fish** [comment]
Hi @nirm2009 , Can you have a look at this ticket today please. 

thanks in advance, 

Iain

**Comment by billy-the-fish** [comment]
https://docs.agora.io/en/extensions-marketplace/develop/integrate/deepar and https://docs.agora.io/en/extensions-marketplace/develop/integrate/byteplus.
