### ISSUE TITLE
Chat GA Action List

### ISSUE THREAD

**Issue by jinyuagora** [AgoraIO/Docs-Source#601]
Please ensure that all the following changes are deployed and displayed on [docs.agora.io/en/ ](https://docs.agora.io/en) at the promised time - **Chat GA - 8am PT on 10/10**.
<img width="777" alt="image" src="https://user-images.githubusercontent.com/101544891/194830683-6e98f10d-4fbb-4457-ac69-4b19d3a5ce21.png">

**Comment by jinyuagora** [comment]
**SDK Downloads**
Currently, the Chat SDKs for React Native and Windows are missing, and the Chat SDKs for other platforms are not the latest versions.
Android v1.0.7: https://download.agora.io/sdk/release/Agora_CHAT_SDK_for_Android_v1_0_7.zip
iOS v1.0.7: https://download.agora.io/sdk/release/Agora_Chat_SDK_for_iOS_v1_0_7.zip
Web v1.0.6: https://www.npmjs.com/package/agora-chat
React Native v1.0.7: https://www.npmjs.com/package/react-native-agora-chat
Flutter v1.0.7: https://pub.dev/packages/agora_chat_sdk
Unity v1.0.5: https://downloadsdk.easemob.com/downloads/SDK/Unity/Agora_Unity_Chat_SDK_1.0.5.unitypackage
Windows v1.0.5: https://downloadsdk.easemob.com/downloads/SDK/WinSDK/agora_chat_sdk.1.0.5.nupkg

**Comment by jinyuagora** [comment]
**Add demo app download links to the new Doc center.**
- Android: https://download.agora.io/demo/release/agorachatdemo_android_1.0.6.apk
- iOS: https://testflight.apple.com/join/MO0UuYJH
- Web: https://webdemo.chat.agora.io/

**Comment by jinyuagora** [comment]
**Remove "Beta" as Chat will go GA soon.**
<img width="422" alt="image" src="https://user-images.githubusercontent.com/101544891/194832050-47753991-a5b6-4bab-b730-28c42d963025.png">

**Comment by pmmgithub** [comment]
Please help change the link text here to 'View UI Samples quickstart'. 
![image](https://user-images.githubusercontent.com/45590614/194841679-ece4dd30-8a36-44d1-8fdd-e26464c42198.png)

**Comment by pmmgithub** [comment]
PR: https://github.com/AgoraIO/Docs-Source/pull/602
Please help review the PR and merge to main. Thx.

**Comment by billy-the-fish** [comment]
Work that is in the doc build I will do in https://github.com/AgoraIO/Docs/tree/38-relative-links-are-not-working, there are already updates to the SDK downloads in this page that need to be merged.

**Comment by billy-the-fish** [comment]
Done.
