### ISSUE TITLE
RTC Web 4.x SDK doesn't have Best Practice document. 

### ISSUE THREAD

**Issue by EmmaAzureAgora** [AgoraIO/Docs-Source#603]
4.x "Deal with Autoplay Blocking" is different than 3.x version. This is an important information.

**Comment by billy-the-fish** [comment]
It is here: https://docs.agora.io/en/video-calling/develop/product-workflow#implement-the--workflow

**Comment by EmmaAzureAgora** [comment]
Got it. Thank you!

**Comment by EmmaAzureAgora** [comment]
Got it. Thank you!
