### ISSUE TITLE
Update migration guides for 4.x frameworks

### ISSUE THREAD

**Issue by Cilla-luodan** [AgoraIO/Docs-Source#611]
@billy-the-fish, please help with this update.
 
[migration_guide_electron_ng.md](https://github.com/AgoraIO/Docs-Source/files/9750761/migration_guide_electron_ng.md)
[migration_guide_flutter_ng_en.md](https://github.com/AgoraIO/Docs-Source/files/9750762/migration_guide_flutter_ng_en.md)
[migration_guide_rn_ng.md](https://github.com/AgoraIO/Docs-Source/files/9750763/migration_guide_rn_ng.md)
[migration_guide_unity_ng.md](https://github.com/AgoraIO/Docs-Source/files/9750764/migration_guide_unity_ng.md)

**Comment by saudsami** [comment]
Found flutter and electron guides ok.
Changed the latest version number in Unity
Added the changes for 4.0.0 Beta to 4.0.0 section to the RN guide.
