### ISSUE TITLE
Update token authentication guide to token 007

### ISSUE THREAD

**Issue by Cilla-luodan** [AgoraIO/Docs-Source#614]
@billy-the-fish, please update the current token generator guide to replace AccessToken with AccessToken2. You may want to add a new guide that tells users how to upgrade from AccessToken to AccessToken2.
AccessToken2 has been released since 18 Aug.

**Comment by billy-the-fish** [comment]
We are already working on this: https://github.com/AgoraIO/Docs-Source/issues/220.
