### ISSUE TITLE
Wrong information on Download SDKs for Web

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#619]
The latest information is as follows:

- version number: 4.14.0
- Direct Download link: https://download.agora.io/sdk/release/Agora_Web_SDK_v4_14_0_FULL.zip
- Package Manager link: https://www.npmjs.com/package/agora-rtc-sdk-ng

**Comment by billy-the-fish** [comment]
@dengyaxi are you sure about this? Looks ok to me on https://docs.agora.io/en/sdks?platform=web.

**Comment by dengyaxi** [comment]
@billy-the-fish Yes the version number was 4.13.0. I guess someone fixed it before you did. Nice.

However the Package Manager link still goes to https://www.npmjs.com/package/agora-rtc-react not https://www.npmjs.com/package/agora-rtc-sdk-ng. Not sure if this is done on purpose.

**Comment by Kishan-Dhakan** [comment]
The repo https://github.com/AgoraIO-Extensions/react-native-agora-rtc-ng has been archived/deleted, and the docs in https://github.com/AgoraIO-Extensions/react-native-agora say to use `npm i --save react-native-agora`, so it might be on purpose but worth checking.

**Comment by billy-the-fish** [comment]
Putting in a release today.

**Comment by billy-the-fish** [comment]
Fixed: https://docs.agora.io/en/sdks?platform=web
