### ISSUE TITLE
Update service sunset plans for 3.x Web

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#624]
Hi @billy-the-fish. As discussed in the email thread, please update https://docs.agora.io/en/3.x/interactive-live-streaming/introduction/service-sunset-plans using this source file [rtc_sunset_web.md](https://github.com/AgoraIO/Docs-Source/files/9760889/rtc_sunset_web.md)

**Comment by billy-the-fish** [comment]
Saud, to understand the email thread context: "Just want to clarify that we only put the 3.x sunset plan under 3.x docs, not 4.x docs, considering that 3.x and 4.x docs are served independently now through a versioning policy. Both Web 4.x and Native 4.x are doing it this way. If you have a different opinion, just let us know."

**Comment by Kishan-Dhakan** [comment]
Closed by https://github.com/AgoraIO/Docs-Source-Legacy/pull/31
