### ISSUE TITLE
Fix version number in web 4.x docs

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#625]
Hi @billy-the-fish **Voice/Video SDK for Web** does not have v3.7.x. The suggestion is to use **v3.x** for Web, and v3.7.x for other platforms that apply.

We first found this issue in https://docs.agora.io/en/interactive-live-streaming/develop/migration-guide. Jennifer Xin also saw it in another doc (she is trying to recall and locate). So please run a global check throughout the 4.x docs for Web SDK. Thanks in advance

**Comment by Kishan-Dhakan** [comment]
Resolved in https://github.com/AgoraIO/Docs-Source/pull/615

**Comment by billy-the-fish** [comment]
Done: https://docs.agora.io/en/interactive-live-streaming/develop/migration-guide

**Comment by dengyaxi** [comment]
Seems like it hasn't changed on the doc center
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/73678648/195752145-424c09a0-a2f4-4885-9dd2-057203e29f2a.png">
