### ISSUE TITLE
Doc update for Flexible Classroom: Classroom RESTful APIs

### ISSUE THREAD

**Issue by pmmgithub** [AgoraIO/Docs-Source#626]
To sync with CN ver doc, we added an API of creating a classroom. Please help update the EN doc with the attach MD file, thanks!
[Flexible Classroom RESTful APIs.md](https://github.com/AgoraIO/Docs-Source/files/9762227/Flexible.Classroom.RESTful.APIs.md)

**Comment by saudsami** [comment]
done
