### ISSUE TITLE
Doc update for Flexible Classroom: Integrate Flexible Classroom

### ISSUE THREAD

**Issue by pmmgithub** [AgoraIO/Docs-Source#627]
Please help make updates as follows, thanks!

-   **Web platform only:**Update the "Integrate Flexible Classroom" section step 2 as follows:

  To change directory to `CloudClass-Desktop` and switch the branch, run the following commands. Remember to replace {VERSION} with a specified version number:
  `cd CloudClass-Desktop`
  `git checkout release/`{VERSION}`
  
  For example, if you want to switch to the branch of v2.6.2, just run the following command:
  
     ```bash
     git checkout release/2.6.2
     ```
  
  Agora recommends switching the branch of the latest release. The following image shows how to see the latest release branch in the GitHub repository:
  
  ![](https://web-cdn.agora.io/docs-files/1658916187924)

- **Web and Electron platforms:**Update the "Integrate Flexible Classroom" section step 4 by adding two sub-steps after step i:

  ii: Move the `.env.example` file in your project's root directory to `packages/agora-classroom-sdk` and rename the file as `.env`. So the file path is `mv .env.example packages/agora-classroom-sdk/.env`.
  
  iii: Fill in your App ID and App Certificate in the following code in `.env`:
    ```
    REACT_APP_AGORA_APP_ID={your appid}
    REACT_APP_AGORA_APP_CERTIFICATE={your app certificate}
    ```

- **Web and Electron platforms:**Update the sample code in the Use the default UI of Flexible Classroom section with following:
      
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="https://download.agora.io/edu-apaas/release/edu_sdk@2.7.1.bundle.js"></script>
</head>

<body>
    <style>
        #root {
            width: 100%;
            height: 100%;
        }
    </style>
    <div id="root"></div>
    <script type="text/javascript">
        //  Configures the SDK.
        // Provide your App ID.
        AgoraEduSDK.config({
                appId: 'Your App ID',
                region: 'NA'
        });
        //  Launches  the flexible classroom.
        AgoraEduSDK.launch(document.querySelector('#root'), {
            userUuid: 'user id',
            userName: 'user name',
            roomUuid: 'room id',
            roleType: 1, //  Role type: 1 for teachers, 2 for students.
            roomType: 0, // Room type: 0 for a one-to-one classroom, 2 for a lecture hall (a common lecture hall or a vocational lecture hall depending on room sub-type), 4 for  a small classroom.
            roomSubType: 0, //  Room sub-type. The default value is 0. To set a vocational lecture hall, set roomType as 2 and roomSubType as 1.
            roomName: 'room name',
            pretest: true, // Whether to enable the pre-class device test.
            rtmToken: 'rtm token', //// In a test environment, you can use a temporary <Vg k="MESS" /> token; in a production or security environment, Agora strongly recommends that you use a server-generated <Vg k="MESS" /> token.
            language: 'zh', // The language on the classroom UI: zh for Chinese and en for English.
            duration: 60 * 30, // The duration of the class (in second).
            recordUrl: 'https://solutions-apaas.agora.io/apaas/record/dev/2.3.3/record_page.html',
            courseWareList: [],
            uiMode: FcrMultiThemeMode.light, // The theme of the classroom UI: FcrMultiThemeMode.light for the light mode, FcrMultiThemeMode.dark for the dark mode.
            listener: (evt, args) => {
            },
        }).then(() => {
            console.log('start launch');
        }).catch((e) => {
            console.error('fail to launch', e);
        });
    </script>
</body>

</html>

**Comment by billy-the-fish** [comment]
@saudsami , please do a full review of this addition when you add it.

**Comment by saudsami** [comment]
done
