### ISSUE TITLE
Change capitalization for "On-Premise Recording"

### ISSUE THREAD

**Issue by ghuddy** [AgoraIO/Docs-Source#628]
@billy-the-fish can we please update all mentions of "On-premise Recording" to "On-Premise Recording" (with the "p" capitalized). 

Thanks!

**Comment by Kishan-Dhakan** [comment]
Done in https://github.com/AgoraIO/Docs/pull/50, https://github.com/AgoraIO/Docs-Source/pull/615, https://github.com/AgoraIO/Docs-Help/pull/8, and https://github.com/AgoraIO/Docs-Source-Legacy/pull/19.
