### ISSUE TITLE
Update Interactive Live Streaming overview intro

### ISSUE THREAD

**Issue by ghuddy** [AgoraIO/Docs-Source#632]
Page: https://docs.agora.io/en/interactive-live-streaming/overview/product-overview

Update to the second sentence in the intro for ILS:
Enabled Agora’s Video SDK, Interactive Live Streaming gives you full control over the streaming experience from a standard one-to-many stream to a highly-interactive live event.

**Comment by billy-the-fish** [comment]
Done: https://docs.agora.io/en/interactive-live-streaming/overview/product-overview.
