### ISSUE TITLE
TOC update suggestions for Flexible Classroom

### ISSUE THREAD

**Issue by pmmgithub** [AgoraIO/Docs-Source#635]
Hi, the flexible classroom team gathered feedback from the SA team on the table of contents of Flexible Classroom:
1. Move the Platform Support and Technical Architecture doc under Overview
2. Add back the Product Overview (CN ver: https://docs.agora.io/cn/agora-class/product_agora_class?platform=Android) and Features Description (CN ver: https://docs.agora.io/cn/agora-class/product_agora_class?platform=Android) doc.
3. Create a category for best practices to include "record a class", "supply course materials", and "secure your classroom"
4. Make Web the first button of the platform rows.

These suggestions are open for discussion and you could contact Sun Liang <sunliang@agora.io> who shared the feedback for follow-up actions. Thanks!

**Comment by pmmgithub** [comment]
Sure. Please contact Sun Liang [sunliang@agora.io](mailto:sunliang@agora.io) who raised this request and has the first-hand customer feedback.

**Comment by billy-the-fish** [comment]
Our goal is to have the same structure for all products, following the architecture shown in the Video SDK based products. I'm happy to have a discussion on the information architecture following that model. Please setup a meeting so we can discuss.
