### ISSUE TITLE
Doc updates for Flexible Classroom: Configure Flexible Classroom

### ISSUE THREAD

**Issue by pmmgithub** [AgoraIO/Docs-Source#636]
Please help make the following updates based on the product team, thanks!

- Remove the first screenshot, as it shows product architecture, rather than product features, which is not suitable in the configuration section.
- Add the Considerations section as consistent with the CN ver (https://docs.agora.io/cn/agora-class/agora_class_configure?platform=Android#注意事项).

**Comment by saudsami** [comment]
I need the English version of the Alibaba Cloud OSS account screenshot to add to the document.

**Comment by pmmgithub** [comment]
Hi Saud @saudsami, after double-checking with the SME, only China customers use Alibaba Cloud OSS. So for en doc, we only need to add the AWS cloud config info. You could just copy the content from the previous en site: https://docs-preprod.agora.io/en/agora-class/agora_class_configure?platform=iOS#considerations .   Thanks!

**Comment by saudsami** [comment]
Done
