### ISSUE TITLE
Cloud Proxy relevant introduction is missing

### ISSUE THREAD

**Issue by The-Machine-Tango** [AgoraIO/Docs-Source#638]
For the new doc, I could only find a doc of Cloud Proxy as "IP Addresses for Cloud Proxy"
https://docs.agora.io/en/interactive-live-streaming/reference/cloud-proxy-allowed-ips

But seems there is no any introduction about What is Cloud Proxy, How to use it, What is the limitation, How much it will be billed(we received flooded complains about billing when the product is released). The IP address sounds likely to be just a part of the whole Cloud Proxy page.

**Comment by billy-the-fish** [comment]
Hi @The-Machine-Tango, 
   Thanks for your feedback .If you look at https://docs.agora.io/en/video-calling/develop/cloud-proxy, you  will see the docs for this feature. The billing is now included in https://docs.agora.io/en/video-calling/reference/pricing#-billing, so users get the big picture for all Video SDK based products. 

    Hope you find this useful, cheers

    Iain
