### ISSUE TITLE
sever gateway SDK download links for c++ and Java are broken

### ISSUE THREAD

**Issue by Monichen-agora** [AgoraIO/Docs-Source#643]
https://docs.agora.io/en/sdks?platform=linux

Not only are the versions not right, but the download links are also broken.

**Comment by billy-the-fish** [comment]
Hi @Monichen-agora ,
    Thanks for the update. I've done a bit of research and from what I understand the download URLs are:

C++ download: https://download.agora.io/sdk/release/Agora-RTC-x86_64-linux-gnu-v3.8.202.20-20220627_152601-214165.tgz
Java package: https://mvnrepository.com/artifact/io.agora.rtc/linux-sdk

Can you validate please. 

@Kishan-Dhakan, as soon as this is validated can you update in the Docs repo please. 

   Cheers

   iain
