### ISSUE TITLE
Add video profile setting for 1080p,4k, 8k for all platforms, native sdk, as well as web sdk.

### ISSUE THREAD

**Issue by zeng16107** [AgoraIO/Docs-Source#644]
Add video profile setting for 1080p,4k, 8k for all platforms, native sdk, as well as web sdk.
and keep chinese language version same as english version.
https://docs.agora.io/cn/video-call-4.x/video_profile_apple_ng?platform=iOS

**Comment by zeng16107** [comment]
<html>
<body>


Resolution (Width x Height) | Frame Rate (fps) | Base Bitrate (Kbps)
-- | -- | --

160 × 120 | 15 | 65
120 × 120 | 15 | 50
320 × 180 | 15 | 140
180 × 180 | 15 | 100
240 × 180 | 15 | 120
320 × 240 | 15 | 200
240 × 240 | 15 | 140
424 × 240 | 15 | 220
640 × 360 | 15 | 400
360 × 360 | 15 | 260
640 × 360 | 30 | 600
360 × 360 | 30 | 400
480 × 360 | 15 | 320
480 × 360 | 30 | 490
640 × 480 | 15 | 500
480 × 480 | 15 | 400
640 × 480 | 30 | 750
480 × 480 | 30 | 600
848 × 480 | 15 | 610
848 × 480 | 30 | 930
640 × 480 | 10 | 400
1280 × 720 | 15 | 1130
1280 × 720 | 30 | 1710
960 × 720 | 15 | 910
960 × 720 | 30 | 1380
1920 × 1080 | 15 | 2080
1920 × 1080 | 30 | 3150
1920 × 1080 | 60 | 4780
2560 × 1440 | 30 | 4850
2560 × 1440 | 60 | 6500
3840 × 2160 | 30 | 6500
3840 × 2160 | 60 | 6500


</body>
</html>

**Comment by Kishan-Dhakan** [comment]
@zeng16107 could you please provide the first column values (Video profile) for these rows:

| 2560 × 1440 | 30 | 4850|
| 2560 × 1440 | 60 | 6500|
| 3840 × 2160 | 30 | 6500|
| 3840 × 2160 | 60 | 6500|

For more information, please see this comment https://github.com/AgoraIO/Docs-Source/issues/756#issuecomment-1296785725.
