### ISSUE TITLE
Can't find FAQ What are the differences between setEnabled and setMuted?

### ISSUE THREAD

**Issue by EmmaAzureAgora** [AgoraIO/Docs-Source#650]
Is this FAQ available in the new document? Can't find it. 
https://docs-preprod.agora.io/en/live-streaming-premium-legacy/faq/differences_between_setenabled_and_setmuted
Thank you!

**Comment by billy-the-fish** [comment]
Hi @EmmaAzureAgora,
   Nice question :-). This information is explained when we talk about core functionality for a channel. Could you have a look in https://docs.agora.io/en/video-calling/develop/product-workflow#implement-autoplay-blocking-screen-sharing-volume-control-and-mute for the web platform and say if this explains clearly enough. 
     Cheers
     
     Iain

**Comment by vakrolme** [comment]
The API reference for WebSDK references this link in multiple places: https://docs.agora.io/en/Interactive%20Broadcast/faq/differences_between_setenabled_and_setmuted

It's no longer available on the new Docs portal, so it redirects to Product Overview.

**Comment by billy-the-fish** [comment]
Hey @vakrolme, hope you are well. Nice point. @lemon-chen, is there any chance we could update the Web API ref so links to https://docs.agora.io/en/Interactive%20Broadcast/faq/differences_between_setenabled_and_setmuted now go to https://docs.agora.io/en/video-calling/develop/product-workflow#implement-autoplay-blocking-screen-sharing-volume-control-and-mute. 
    Nice spot.

**Comment by lemon-chen** [comment]
Add @***@***.***>.

https://github.com/AgoraIO/Docs-Source/issues/650. Looks like a link in the Web ref needs update.

Chen, Meng
Technical Writer
M: +86 15721372880
E: ***@***.******@***.***>

[Agora Logo]
Real-Time Engagement
Anytime, Anywhere, In Any App


发件人: Iain Cox ***@***.***>
日期: 星期五, 2023年2月10日 17:45
收件人: AgoraIO/Docs-Source ***@***.***>
抄送: Chen, Meng ***@***.***>, Mention ***@***.***>
主题: Re: [AgoraIO/Docs-Source] Can't find FAQ What are the differences between setEnabled and setMuted? (Issue #650)

Hey @vakrolme<https://github.com/vakrolme>, hope you are well. Nice point. @lemon-chen<https://github.com/lemon-chen>, is there any chance we could update the Web API ref so links to https://docs.agora.io/en/Interactive%20Broadcast/faq/differences_between_setenabled_and_setmuted now go to https://docs.agora.io/en/video-calling/develop/product-workflow#implement-autoplay-blocking-screen-sharing-volume-control-and-mute.
Nice spot.

―

**Comment by lemon-chen** [comment]
Hi @Iain ***@***.***>

Happy to update the link.

Unfortunately, the new link you supplied (https://docs.agora.io/en/video-calling/develop/product-workflow#implement-autoplay-blocking-screen-sharing-volume-control-and-mute ) doesn’t seem to include information about differences between setEnabled and setMuted. Can you point me to the right link?

Yaxi,
Cheers

发件人: Chen, Meng ***@***.***>
日期: 星期五, 2023年2月10日 19:29
收件人: AgoraIO/Docs-Source ***@***.***>, AgoraIO/Docs-Source ***@***.***>, Deng,Yaxi ***@***.***>
抄送: Mention ***@***.***>
主题: 答复: [AgoraIO/Docs-Source] Can't find FAQ What are the differences between setEnabled and setMuted? (Issue #650)
Add @***@***.***>.

https://github.com/AgoraIO/Docs-Source/issues/650. Looks like a link in the Web ref needs update.

Chen, Meng
Technical Writer
M: +86 15721372880
E: ***@***.******@***.***>

[Agora Logo]
Real-Time Engagement
Anytime, Anywhere, In Any App


发件人: Iain Cox ***@***.***>
日期: 星期五, 2023年2月10日 17:45
收件人: AgoraIO/Docs-Source ***@***.***>
抄送: Chen, Meng ***@***.***>, Mention ***@***.***>
主题: Re: [AgoraIO/Docs-Source] Can't find FAQ What are the differences between setEnabled and setMuted? (Issue #650)

Hey @vakrolme<https://github.com/vakrolme>, hope you are well. Nice point. @lemon-chen<https://github.com/lemon-chen>, is there any chance we could update the Web API ref so links to https://docs.agora.io/en/Interactive%20Broadcast/faq/differences_between_setenabled_and_setmuted now go to https://docs.agora.io/en/video-calling/develop/product-workflow#implement-autoplay-blocking-screen-sharing-volume-control-and-mute.
Nice spot.

―
