### ISSUE TITLE
Publish API settings after SDK migration 

### ISSUE THREAD

**Issue by Cilla-luodan** [AgoraIO/Docs-Source#658]
Hi Iain,
CS has requested a best practice document explaining the API setup after migrating from v3.x, v4.0.0 Preview or v4.0.0 Beta SDK to 4.x SDK with demo code.

The Chinese version has been released, please help with the English version.
Hefei has modified most of the links and text formatting after translation, please check and make some necessary changes before posting.
Thanks.

**Comment by Cilla-luodan** [comment]
[migrate_to_ng.md](https://github.com/AgoraIO/Docs-Source/files/9796400/migrate_to_ng.md)

**Comment by atovpeko** [comment]
@Cilla-luodan given the age of this issue, is this still relevant?

**Comment by atovpeko** [comment]
Closing this ticket due to its age. Please reopen or open a new one if these updates are still relevant, thank you
