### ISSUE TITLE
Comparison between Signaling and Chat

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#659]
As discussed, add the last chapter of the old product overview: RTM and Chat comparison as a reference article under Chat.
[agora_chat_overview.md](https://github.com/AgoraIO/Docs-Source/files/9798546/agora_chat_overview.md)

**Comment by billy-the-fish** [comment]
Done: https://docs.agora.io/en/agora-chat/reference/comparison-chat-signalling.
