### ISSUE TITLE
Release notes and variables

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#661]
Business case - For a new release, these are the minimum possible changes to be made. 
Subject Matter Expert - Kyle
Reviewer:
   - Technical: Kyle
   - Product: Karen
Scope: 
  - [Release notes](https://github.com/AgoraIO/Docs-Source/tree/main/shared/flexible-classroom/release-notes): Add information about this release in the following structure:
      - New features and improvements
              The list of good things in this release. 
      - Fixed issues
              The list of only public tickets and known issues that have been fixed.
      - Known issues
              The list of issues introduced in this release that users must be aware of. 
       Try and sort out reuse/conditional text so we don't have the same thing written or each platform. 
  - [Version number update](https://github.com/AgoraIO/Docs-Source/blob/main/shared/variables/global.js) - put the latest release number in. 
Acceptance criteria - Flexible classroom documentation ensures that new features are easy to implement by developers and experience by users. The documentation must follow the templates provided and be written using the Google Developer style guide.
Additional valuable information - All work must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone-26-flexible-classroom-uibuilder-release.

**Comment by kelzr** [comment]
The next version is 2.8.x. We haven't started writing yet because we haven't received input from R&D. When the Chinese release notes are completed, reviewed, and approved, we will attach the content here. 

Also, in the previous process, the English documentation was reviewed by Karen in addition to Kyle. I hope this information is useful to you.
