### ISSUE TITLE
Screen share error

### ISSUE THREAD

**Issue by SherpaGroup** [AgoraIO/Docs-Source#667]
Hello,

Thank you for the quick response.
all the code is working fine but as I click 「stop sharing」button, local user displays inside remote user id.
is there any way to append the local user inisde local.

Please download the program file from the link below.
https://filetalk.jp/download.php?cd=vYMT95as9V

thank you in advance.

**Comment by billy-the-fish** [comment]
hi @SherpaGroup,
   Thanks for the feedback. @saudsami, is there any chance you could have a quick look at this?

    cheers
    
      Iain

**Comment by saudsami** [comment]
The source of the problem is the following line in your code:
`channelParameters.localVideoTrack.play(remotePlayerContainer);`
It should be
channelParameters.localVideoTrack.play(localPlayerContainer);

**Comment by SherpaGroup** [comment]
dear @saudsami,
thank you very much for the quick reply.
It worked fine. thank you very much.
