### ISSUE TITLE
Android and iOS screenshare API is not listed in doc

### ISSUE THREAD

**Issue by EmmaAzureAgora** [AgoraIO/Docs-Source#668]
https://docs.agora.io/en/interactive-live-streaming/develop/product-workflow#api-reference
In this doc, it lists APIs as below:
startScreenCaptureByScreenRect
startScreenCaptureByDisplayId
startScreenCaptureByWindowId
However they are applying for windows or mac only. For iOS and Android, there is another API called startScreenCapture. Can you please add it?

**Comment by billy-the-fish** [comment]
Hi @EmmaAzureAgora,
  Thanks for the feedback. @saudsami, can you do this update while you are looking at https://github.com/AgoraIO/Docs-Source/issues/667 please. 
     Cheers
     
      Iain

**Comment by saudsami** [comment]
done
