### ISSUE TITLE
Doc Update for Flexible Classroom: Quickstart

### ISSUE THREAD

**Issue by pmmgithub** [AgoraIO/Docs-Source#679]
Hi, as requested by Flexible Classroom's SA colleagues, please help add a note to the [Launch a flexible classroom](https://docs.agora.io/en/flexible-classroom/get-started/#launch-a-flexible-classroom) section (Android and iOS platforms) as follows. We will also update CN doc accordingly.

> Ensure that you select the region you are located in; Otherwise, you might not be able to join a classroom with the following error.
> <img width="670" alt="error" src="https://user-images.githubusercontent.com/45590614/196652939-3992455b-7f6f-4dfe-b747-f40dd35cd4bc.png">

Thanks!

**Comment by billy-the-fish** [comment]
Update step 3 to say: To join a classroom, enter the **Room**, your **Name**, the class **Type**, your current **Region**, then click **Enter**. 


Please don't add a note as this looks like a known issue that should be in the release note.

**Comment by saudsami** [comment]
done
