### ISSUE TITLE
Doc Update for Classroom: Configure Flexible Classroom

### ISSUE THREAD

**Issue by pmmgithub** [AgoraIO/Docs-Source#680]
Hi, as requested by Flexible Classroom's SA colleague (), please help update the [Configure classroom storage and recording](https://docs.agora.io/en/flexible-classroom/get-started/enable-flexible-classroom#configure-classroom-storage-and-recording) section step 2 sub-step ii Configure storage by adding the description for the two fields "endpoint" and "fileNamePrefix". You could refer to the [CN doc](https://docs.agora.io/cn/agora-class/agora_class_configure?platform=Web#录制文件存储配置), 
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/45590614/196657150-e52499a9-528c-4b35-9a99-5ca040a505cc.png">

or reach out to the SA colleague Sun Liang (sunliang@agora.io) for more details. Thanks!

**Comment by saudsami** [comment]
done
