### ISSUE TITLE
Linux SDK version is wrong

### ISSUE THREAD

**Issue by Monichen-agora** [AgoraIO/Docs-Source#689]
The latest C++ Linux SDK should be v3.8.202, not 3.0.6.  The "direct download" links to a doc page, not the SDK download.
<img width="932" alt="Screen Shot 2022-10-19 at 10 33 04 AM" src="https://user-images.githubusercontent.com/77456831/196763780-a4f4a644-4a14-459c-a13c-45e3de1dda85.png">
<img width="623" alt="Screen Shot 2022-10-19 at 10 33 28 AM" src="https://user-images.githubusercontent.com/77456831/196763863-bff9e8e2-3f68-4f10-9a2c-2c669b5f95d9.png">

**Comment by atovpeko** [comment]
@billy-the-fish some input here, please. Which page in the source/repo is this?

**Comment by atovpeko** [comment]
This is already fixed for Server Gateway SDK.
