### ISSUE TITLE
Need to add a requirement when using Google Cloud Storage

### ISSUE THREAD

**Issue by rkalra247** [AgoraIO/Docs-Source#690]
The user needs to add *rewrite* permission as well when using Agora Cloud Recording with Google Cloud Storage to avoid upload errors. Reference documentation: https://cloud.google.com/storage/docs/access-control/iam-json

**Comment by atovpeko** [comment]
@rkalra247 is there a specific page in the docs this has to be added to?

**Comment by rkalra247** [comment]
@atovpeko , in prerequisites you can mention under Google Cloud so users are aware that this is a necessary step to upload recording successfully to Google Cloud. 
Reference Documentation: https://docs.agora.io/en/cloud-recording/get-started/getstarted#prerequisites

**Comment by atovpeko** [comment]
@billy-the-fish I don't see permissions mentioned at all on this page, even for Google Cloud. Does it make sense to only add this one permission somewhere? Or is it better to rework this page so that required permissions are mentioned for all cloud storage services?

**Comment by billy-the-fish** [comment]
Would it not be best to add this permission in the JSON object in the doc?
