### ISSUE TITLE
[RTE 3.x] Github links need to be updated

### ISSUE THREAD

**Issue by kelzr** [AgoraIO/Docs-Source#692]
According to the feedback from the technical support team, the Github link in the documentation has been 404, so the Chinese documentation team has checked and fixed it as follows: API-Examples/tree/master is replaced globally with API-Examples/tree/legacy, and API-Examples/blob/master is replaced globally with API-Examples/blob/legacy.

ps. The links were changed because the Chinese development team updated the repository branch, which was not synchronized with the documentation team.

**Comment by atovpeko** [comment]
Pull request open: https://github.com/AgoraIO/Docs-Source-Legacy/pull/21
