### ISSUE TITLE
Add usage warning to Agora Analytics doc. 

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#694]
AA usage warning is missing in the new EN doc:

![企业微信截图_36101eb1-200a-4ca2-9ad1-ddcf6ebb4ad9](https://user-images.githubusercontent.com/22094088/196889465-b6390230-6bd8-420c-a2cd-f22c5e2f6beb.png)
![企业微信截图_21c4cbce-a641-4001-b159-93e8b87bc458](https://user-images.githubusercontent.com/22094088/196889488-dbc5ace5-707c-4229-a327-fcefd254f375.png)

If you could update please. Message is:

Disclaimer

“ The usage data provided in the Usage Overview page is for reference only and is not used for billing calculation”

**Comment by pkpakala** [comment]
[atovpeko](https://github.com/atovpeko), We need to the word "Disclaimer" and create a red border around the message for greater visibility similar to the old doc reference above which was highlighted in red around the warning area.

--------------------------------------------------------------------------------------------------------------------------
**Disclaimer 
The usage data provided in the Usage Overview page is for reference only and is not used for billing calculation
--------------------------------------------------------------------------------------------------------------------------

**Comment by pkpakala** [comment]
Need to change the screen shots attached under the session "Quality Overview" to remove the chinese word besides  Shawn "Shawn曾庆峰" which is indicated currently as a logged user.
![Screenshot 2022-10-27 at 10 06 17 AM](https://user-images.githubusercontent.com/99174708/198197067-3ec6697b-20a0-42f3-a7e2-b949706060c2.png)

**Comment by billy-the-fish** [comment]
@Mr-spShuvo, the presentation of the admonitions is from https://github.com/AgoraIO/Docs-Source/issues/78 which should have moved to the Docs repository. Maybe we should talk to Malavika about how they should be represented. Or even, if we just use standard Markdown admonitions etc.
