### ISSUE TITLE
All Platforms: leaveChannelEx updated. 

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#701]
* Business case - changes functionality for multi-channel ILS
* Fix version - 4.1.0
* Subject Matter Expert - Deng Qiming: dengqiming@agora.io
tale
* Review:
  * PM: TBD
  * Technical: Deng Qiming
  * Language: Iain
* Scope - [NMS-6001](https://jira.agoralab.co/browse/NMS-6001). Check that all code with or doc mentions of f leaveChannelEx  use the correct parameters and the code examples run. Main doc is: https://docs.agora.io/en/interactive-live-streaming/develop/live-streaming-over-multiple-channels. 
  * Tasks:
    - [x] @saudsami: complete for Android
    - [x] @nirm2009: complete for iOS and MacOS
    - [x] @hussain-khalid: complete for Windows
* Acceptance criteria - all docs must be technically correct, have no broken links, follow the templates provided and be written following the Google Developer style guide.
* Additional valuable information - Branches for all tickets must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone-28-vsdk-4.1.0

**Comment by saudsami** [comment]
Checked the multi-channel code that uses `leaveChannelEx`. Works ok. 
Found some minor issues and fixed them.

**Comment by billy-the-fish** [comment]
Done
