### ISSUE TITLE
iOS, maybe Android: stream video from multiple cameras to a channel

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#703]
* Business case - iOS enables users to run both cameras at the same time
* Fix version - 4.1.0
* Subject Matter Expert - zhonghuan: zhonghuan@agora.io
* Review:
  * PM: TBD
  * Technical: zhonghuan
  * Language: Iain
* Scope - [NMS-5356](https://jira.agoralab.co/browse/NMS-5356): add a note in the "Enable your app to display a local video stream" section in the [iOS quickstart](https://docs.agora.io/en/interactive-live-streaming/get-started/get-started-sdk) to say you can enable both cameras with a link to the API ref. Add links to the reference section. 
  * Tasks:
    - [x] @saudsami: complete for Android
    - [x] @nirm2009: complete for iOS and MacOS
* Acceptance criteria - all docs must be technically correct, have no broken links, follow the templates provided and be written following the Google Developer style guide.
* Additional valuable information - Branches for all tickets must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone-28-vsdk-4.1.0

**Comment by billy-the-fish** [comment]
Check with @Cilla-luodan to see if Android will also be release.

**Comment by saudsami** [comment]
Can't see which APIs to use for streaming video from multiple cameras.
Please provide details.

**Comment by saudsami** [comment]
I have looked through the latest Android API ref and can't find the method `enableMultiCamera`. I have also checked the 4.1.0 SDK and it does not recognize this method.
