### ISSUE TITLE
All platforms: enable open and close of the B frame when you call setvideoEncoderConfig

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#709]
* Business case - Some live customers need to turn on or off B frames during channel encoding and streaming
* Fix version - 4.1.0
* Subject Matter Expert - wangchunkun: wangchunkun@agora.io
* Review:
  * PM: TBD
  * Technical: wangchunkun
  * Language: Iain
* Scope -From [NMS-3626](https://jira.agoralab.co/browse/NMS-3626) `VideoEncoderConfiguration`  adds a structure member compressionPreference. Check the docs for all mentions of `VideoEncoderConfiguration` and ensure the code runs correctly. Do the updates for this feature in coordination with https://github.com/AgoraIO/Docs-Source/issues/877. 
  * Tasks:
    - [x] @saudsami: complete for Android
    - [x] @nirm2009: complete for iOS and MacOS
    - [x] @hussain-khalid: complete for Windows
* Acceptance criteria - all docs must be technically correct, have no broken links, follow the templates provided and be written following the Google Developer style guide.
* Additional valuable information - Branches for all tickets must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone-28-vsdk-4.1.0

**Comment by saudsami** [comment]
Android platform:
Tested the code and updated the call-quality doc.
Tested symbl.ai to the extent of the use of 'VideoEncoderConfiguration'.
Couldn't find the use of VideoEncoderConfiguration in the cloud gateway doc.

**Comment by billy-the-fish** [comment]
Done.
