### ISSUE TITLE
Callback events for Cloud Recording Service require Signature Verification 

### ISSUE THREAD

**Issue by rkalra247** [AgoraIO/Docs-Source#713]
https://docs-preprod.agora.io/en/Agora%20Platform/ncs?platform=Android#signature-verification

This is very crucial part for listening to our call back events so I would say immediate fix is required.

**Comment by billy-the-fish** [comment]
There are signature verification sections in a couple of products. Can you align them and do resuse with the doc you wrote for NCS pease.

**Comment by saudsami** [comment]
The signature verification part is ready for reuse. 
Please let me know where I should add it for cloud recording.
