### ISSUE TITLE
Update use an extension guide for all platforms

### ISSUE THREAD

**Issue by Kishan-Dhakan** [AgoraIO/Docs-Source#72]
Business case - Developers must be able to rapidly and easily integrate an extension into their app for android, iOS and Web platforms.
Fix version - Hard Release
Subject Matter Expert - Iain
Reviewer - USROW doc team
Scope - Use an extension for Android, iOS, Web

Source: https://docs.agora.io/en/live-streaming-premium-4.x-beta/use_extension_android?platform=Android

**Comment by billy-the-fish** [comment]
Is this done?

**Comment by Kishan-Dhakan** [comment]
This was divided into separate tasks like this one https://github.com/AgoraIO/Docs-Source/issues/94 when we created the platform milestones. For the original 3 platforms (Android, web, iOS), the guides seem to be complete in our main branch. It's safe to close this.
