### ISSUE TITLE
Background transparency for virtual background

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#720]
* Business case - customer request
* Fix version - 4.1.0
* Subject Matter Expert - cairui: cairui@agora.io
* Review:
  * PM: TBD
  * Technical: cairui
  * Language: Iain
* Scope - [NMS-1670](https://confluence.agoralab.co/pages/viewpage.action?pageId=900239555), in the virtual background extension, https://docs.agora.io/en/video-calling/develop/virtual-background ensure the calls are as follows:
   - Host: 
       ```java
         enableVirtualBackground
         setParameters {"rtc.video.send_alpha_data":true}
      ```
    - Audience
          ```java
            registerVideoFrameObserver set alpha_buffer (recommended to change the member name of each platform to the same)
            onRenderVideoFrame
      ```
      Also. check call to AgoraOutputVideoFrame, VideoFrame and media::base::VideoFrame are correct with the updated SDK. 
  * Tasks:
    - [x] @saudsami: complete for Android
    - [x] @nirm2009: complete for iOS and MacOS
    - [x] @hussain-khalid: complete for Windows
* Acceptance criteria - all docs must be technically correct, have no broken links, follow the templates provided and be written following the Google Developer style guide.
* Additional valuable information - Branches for all tickets must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone-28-vsdk-4.1.0

**Comment by billy-the-fish** [comment]
Update the ticket with more information and relate to virtual background update ticket.

**Comment by saudsami** [comment]
The [link]( https://docs.agora.io/en/video-calling/develop/virtual-background) in the issue description says that "This extension is for Web only". When I look through the available extensions in the Extension Market place, there are at least three extensions that allow you to set virtual backgrounds.
* Banuba Face AR SDK
* DeepAR
* VisionLab DoreSegment
Please clarify which extension this issue refers to.
