### ISSUE TITLE
Automatic upload of log files

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#723]
* Business case - ensure real-time access to user log analysis problems
  * Fix version - 4.1.0
  * Subject Matter Expert - wanpiao@agora.io
  * Review:
    * PM: TBD
    * Technical: wanpiao
    * Language: Iain
  * Platforms: Android, iOs, MacOs, Windows
  * Scope - [NMS-1344](https://jira.agoralab.co/browse/NMS-1344), the api call is setLocalAccessPoint. Add a line to the log section saying if you want to upload automatically to a CDN in https://docs.agora.io/en/video-calling/develop/ensure-channel-quality. The method and object is int `setLocalAccessPoint(const LocalAccessPointConfiguration& config);`. 
  * Tasks:
    - [x] @saudsami: complete for Android
    - [x] @nirm2009: complete for iOS and MacOS
    - [x] @hussain-khalid: complete for Windows
  * Acceptance criteria - all docs must be technically correct, have no broken links, follow the templates provided and be written following the Google Developer style guide.
  * Additional valuable information - Branches for all tickets must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone-28-vsdk-4.1.0

**Comment by saudsami** [comment]
Updated.
The log file configuration section was missing in the Android call-quality doc so I have added it.
