### ISSUE TITLE
onClientRoleChanged updated to enable audience identity

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#725]
* Business case -  make it easier to see when your client moves to low latencey. 
  * Fix version - 4.1.0
  * Subject Matter Expert - 
  * Review:
    * PM: TBD
    * Technical: 
    * Language: Iain
  * Platforms: Android, iOs, MacOs, Windows
  *  Scope - [CSD-44405](https://jira.agoralab.co/browse/CSD-44405):  When the client uses the AUDIENCE_LATENCY_LEVEL_LOW_LATENCY identity, the identity switch is successful, and the SDK onClientRoleChanged can return the correct identity.  Check all docs for calls to onClientRoleChanged and check that the code works with the 4.1.0 SDK. 
  * Tasks:
    - [x] @saudsami: complete for Android
    - [x] @nirm2009: complete for iOS and MacOS
    - [x] @hussain-khalid: complete for Windows
  * Acceptance criteria - all docs must be technically correct, have no broken links, follow the templates provided and be written following the Google Developer style guide.
  * Additional valuable information - Branches for all tickets must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone-28-vsdk-4.1.0

**Comment by saudsami** [comment]
We are not using this callback anywhere in our Android documentation sample code.
Nevertheless, I have tested the callback. The callback is fired only if you also set the `clientRoleType` when you change the `audienceLatencyLevel`. If you only change the `audienceLatencyLevel` without setting the `clientRoleType` in `updateChannelMediaOptions `the callback is not fired.

**Comment by nirm2009** [comment]
Please refer my findings for iOS/macOS 4.1.0 SDK behaviour for `didClientRoleChanged` with and without `lowLatency` changes:

Adding `option.audienceLatencyLevel = .lowLatency` line, in joinChannel(), before agoraEngine.joinChannel():
	Broadcast selected as client role on app UI:
		agoraEngine.joinChannel() returns a -2 (AgoraErrorCodeInvalidArgument), call doesn't join.

	Audience selected as client role on app UI:
		agoraEngine.joinChannel() returns 0, successfully joins the call.
		Calling `setClientRole(.broadcaster)` doesn't fire didClientRoleChanged.
		Calling `setClientRole(.audience)` correctly fires `didClientRoleChanged (oldRole: 2, newRole: 2)`.
		

Without adding `option.audienceLatencyLevel = .lowLatency` line
	Broadcast selected as client role on app UI:
		agoraEngine.joinChannel() returns 0, successfully joins the call and correctly fires `didClientRoleChanged (oldRole: 2, newRole: 1)`.
		Calling `setClientRole(.broadcaster)` correctly fires `didClientRoleChanged (oldRole: 1, newRole: 1)`.
		Calling `setClientRole(.audience)` doesn't fire didClientRoleChanged.

	Audience selected as client role on app UI:
		agoraEngine.joinChannel() returns 0, successfully joins the call.
		Calling `setClientRole(.broadcaster)` doesn't fire didClientRoleChanged.
		Calling `setClientRole(.audience)` correctly fires `didClientRoleChanged (oldRole: 2, newRole: 2)`.
