### ISSUE TITLE
Recording callback service isn't GA in ROW. Customer needs support help to enable it.

### ISSUE THREAD

**Issue by EmmaAzureAgora** [AgoraIO/Docs-Source#730]
https://docs.agora.io/en/cloud-recording/reference/rest-api/rest-api-overview#callback-information
In this document, there is no detailed information listed so that customer can follow up to provide.

There used to be such information list in [Message Notification Service](https://docs.agora.io/en/Agora%20Platform/ncs)
However NCS link is broken now.

**Comment by billy-the-fish** [comment]
Hi @EmmaAzureAgora , 
   Thanks for the feedback. From what I understand, MNS is still beta. We have https://github.com/AgoraIO/Docs-Source/issues/653 to work on this doc. 

    Cheers

    Iain

**Comment by billy-the-fish** [comment]
Same as your MNS l ink I think.
