### ISSUE TITLE
Metrics ID link is set wrong

### ISSUE THREAD

**Issue by frank005** [AgoraIO/Docs-Source#745]
On this page: https://docs.agora.io/en/agora-analytics/reference/api#get-quality-metrics

In this bullet: mid: Number. The ID of the metric. See [Metrics ID](https://docs.agora.io/en/agora-analytics/reference/api#user-content-metrics-id) for details.

The link is set is set wrong for Metrics ID as you can see above, you can check the correct link below
https://docs.agora.io/en/agora-analytics/reference/api#metrics-id

**Comment by Kishan-Dhakan** [comment]
Closed by https://github.com/AgoraIO/Docs-Source/pull/795
