### ISSUE TITLE
Integrate changes in Kyle's spreadsheet into the Flexible Classroom docs

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#747]
Business case - Agora customers must be able to easily use new and existing features in this release.
Fix version - 2.8
Subject Matter Expert - Kyle
Review: -
- PM: Kyle
- Technical: Monica Chen.
- Language: Iain
Scope - all docs mentioned in https://apprtcio-my.sharepoint.com/:x:/g/personal/qianfen_agora_io/Eb9zS_ezmRFHj_7jYsFU-QcBdJqOGD1VcToJT-oqkxpyHw?e=fFwflU&CID=2485948b-e6d1-11a0-79fe-99f305d76a1f
Estimated -
Acceptance criteria - Flexible classroom documentations ensure that new features are easy to implement by developers and experience by users. The documentation must follow the templates provided and be written using the Google Developer style guide.
Additional valuable information - Branches for all tickets must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone-26-flexible-classroom-uibuilder-release.

**Comment by saudsami** [comment]
I have made the suggested changes and added my comments to the spreadsheet.

**Comment by billy-the-fish** [comment]
I've added comments and requested one change.
