### ISSUE TITLE
Can't find the mapping between High and low stream table in new doc.

### ISSUE THREAD

**Issue by EmmaAzureAgora** [AgoraIO/Docs-Source#748]
Hello Team,
In this doc, the table about high and low stream mapping can't be found in new doc. Here previous doc.
https://docs-preprod.agora.io/en/live-streaming-premium-legacy/multi_user_video?platform=iOS#mainstream-video-profiles

Can you please add it somewhere in new doc?

Thank you!

**Comment by billy-the-fish** [comment]
Nice spot. 

@kishan can you add this table to the reference in https://docs.agora.io/en/video-calling/develop/ensure-channel-quality please.
