### ISSUE TITLE
[RTC-NG] Flutter 6.0.0 API Reference

### ISSUE THREAD

**Issue by jinyuagora** [AgoraIO/Docs-Source#750]
Modified based on feedback from tech support. Plz kindly re-upload the updated Flutter 6.0.0 API reference pack. Thanks.
[flutter-ng.zip](https://github.com/AgoraIO/Docs-Source/files/9868341/flutter-ng.zip)

**Comment by Kishan-Dhakan** [comment]
Hi @jinyuagora, could you provide a bit more context for this ticket? I suppose the files provided above should replace the ones in https://github.com/AgoraIO/API-Reference, is that correct? Should it be done for Video SDK alone or for all products? Thanks in advance

**Comment by jinyuagora** [comment]
Hi @Kishan-Dhakan, the files provided above should replace the API reference in https://api-ref.agora.io/en/voice-sdk/flutter/6.x/API/rtc_api_overview_ng.html for all RTC products (Flutter 6.0.0).

**Comment by jinyuagora** [comment]
As for operations in GitHub repos, guess you need to further confirm with Shuvo.

**Comment by Kishan-Dhakan** [comment]
@Mr-spShuvo I've made a PR for this issue https://github.com/AgoraIO/API-Reference/pull/18, could you please help me by reviewing it?

**Comment by billy-the-fish** [comment]
@Kishan-Dhakan, quick question, have you checked that you have the latest CSS so the doc looks like https://api-ref.agora.io/en/voice-sdk/flutter/6.x/API/rtc_api_overview_ng.html?

**Comment by Kishan-Dhakan** [comment]
@billy-the-fish I haven't changed the css files or the index.html, they're the same as in main. However, the side panel seems to not render correctly anymore after updating the class html files. I'm looking into it.
![image](https://user-images.githubusercontent.com/42718091/199722336-3200fef4-3fba-4a29-a470-e212decb6f28.png)
