### ISSUE TITLE
Flutter UI Kit Quickstart missing piece

### ISSUE THREAD

**Issue by tadaspetra** [AgoraIO/Docs-Source#753]
If you are using iOS as a target platform you need to do the same step 3 from [iOS project setup](https://docs.agora.io/en/video-calling/get-started/get-started-uikit#project-setup)

**Comment by saudsami** [comment]
Not sure what this means, can you please clarify?

**Comment by saudsami** [comment]
Sorry, I understand now.
I have made the change.
