### ISSUE TITLE
Integrate comments about Video Calling for Web

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#756]
![wecom-temp-d7194e0e715be815b8e7dc707bd010ec](https://user-images.githubusercontent.com/22094088/198223696-8d368518-a069-492b-87cb-0d8aea23e684.png)

![wecom-temp-bb5e7e3bd1d6bb807560a4e734f53fbd](https://user-images.githubusercontent.com/22094088/198223725-c78884c3-efa8-4432-b805-fe8c0d29768e.png)

![wecom-temp-998dbf8a8635a9beabce06ef0e928961](https://user-images.githubusercontent.com/22094088/198223773-484a9728-a226-4b80-99e2-d93787d6ad01.png)

#2 in the web sdk, we don't provide audio scenarios setting, it is feature in the native sdk.
![wecom-temp-81e2e8095194296128642011c6027337](https://user-images.githubusercontent.com/22094088/198223823-1fc4c67d-78b0-4d2e-ac50-bdad02c3e856.png)

# 3 as far as i know, it seems that mirror mode can only be archived canvas technology, i'm not sure when we implement this feature in the web sdk now.
![wecom-temp-a621e4e97619cd4c2df818470bc4255e](https://user-images.githubusercontent.com/22094088/198223872-d2673114-fffc-4b48-8b87-6054ba2d00a0.png)

i think we'd like invite webrtc team and product manager to review the english doc for web sdk, make sure the contents are correct.

#4 regarding "Video profile tble" section, we can reference to this link https://api-ref.agora.io/en/video-sdk/web/4.x/globals.html

![wecom-temp-27fbd4df4eceab9f7391425c238f9e5c](https://user-images.githubusercontent.com/22094088/198223934-1182840e-4b44-47ed-9c98-2f4f7dc7046f.png)

![wecom-temp-f2a928151e0f5355859ebec135ff567f](https://user-images.githubusercontent.com/22094088/198223958-66242bd0-832d-4c99-8452-d1d9d030c4f7.png)

by the way, in web sdk, we support 2k+,4K as well. it seems we need to update the table as well.

#1 mainstream browser cannot capture stereo audio track, so the content is not correct regarding list of audio profiles

#5 regarding Media player page, in web sdk, we use <video> and <audio> tag to play, and support 3rd party web media palyer such as video.js as well. in this "Media player page,", it looks like it is referring to "native media player kit" developed by agora,

![wecom-temp-5cda088e62f530cbb26c85ccea1ae95d](https://user-images.githubusercontent.com/22094088/198224067-7733e6ca-909d-4245-bb1b-ce97706317fb.png)

#6 regarding "Audio and voice effects" page, it seems that there are some contents are related to native sdk as well.

![wecom-temp-5e76f30480bbb39475ab637b258e3349](https://user-images.githubusercontent.com/22094088/198224105-e756d187-69b1-4616-95e2-fccff9107d93.png)

#7 regarding "raw video and audio processing" page,  the statement "This feature is not supported for Web." is NOT correct. in web sdk, we provide extensions like ai denoiser, virtual background for pre-process and post-process phases.

![wecom-temp-a38764ec54cc434e518982b98d890759](https://user-images.githubusercontent.com/22094088/198224166-f84284b5-c5dc-4384-bc77-f4d5da00f159.png)

#8 associating Tab is not correct .

![wecom-temp-b2a639e8e82d52b51e0b204109684c28](https://user-images.githubusercontent.com/22094088/198224203-019d4c04-a421-4167-ad25-1a1c6c8e08c7.png)

**Comment by dengyaxi** [comment]
The first column is missing

![wecom-temp-4eb4626167852d2c8ba2c29dfad5d2d2](https://user-images.githubusercontent.com/73678648/198969613-d7074c2e-a83e-4a7a-bdf1-aca43d3d6fa8.png)

Source: [Recommended video profiles.md](https://github.com/AgoraIO/Docs-Source/files/9899559/Recommended.video.profiles.md)

**Comment by Kishan-Dhakan** [comment]
@dengyaxi the table was updated according to information provided in https://github.com/AgoraIO/Docs-Source/issues/644. I'm adding the first column back but could you provide the first column values for these rows as they're missing:

| 2560 × 1440 | 30 | 4850|
| 2560 × 1440 | 60 | 6500|
| 3840 × 2160 | 30 | 6500|
| 3840 × 2160 | 60 | 6500|

**Comment by dengyaxi** [comment]
@Kishan-Dhakan They are not provided in CN doc either. My suggestion is to reach out to the Global Product Manager for confirmation

**Comment by dengyaxi** [comment]
Duplicate content in release notes
<img width="903" alt="wecom-temp-37abdfb6d759c38b509fdd1a6884afed" src="https://user-images.githubusercontent.com/73678648/199198792-1d3101e5-7238-4fd1-bf57-c882ac471b98.png">

**Comment by dengyaxi** [comment]
Update this iOS known issue according to [iOS_issue_audio_cutoff.md](https://github.com/AgoraIO/Docs-Source/files/9908500/iOS_issue_audio_cutoff.md)


<img width="779" alt="image" src="https://user-images.githubusercontent.com/73678648/199200339-a2be824b-0f00-4f97-8ad2-fd941e3189f5.png">

**Comment by Kishan-Dhakan** [comment]
Re 3: https://api-ref.agora.io/en/video-sdk/web/4.x/interfaces/videoplayerconfig.html#mirror Web SDK still seems to be supporting mirror mode.

**Comment by Kishan-Dhakan** [comment]
Re 1: https://api-ref.agora.io/en/video-sdk/web/4.x/globals.html#audioencoderconfigurationpreset, web sdk seems to supporting the audio profiles mentioned in the doc.

**Comment by Kishan-Dhakan** [comment]
Re 5: needs some more information, am I missing something silly?
