### ISSUE TITLE
Platform option is not easy to find

### ISSUE THREAD

**Issue by The-Machine-Tango** [AgoraIO/Docs-Source#77]
https://agoradocs-internal.netlify.app/interactive-live-streaming/develop/use-an-extension

**Comment by The-Machine-Tango** [comment]
Seems the platform options at the top is easy to miss. I was trying to see the Android platform but it took me a while to notice that.

**Comment by billy-the-fish** [comment]
We had a discussion about this one. I'm afraid the decision is to leave as is.
