### ISSUE TITLE
Web 4.14.2 Immediate release

### ISSUE THREAD

**Issue by embkim** [AgoraIO/Docs-Source#770]
**Business case**: Web 4.14.2 was officially released yesterday and needs to be added to Docs immediately.

**Subject Matter Expert**: Jennifer Xin

**Reviewers**: n/a

**Scope**: Update release notes (attached: [v4.14.2.md](https://github.com/AgoraIO/Docs-Source/files/9885421/v4.14.2.md)) and download (https://download.agora.io/sdk/release/Agora_Web_SDK_v4_14_2_FULL.zip)

**Acceptance criteria**: n/a

**Additional valuable information** - n/a

**Comment by billy-the-fish** [comment]
@hussain-khalid, can you drop everything and get this baby out the door please:

This repo: update the Video SDK for Web release notes
Docs repo: update the download link and text, and the API ref link text
API reference repo: update the title in all pages for the Video and Voice SDKs for web to say 4.14.2.
