### ISSUE TITLE
Admonitions are not rendered properly

### ISSUE THREAD

**Issue by dengyaxi** [AgoraIO/Docs-Source#78]
The recommended way of adding admonitions is https://docusaurus.io/docs/markdown-features/admonitions, but it does not render as expected 
![企业微信截图_acdd40c8-e8bd-4983-a94e-a5226e6fa778](https://user-images.githubusercontent.com/73678648/182811244-cc2b86a0-2b0d-4955-96ec-aa0ced29c763.png)

@Mr-spShuvo Could you help look into this after soft launch? Thank you

**Comment by billy-the-fish** [comment]
No hiurry.

**Comment by billy-the-fish** [comment]
Can you move this ticket to https://github.com/AgoraIO/Docs/issues please. Closing it here.
