### ISSUE TITLE
[flutter] Quick start may not work correctly

### ISSUE THREAD

**Issue by littleGnAl** [AgoraIO/Docs-Source#815]
There's user feedback that [video call quick](https://docs.agora.io/en/video-calling/get-started/get-started-sdk) started not work correctly, please help check and correct the doc

https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/805

**Comment by Kishan-Dhakan** [comment]
The quickstart seems to work correctly on android. Since flutter supports multiple platforms, could you please confirm on which platform the user found the quickstart to be not working?
