### ISSUE TITLE
Update the custom video doc to choose a specific camera lense on a phone

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#821]
**Business case**: easily implement a useful real-world scenario.

**Subject Matter Expert**: Tadas

**Reviewers**:
  - *Technical*:  Nikita
  - *Language*: Iain

**Scope**: Update the code in https://docs.agora.io/en/video-calling/develop/custom-video-and-audio to choose a specific camera lens. 
  - [ ] Flutter - Tadas 
  - [ ] Android - Saud
  - [x] iOS - Max
  - [x] macOS - Max
  - [ ] Web - Hussain
  - [ ] React - Kishan
  - [ ] Electron - Hussain
  - [ ] Unity - Hussain
  - [ ] Windows - No

**Acceptance criteria**: Developers can easily understand the workflow and use the code to implement in their app. 

**Additional valuable information**:

**Comment by maxxfrazer** [comment]
This will be handled with POC3
