### ISSUE TITLE
Update docs from existing docs. 

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#828]
**Business case**: Understand the new features

**Subject Matter Expert**: Working from reviewed docs previously written.

**Reviewers**:
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: 

l   v4.15.0 release notes: https://docs-preprod.agora.io/en/live-streaming-premium-legacy/release_web_ng?platform=Web&versionId=0a1d1be0-5b29-11ed-8dae-bf25bf08a626#v4150. Will be supplied in MD. 

l  Extension release notes (new doc): https://docs-preprod.agora.io/en/video-call-4.x/release_extension_web_ng?platform=Web. To be supplied in MD. 

l  AI Noise Suppression doc. Update from: https://docs-preprod.agora.io/en/video-call-4.x-beta/noise_reduction_web_ng?platform=iOS&versionId=83b570b0-5697-11ed-8dae-bf25bf08a626

l  Virtual background doc: Update from: https://docs-preprod.agora.io/en/video-call-4.x-beta/virtual_background_web_ng?platform=iOS&versionId=cb1cbb50-55db-11ed-8dae-bf25bf08a626

**Acceptance criteria**: Criteria for this issue to be approved.

**Additional valuable information**: Anything else that will help with this issue.

**Comment by dengyaxi** [comment]
Hi. @billy-the-fish @Kishan-Dhakan Please kindly find the MD files below: 

- [4.15-release-notes.md](https://github.com/AgoraIO/Docs-Source/files/9950445/4.15-release-notes.md)
- [Extension release notes.md](https://github.com/AgoraIO/Docs-Source/files/9950447/Extension.release.notes.md)
- [Noise suppression.md](https://github.com/AgoraIO/Docs-Source/files/9950448/Noise.suppression.md)
- [Virtual Background.md](https://github.com/AgoraIO/Docs-Source/files/9950449/Virtual.Background.md)

**Comment by billy-the-fish** [comment]
The release notes are already done in https://github.com/AgoraIO/Docs-Source/pull/841#pullrequestreview-1170169769.

**Comment by dengyaxi** [comment]
The release notes were updated since #841 was opened. Please make a diff for the release notes, too
