### ISSUE TITLE
RTC 3.7.2 Release Notes: Editorial Review Suggestions

### ISSUE THREAD

**Issue by kelzr** [AgoraIO/Docs-Source#839]
Last week's 3.7.2 release was very urgent, so the documentation had not yet passed the Editor's review. Now I am sharing the review comments with you, please follow up on these changes:

- Change "otherwise, users with Android 12.0 or above devices cannot use Bluetooth properly" to "otherwise, users with devices running Android 12.0 or later cannot use Bluetooth properly"
- Change "The virtual metronome worked exceptionally, such as audio in the MP3 format was not supported and the beats played were not as expected." to "The virtual metronome did not perform as expected; for example, audio in the MP3 format was not supported, and the beats played were sometimes incorrect."
- Change "In the communication channel profile, when a user was using a Bluetooth headset for a call left a channel, and re-joined it, the sound was played through the speaker instead of the Bluetooth headset." to "In the communication channel profile, when a user who was using a Bluetooth headset for a call left and then rejoined a channel, the sound was played through the speaker instead of the Bluetooth headset."

**Comment by hussain-khalid** [comment]
This issue was resolved here: https://github.com/AgoraIO/Docs-Source-Legacy/issues/33
