### ISSUE TITLE
Quickstart for Unreal engine

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#84]
Business case - developers need to easily implement Agora functionality using Video SDK in a flutter app
Fix version - hard release
Subject Matter Expert - [wangxidong@agora.io](mailto:wangxidong@agora.io), [lihanquan@agora.io](mailto:lihanquan@agora.io) , [luodan@agora.io](mailto:luodan@agora.io).
Reviewer - @saudsami 
Scope - Quickstart for Video Calling and ILS:
    The bare-bones app MUST have the same structure and functionality as the other platforms. 
    Existing doc: https://github.com/AgoraIO/Docs-Source/blob/milestone16-unrealengine/interactive-live-streaming/get-started/get-started-sdk.mdx
    Use https://docs.unrealengine.com/4.27/en-US/ProgrammingAndScripting/ProgrammingWithCPP/CPPProgrammingQuickStart/ to learn. 
[demoCode.zip](https://github.com/AgoraIO/Docs-Source/files/10113426/demoCode.zip)
[Reference.docx](https://github.com/AgoraIO/Docs-Source/files/10152206/Reference.docx)
[quickStart.docx](https://github.com/AgoraIO/Docs-Source/files/10152207/quickStart.docx)

Acceptance criteria - developers must be able to easily implement video calling and ILS event  functionality for Unreal Engine
Milestone branch - h: https://github.com/AgoraIO/Docs-Source/tree/milestone16-unrealengine

**Comment by Cilla-luodan** [comment]
Hi @saudsami, can you provide a md file of the current quick start guide to wangxidong@agora.io so he can replace the code, and you can do the rest.

**Comment by saudsami** [comment]
Hi @Cilla-luodan 
I have emailed the quickstart .md files. Please send me the replacement code so that I may put it into the doc.

**Comment by billy-the-fish** [comment]
@Cilla-luodan . any luck with the replacement code?

**Comment by hussain-khalid** [comment]
Hi @Chuchun1991,
Yesterday, I set up an environment for the unreal engine. Now, I am integrating the VSDK and I need at least 2 days to get it complete. I will share my doc structure soon. if you have already made a structure for the doc, please share it. This will help me to get things complete quickly.

**Comment by Chuchun1991** [comment]
Hi @hussain-khalid. Thanks for the update. In fact I just started to explore Unreal, and I'm looking forward to your sharing. If you have any question, feel free to discuss with me.

**Comment by hussain-khalid** [comment]
Hi @Chuchun1991, 

This is get started for unreal: https://github.com/AgoraIO/Docs-Source/pull/1015
