### ISSUE TITLE
Update the API ref for Android v3.7.2 (voice, video, live-streaming)

### ISSUE THREAD

**Issue by pmmgithub** [AgoraIO/Docs-Source#854]
**Business case**: We fixed some issues reported by colleagues and customers, including some dead links, and edited the language for some interfaces based on editorial review. See the attached ZIP file.

**Subject Matter Expert**: Kelu Peng / Miaomiao Pan

**Reviewers**:
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: The API ref for Android v3.7.2; product: voice, video, live-streaming 

**Acceptance criteria**: Criteria for this issue to be approved.

**Additional valuable information**: N/A

[html.zip](https://github.com/AgoraIO/Docs-Source/files/9967137/html.zip)

**Comment by billy-the-fish** [comment]
Dasun, can you work from https://github.com/AgoraIO/API-Reference/tree/milestone-29-video-sdk-for-web-4.15.0 so we can push this with Video Calling for Web 4.15.0. 

Basically, you update the contents of https://github.com/AgoraIO/API-Reference/tree/milestone-29-video-sdk-for-web-4.15.0/video-sdk/android/3.x and https://github.com/AgoraIO/API-Reference/tree/milestone-29-video-sdk-for-web-4.15.0/voice-sdk/android/3.x with the zip output. 

@pmmgithub, is it really the same API ref for Video and Voice? I thought that there are classes and methods missing in voice?

**Comment by pmmgithub** [comment]
Hi Iain @billy-the-fish , yes we provide the same API ref for Video and Voice, despite that the voice SDK doesn't have video related APIs.
