### ISSUE TITLE
[Flutter]Screenshare document applies for windows only. Can we have the detailed document for iOS as well?

### ISSUE THREAD

**Issue by EmmaAzureAgora** [AgoraIO/Docs-Source#856]
Here the previous Flutter 5.x version screenshare. The section "Implement screen sharing on iOS" is missing in the new document. 
https://docs-preprod.agora.io/en/live-streaming-premium-legacy/screensharing_flutter?platform=Flutter

If customer follow up current document, they can't make screenshare working in Flutter iOS.

Thank you!

**Comment by saudsami** [comment]
Updated the doc to add screen sharing on iOS, Android, and macOS.

I also updated the Windows implementation to avoid using the deprecated `startScreenCaptureByScreenRect` method.
