### ISSUE TITLE
data center for chats

### ISSUE THREAD

**Issue by itscvenk** [AgoraIO/Docs-Source#861]
Hi!

https://docs.agora.io/en/agora-chat/get-started/enable?platform=web

It will be nice to know what is SGP1 : probably Singapore?
US1 is probably the United States of America
DE1 is probably Germany

The key word is "probably" . How can we be certain? Please update the document :-)

**Comment by billy-the-fish** [comment]
@haoxiuwen, any idea?

**Comment by haoxiuwen** [comment]
> @haoxiuwen, any idea?
itscvenk's understanding is right. The country code used here is indeed confusing.  We have submitted this issue to the GDXE  team.

**Comment by billy-the-fish** [comment]
Ok, I've looked at this again and this is inside console. The UI has already changed from when this screenshot was taken. Best is to update console with more understandable regions and then update the doc. 

I'm closing this issue, we can make a new one when console is updated.
