### ISSUE TITLE
Chat pricing example issue

### ISSUE THREAD

**Issue by marshallgosling** [AgoraIO/Docs-Source#863]
Hi,

The chat pricing example is incorrect.

[Chat Price Link](https://docs.agora.io/en/agora-chat/reference/pricing?platform=web)

`For example, a user buys the Starter Chat plan, which includes 5,000 MAU, and uses the Chat service in Project A and Project B. For that month, the total number of MAU for Project A is 2,370 and for Project B is 7,865. Therefore, the total cost of that month's Chat is as follows: (2,370 + 7,865 - 5,000) * 0.05 + 299 = US$560.75.`

It should be `(2,370 + 7,865 - 5,000) * 0.05 + 349 = US$610.75.`

<img width="914" alt="img1" src="https://user-images.githubusercontent.com/58164520/200996666-710df3d4-0ce1-4384-8371-f5dabfb4fbde.png">

**Comment by billy-the-fish** [comment]
Merged in https://github.com/AgoraIO/Docs-Source/pull/867.
