### ISSUE TITLE
Update the download for Agora Chat

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#865]
**Business case**: iOS SDKs should point to https://github.com/AgoraIO/AgoraChat_iOS.git

**Subject Matter Expert**: Lance

**Reviewers**:
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: Update https://docs.agora.io/en/sdks?platform=ios to point to iOS git repo and not npm. 

**Acceptance criteria**:  Download is correct. 

**Additional valuable information**:

**Comment by atovpeko** [comment]
Done in https://github.com/AgoraIO/Docs/pull/60
