### ISSUE TITLE
All platforms: enable open and close of the B frame when you call setvideoEncoderConfig

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#879]
* Business case - Some live customers need to turn on or off B frames during channel encoding and streaming
* Fix version - 4.1.0
* Subject Matter Expert - wangchunkun: wangchunkun@agora.io
* Review:
  * PM: TBD
  * Technical: wangchunkun
  * Language: Iain
* Scope -From [NMS-3626](https://jira.agoralab.co/browse/NMS-3626) `VideoEncoderConfiguration`  adds a structure member compressionPreference. Check the docs for all mentions of `VideoEncoderConfiguration` and ensure the code runs correctly. Do the updates for this feature in coordination with https://github.com/AgoraIO/Docs-Source/issues/704. 
  * Tasks:
    - [x] @saudsami: complete for Flutter
    - [x] @nirm2009: complete for Electron
    - [x] @hussain-khalid: complete for Unity
    - [x] @Kishan-Dhakan: complete for React Native
* Acceptance criteria - all docs must be technically correct, have no broken links, follow the templates provided and be written following the Google Developer style guide.
* Additional valuable information - Branches for all tickets must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone-34-vsdk-4.1.0.

**Comment by saudsami** [comment]
`compressionPreference` attribute is not available in Flutter 6.1.0
