### ISSUE TITLE
Update the version numbers, downloads,  release notes and API reference for this release

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#883]
**Business case**: The user must understand and use the latest version of the documentation

**Subject Matter Expert**: Who the doc team can ask technical questions.

**Reviewers**:
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**:  
- https://docs-staging-h7ipq6fad-agora-gdxe.vercel.app/en/api-reference  
        - https://api-ref.agora.io/en/video-sdk/electron/4.x/API/rtc_api_overview_ng.html
        - https://api-ref.agora.io/en/video-sdk/flutter/6.x/API/rtc_api_overview_ng.html
        - https://api-ref.agora.io/en/video-sdk/react-native/4.x/API/rtc_api_overview_ng.html
        - https://api-ref.agora.io/en/video-sdk/unity/4.x/API/rtc_api_overview_ng.html        
- https://docs-staging-h7ipq6fad-agora-gdxe.vercel.app/en/sdks?platform=android
- Release notes:
      - https://docs.agora.io/en/video-calling/reference/release-notes
      - https://docs.agora.io/en/interactive-live-streaming/reference/release-notes
      - https://docs.agora.io/en/voice-calling/reference/release-notes
    
**Acceptance criteria**: Criteria for this issue to be approved.

**Additional valuable information**: Anything else that will help with this issue.

**Comment by atovpeko** [comment]
The SDK downloads for 4.1.0 are:
Flutter:
Demo - download works
SDK - https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/littlegnal/dev/6.1.0
Electron:
Demo - https://github.com/AgoraIO-Extensions/Electron-SDK/tree/release/4.1.0/example/src/renderer/examples
SDK - https://github.com/AgoraIO-Extensions/Electron-SDK/tree/release/4.1.0
React Native:
Demo - https://github.com/AgoraIO-Extensions/react-native-agora/tree/release/4.1.0/example/src/examples
SDK -  https://github.com/AgoraIO-Extensions/react-native-agora/tree/release/4.1.0

**Comment by Cilla-luodan** [comment]
> 

The former understanding is correct. The x-platforms SDK has its target platforms, e.g. Flutter applies to iOS, Android, Windows, and macOS. If a feature only applies to Android, like Audio capture device test, it's marked as _Audio capture device test (Android)_, otherwise, it's for every platform.
When I  was answering your question, I checked the release notes for RN and Electron found a few mistakes. We'll correct them ASAP and let you know the updates.

**Comment by Cilla-luodan** [comment]
@atovpeko  here's the latest tag for x-platforms release notes: v4.1.0-all-platforms-1221

**Comment by billy-the-fish** [comment]
Is this for changes to all release notes? Certain ones, API refs?
