### ISSUE TITLE
Add speech to text pricing to the pricing guide

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#886]
**Business case**: Customers can easily estimate the cost of using speech to text. 

**Subject Matter Expert**: 曹跃 (Leon)

**Reviewers**:
  - *Technical*: 曹跃 (Leon)
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: https://docs.agora.io/en/video-calling/reference/pricing

**Acceptance criteria**: Users must easily estimate pricing for this feature. 

**Additional valuable information**: Additional valuable information - Branches for all tickets must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone37-speech-to-text

**Comment by atovpeko** [comment]
https://confluence.agoralab.co/pages/viewpage.action?pageId=976159327
