### ISSUE TITLE
Check the Postman API ref is complete

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#887]
**Business case**: customers will know every send and receive variable

**Subject Matter Expert**: Cao,Yue

**Reviewers**:
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: check https://documenter.getpostman.com/view/6319646/SVSLr9AM#be07209a-8d90-40e8-8c20-86e1687a5012 against https://docs-preprod.agora.io/en/live-streaming-premium-legacy/speech_to_text_rest?platform=Android and ensure all parameters are present and well explained. 

**Acceptance criteria**: Criteria for this issue to be approved.

**Additional valuable information**: Additional valuable information - Branches for all tickets must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone37-speech-to-text

**Comment by saudsami** [comment]
The reference is incomplete with some errors. Please see the following list

**POST acquire**
* Path parameter APPID is not defined
* Missing request header parameters: Content-Type and Authorization
* Missing response parameters: tokenName, createTs and instanceId
* Response code should be 2XX in case of success

**POST Start**
* Path parameters APPID not defined
* Query parameter builderToken not defined
* Missing request header parameter Authorization
* Description is incorrect. It talks about call recording
* Request body parameters are not explained
* Missing response parameters: taskId, createTs and status

**GET query**
* Path parameters APPID, taskID not defined
* Description is incorrect. It talks about call recording
* Missing request header parameter Authorization
* Missing response parameters: taskId, createTs and status

**DELETE Stop**
* Path parameters APPID, taskID not defined
* Description is incorrect. It talks about call recording
* Missing request header parameter Authorization

**Comment by billy-the-fish** [comment]
Please contant Frank Molinaro an ask for access to his postman account so you can update the API ref with the information in 
[RTT Document 大纲.md](https://github.com/AgoraIO/Docs-Source/files/10931239/RTT.Document.md)
