### ISSUE TITLE
Add codec parameter in Create method

### ISSUE THREAD

**Issue by Chuchun1991** [AgoraIO/Docs-Source#888]
Hi, codec parameter is added in request body of Create method. The content is as following:

- codec: String type. The encoding format of the output video. The following settings are supported:
  -VP8: Standard VP8.
  -H.264: (Default) Standard H.264.
If set to other value, the default is H.264 video encoding format.

You can put the "codec" parameter after "bitrate".

<img width="780" alt="image" src="https://user-images.githubusercontent.com/78007051/201812697-1bd1bef4-cb28-41a6-9349-af2ed4d4b2ec.png">
 And the [Request example](https://docs.agora.io/en/media-pull/reference/restful-api#request-example) should be:

```json
{
    "player": {
        "audioOptions": {
            "profile": 1
        },
        "videoOptions": {
            "width": 1920,
            "height": 1080,
            "frameRate": 15,
            "bitrate": 400,
            "codec": "VP8",
            "gop": 30,
            "fillMode": "fill"
        },
    "streamUrl": "rtmp://example.agora.io/live/class32/101",
    "channelName": "class32",
    "token": "2a784467d6",
    "uid": 101,
    "idleTimeout": 300,
    "playTs": 1575508644,
    "name": "test"
    }
}
```

**Comment by billy-the-fish** [comment]
Pr to staging please. Assign Anastasia as reviewer please.
