### ISSUE TITLE
Add Supported Players for MPD Files

### ISSUE THREAD

**Issue by Chuchun1991** [AgoraIO/Docs-Source#891]
https://docs.agora.io/en/cloud-recording/reference/rest-api/start
Hi, there is a requirement from PM:
When using the `standard` mode to generate a MPD file, the player supported are as follows:
- macOS：Movist/Chrome (47.0.2526.111+)
- Windows：Media Player/KM Player/VLC Player/Chrome (49.0.2623+)
- Linux：FFplay

You can add the information under the standard parameter as in the CN docs:

<img width="810" alt="image" src="https://user-images.githubusercontent.com/78007051/201856585-9115824b-0613-4dec-a614-768450ef25bc.png">

**Comment by billy-the-fish** [comment]
Pr to staging please. Assign Anastasia as reviewer please.
