### ISSUE TITLE
Unified Titles for API References

### ISSUE THREAD

**Issue by haoxiuwen** [AgoraIO/Docs-Source#896]
We have used the same titles for API References of all platforms/framewoks, except Flutter.
For Flutter, the version number is displayed at the bottom of the page:
![image](https://user-images.githubusercontent.com/95393471/202169551-065485f3-5077-4e87-b32b-340c68f0d075.png)

[Chat SDK for Android v1.0.8.zip](https://github.com/AgoraIO/Docs-Source/files/10021123/Chat.SDK.for.Android.v1.0.8.zip)
[Chat SDk for iOS v1.0.8.zip](https://github.com/AgoraIO/Docs-Source/files/10021124/Chat.SDk.for.iOS.v1.0.8.zip)
[Chat SDK for React Native v1.0.10.zip](https://github.com/AgoraIO/Docs-Source/files/10021126/Chat.SDK.for.React.Native.v1.0.10.zip)
[Chat SDK for Unity & Windows v1.0.8.zip](https://github.com/AgoraIO/Docs-Source/files/10021127/Chat.SDK.for.Unity.Windows.v1.0.8.zip)
[Chat SDK for WEB v1.0.7.zip](https://github.com/AgoraIO/Docs-Source/files/10021128/Chat.SDK.for.WEB.v1.0.7.zip)

**Comment by billy-the-fish** [comment]
@atovpeko, can you update the API ref with the updated reference please. .
