### ISSUE TITLE
Add warning about string UIDs to the join method in the Video SDK for Web API reference

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#915]
**Business case**: Improve app code for our end users

**Subject Matter Expert**: 

**Reviewers**:
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: https://api-ref.agora.io/en/video-sdk/web/4.x/interfaces/iagorartcclient.html#join. and https://api-ref.agora.io/en/video-sdk/web/4.x/globals.html#uid. Add the sentence "To ensure a better end-user experience, best practice is to use an number for `UID`" , and add a list of limitations for string UIDs. 

**Acceptance criteria**:  Documentation has a full list of limitations for string uids, is easy to understand and follows the Google Developer Style Guide. 

**Additional valuable information**:

**Comment by dengyaxi** [comment]
Fixed in 4.16.0 #1067
