### ISSUE TITLE
Mior Changes to Agora Chat Docs

### ISSUE THREAD

**Issue by haoxiuwen** [AgoraIO/Docs-Source#916]
Here are some minor changes to Agora Chat Docs.

**Comment by haoxiuwen** [comment]
Web - Retrieve Messages
https://docs.agora.io/en/agora-chat/client-api/messages/retrieve-messages?platform=web

"L" should be lower-case.

![image](https://user-images.githubusercontent.com/95393471/203893285-b0162de3-5f53-4dda-bebb-63186fe8e555.png)

**Comment by haoxiuwen** [comment]
Agora Chat techinical support personnel advise to add the "How to Collect SDK Logs" doc. 

Please check whether this doc is necessary and where to add it.


# How to Collect SDK Logs?

If you’re troubleshooting an issue with the Agora Chat SDK, Agora support team might ask you to send the SDK logs:

`SDK logs` record information about events that occurred in SDK. They can include errors and warnings as well as informational events.

By default, the SDK generates three log files, `easemob.log` and two `easemob_Y-m-d_H-M-S.log` files, each with a maximum size of 2048 KB (2 MB). These log files are encoded in UTF-8. The SDK writes the latest logs in `easemob.log`. When `easemob.log` is full, the SDK deletes the log file generated at the earliest time, renames `easemob.log` to the name of the current time-dependent file log file, and creates a new `easemob.log` to record the latest logs. 

## Collecting SDK logs

SDK logs can be found in the following directories, depending on your operating system.

### Android

1. Enable the debug mode:

```
 ChatClient.getInstance().setDebugMode(true);
```

2. open the logs directory `/sdcard/Android/data/{package name}/{appkey}/core_log/` which contains the SDK logs.

### iOS

#### Simulator 

1. Copy the `app sandbox path` printed by NSHomeDirectory().
2. In the **Finder** on your Mac system, select **Go** > **Go to Folder**. 
3. Press **Ctrl+V** to paste the path and press **Return**. 
4. open the logs directory `{app sandbox path}/Library/Application Support/HyphenateSDK/easemobLog/` which contains the SDK logs.

**Comment by haoxiuwen** [comment]
Add Moderation Error Code for Android/iOS/Unity 

Android: 
| 1200   |     MODERATION_FAILED           | The third-party content moderation service of Chat rates the message as "Reject". |
| 1299   |     THIRD_SERVER_FAILED         | Another service rather than the third-party content moderation service of Chat rates the message as "Reject". |

iOS

| 1200   |    AgoraChatErrorModerationFailed           | The third-party content moderation service  of Chat rates the message as "Reject". |
| 1299   |     AgoraChatErrorThirdServiceFailed         | Another service rather than the third-party content moderation service of Chat rates the message as "Reject". |

Unity
| 1200   |    THIRD_MODERATION_FAILED           | The third-party content moderation service of Chat rates the message as "Reject". |
| 1299   |     THIRD_DEFAULT_FAILED = 1299         | Another service rather than the third-party content moderation service of Chat rates the message as "Reject". |

**Comment by haoxiuwen** [comment]
Web - Group Attributes
https://docs.agora.io/en/agora-chat/client-api/chat-group/manage-group-attributes?platform=web

Add the following code in the red box:

ext: "group detail extensions",

![image](https://user-images.githubusercontent.com/95393471/204936951-99a09e71-313d-47fc-b38b-663c45f03984.png)

**Comment by haoxiuwen** [comment]
Web - Chat groups

https://docs.agora.io/en/agora-chat/client-api/chat-group/manage-chat-groups?platform=web

Replace the code in the red box with the following:

let option = {
  data: {
    groupname: "groupName",
    desc: "A description of a group",
    members: ["user1", "user2"],
    public: true,
    approval: true,
    allowinvites: true,
    inviteNeedConfirm: true,
    maxusers: 500,
    ext: "group detail extensions",
  },
};
conn.createGroup(option).then((res) => console.log(res));


![image](https://user-images.githubusercontent.com/95393471/204938142-553dcbb2-e55f-4356-a42c-12959eb3b0ca.png)

**Comment by haoxiuwen** [comment]
Android/iOS/Web/Flutter – Manage Chat Room Members
https://docs.agora.io/en/agora-chat/client-api/chat-room/manage-chatroom-members?platform=android

Messages from the members on the chat room allow list are sent preferentially. Therefore, add the related remarks.

Add the following content in the red box:

Messages sent by members in the chat room allow list are of high priority and will be delivered first, but there is no guarantee that they will be delivered. When the load is high, the server discards low-priority messages first. If the load is still high even then, the server discards high-priority messages.

 
![image](https://user-images.githubusercontent.com/95393471/205442377-2d2be43f-82bb-45b0-8d90-0df1cc8ddf33.png)

**Comment by haoxiuwen** [comment]
Reference – Message Overview

The content in the red boxes should be replaced by the following:

First and last red box: 5 KB should be replaced by 3 KB.

Second red box: The image cannot exceed 10 MB and the maximum data length of an image message is 3 KB.
Third red box: The voice file cannot exceed 10 MB and the maximum data length of a voice message is 3 KB.
Fourth red box: The video file cannot exceed 10 MB and the maximum data length of a video message is 3 KB.
Fifth red box: The attachment cannot exceed 10 MB and the maximum data length of a file message is 3 KB.
![image](https://user-images.githubusercontent.com/95393471/205442457-624a5460-f250-4cd4-8106-c66e092300fa.png)

**Comment by haoxiuwen** [comment]
Reference - HTTP status code
https://docs.agora.io/en/agora-chat/reference/http-status-codes?platform=web

Add the following content in the red box:

| 400 | illegal_argument | “message is too large” | The error message returned because the body of the message to be sent exceeds 40 KB. |

![image](https://user-images.githubusercontent.com/95393471/205442495-4f27a6cd-e831-40f2-8127-ecf92f38078f.png)

**Comment by haoxiuwen** [comment]
Web – Create and destroy a group

Replace the code in the two red boxes with “((res)”
![image](https://user-images.githubusercontent.com/95393471/205442553-001314c0-d959-4199-9373-16a8df1bfa9b.png)

**Comment by haoxiuwen** [comment]
Web – Send and receive messages
Add the section of how to send a location message.

Add the following content in the red box:

Send a location message
To send and receive a location message, you need to integrate a third-party map service provider. When sending a location message, you get the longitude and latitude information of the location from the map service provider; when receiving a location message, you extract the received longitude and latitude information and displays the location on the third-party map.

```javascript
const sendLocMsg = () => {
  let coords;
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function (position) {
      coords = position.coords;
      let option = {
        chatType: "singleChat",
        type: "loc",
        to: "username",
        addr: "West Road",
        buildingName: "Tower A",
        lat: Math.round(coords.latitude),
        lng: Math.round(coords.longitude),
      };
      let msg = WebIM.message.create(option);
      conn.send(msg);
    });
  }
};
```
![image](https://user-images.githubusercontent.com/95393471/205442603-a3c3edb0-da2d-4a2b-b676-6164af1115b0.png)

**Comment by haoxiuwen** [comment]
iOS – error code
Add the following error in the red box:
| 1101 | AgoraChatErrorPresenceCannotSubscribeSelf | You cannot subscribe to the presence status of yourself。|

![image](https://user-images.githubusercontent.com/95393471/205442656-88627b04-5c49-42bd-aa1e-bdbd3cbe4dc4.png)

**Comment by haoxiuwen** [comment]
REST - Create, delete and retrieve chat groups

Replace `desc` in the red box with "description".

![image](https://user-images.githubusercontent.com/95393471/205799483-898f8251-6a53-4e4f-839a-50b27d88b0a4.png)

**Comment by LanceAgora** [comment]
We've seen some incorrect information on this page. https://docs.agora.io/en/agora-chat/reference/limitations?platform=android, and all corresponding pages in other platforms/frameworks. 
The content in the bottom half part isn't relevant and we shall delete them, starting from 
https://docs.agora.io/en/agora-chat/reference/limitations?platform=android#enable-and-configure-chat
