### ISSUE TITLE
Picture in picture for virtual background

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#920]
**Business case**: rather than all users having a separate virtual background in their individual window, multiple users appear in the same window with a virtual background. .

**Subject Matter Expert**:  gaochun@agora.io

**Reviewers**:
  - *Technical*: gaochun@agora.io
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: [PRD](https://confluence.agoralab.co/pages/viewpage.action?pageId=991199393). Update https://docs.agora.io/en/video-calling/develop/virtual-background?platform=web to include this new functionality. 

**Acceptance criteria**: Doc must clearly show how to do picture-in-picture. 

**Additional valuable information**: Branches for all tickets must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone40-web4.16.0

**Comment by Kishan-Dhakan** [comment]
To proceed, I need access to https://confluence.agoralab.co/pages/viewpage.action?pageId=991199393.
