### ISSUE TITLE
Make quality statistics visible

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#924]
**Business case**: Improve user recognition of the brand by allowing users to perceive the quality of experience. This is for Caton rate, first frame output, Key events/counters

**Subject Matter Expert**: Who the doc team can ask technical questions.

**Reviewers**:
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: [PRD](https://confluence.agoralab.co/pages/viewpage.action?pageId=996147263), [HLD](https://confluence.agoralab.co/pages/viewpage.action?pageId=1138722399), [HLD](https://confluence.agoralab.co/pages/viewpage.action?pageId=1103758331)  Update the docs in https://docs.agora.io/en/agora-analytics/analyze/video-voice-sdk/data-insight#quality-overview to show this quality information.  However, best will be to get someone to walk us through the pages in analytics. 

**Acceptance criteria**: Enable users to easily understand usage statistics. 

**Additional valuable information**: Branches for all tickets must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone40-web4.16.0

**Comment by Kishan-Dhakan** [comment]
To proceed, I need access to [PRD](https://confluence.agoralab.co/pages/viewpage.action?pageId=996147263), [HLD](https://confluence.agoralab.co/pages/viewpage.action?pageId=1138722399), [HLD](https://confluence.agoralab.co/pages/viewpage.action?pageId=1103758331).
