### ISSUE TITLE
Updated API reference doc for 3.x Android

### ISSUE THREAD

**Issue by pmmgithub** [AgoraIO/Docs-Source#955]
Hi, based on feedback from engineers we updated the API ref doc for 3.x (video call, voice call, ILS) Android. We updated the description and parameter description for the `onLocalVideoStateChanged` callback. Please check the attached ZIP file. Thanks!
[html.zip](https://github.com/AgoraIO/Docs-Source/files/10130490/html.zip)

**Comment by billy-the-fish** [comment]
I assume this is to go in https://github.com/AgoraIO/API-Reference/tree/staging/video-sdk/android/3.x and https://github.com/AgoraIO/API-Reference/tree/staging/voice-sdk/android/3.x. 

While we are playing with API refs, please:
Change the version folder name in  https://github.com/AgoraIO/API-Reference/tree/staging/video-sdk/cocos-creator/1.3.1_3.x and  https://github.com/AgoraIO/API-Reference/tree/staging/voice-sdk/cocos-creator/1.3.1_3.x to 1.x, then update any links to this folder in this repo and in https://github.com/AgoraIO/Docs-Source-Legacy.

**Comment by billy-the-fish** [comment]
https://github.com/AgoraIO/API-Reference/pull/27/files and https://github.com/AgoraIO/Docs-Source-Legacy/pull/30/files. Both look good to me, I will publish with the weekly delivery tomorrow.
