### ISSUE TITLE
Docs for v4.1.0 Native Platform - Android, MacOS, iOS, Windows

### ISSUE THREAD

**Issue by Cilla-luodan** [AgoraIO/Docs-Source#957]
Hi Iain, please find the enclosed release notes and API ref for the v4.1.0 native SDK.
Release notes: 00-GitHub/agora_doc_source/markdown/RTC 4.x
API ref：00-GitHub/agora_doc_source/html/RTC 4.x

**Comment by billy-the-fish** [comment]
Hi @Cilla-luodan,
   Thanks for that. Can you please tell me which branch or the name of the tag you used to mark the delivery of the API ref. We are using a different template to generate the API ref from source.

**Comment by billy-the-fish** [comment]
@atovpeko, can you sort out the release notes please. There are discussions going on about the API ref.

**Comment by Cilla-luodan** [comment]
> Hi @Cilla-luodan, Thanks for that. Can you please tell me which branch or the name of the tag you used to mark the delivery of the API ref. We are using a different template to generate the API ref from source.

Currently we're not using variables in the source files, we just change the title and publish to A and change it again to publish to B.
If we use variable (it's called keydef in DITA), we must maintain 2 sets of ditamaps, one for Video and the other for Voice, that’s against the current platform-wise classified ditamaps and would be extra work for us.

**Comment by Cilla-luodan** [comment]
> 

The SDK is not released yet.
For the release date in the EN docs, I'm sure Emily and Iain will get release notice from the US product manager and they'll let you know.

**Comment by billy-the-fish** [comment]
Hi, not asking about variables. Theoretically when you make a change to the API ref, you make a branch in GitHub. When your work is done you merge your work to master or a branch dedicated to the release. In either case, you should make a tag in GIT to make the moment in time when the files are correct for that release. What I'm asking for is the branch or the tag where I can find this release of the API reference. We are using a different build template in DITA to build the docs so we need access to the correct source. 

If you could point me to the branch or tag please, that would be great.

**Comment by Cilla-luodan** [comment]
> 

Due to our recent continuous receipt of change requests, the document has not been finalized. I haven't created a tag yet, I'd rather create a tag when I get a release notice, is that okay for you?

**Comment by billy-the-fish** [comment]
That would be great, thank you. Apologies for making life complicated. 

The release notes in the link are finalized, yes?

**Comment by Cilla-luodan** [comment]
> 

Actually they're not finalized, we were asked to do some changes yesterday about the virtual background, and they're still discussing whether to put a "beta" tag for  MDUDP feature...
I'll let you know when they're finally fixed.

**Comment by billy-the-fish** [comment]
Ahhh, what fun,   @atovpeko, looks like there is more release note enjoyment for us all.

**Comment by Cilla-luodan** [comment]
Hi @billy-the-fish , please find this tag for the Native v4.1.0 release: https://github.com/AgoraIO/agora_doc_source/releases/tag/v4.1.0-native-en
The release notes are also updated: markdown/RTC 4.x

**Comment by billy-the-fish** [comment]
Awesome, thanks @Cilla-luodan. Would you mind casting a last eye over the docs so we can publish. I have sent an email with the links.
