### ISSUE TITLE
Update flexible-classroom/reference/supported-platforms

### ISSUE THREAD

**Issue by kelzr** [AgoraIO/Docs-Source#960]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/50696835/205263934-1defd0bb-9719-4af9-9aa2-a897913fae1f.png">

https://docs.agora.io/en/flexible-classroom/reference/supported-platforms?platform=web Delete these descriptions.

**Comment by billy-the-fish** [comment]
@Kishan-Dhakan , can you update the supported platforms section with this info please.

**Comment by billy-the-fish** [comment]
Can you merge to the correct milestone please: https://github.com/AgoraIO/Docs-Source/tree/milestone-26-flexible-classroom-uibuilder-release.
