### ISSUE TITLE
React Native UIKit instructions will cause project to fail

### ISSUE THREAD

**Issue by alekben** [AgoraIO/Docs-Source#965]
The React Native UIKit only supports up to agora-react-native 3.7.1.
Following the instructions in the UI Quickstart guide will result in the project importing agora-react-native 4.0.0, and the dependency in the ui kit package will fail.

Instructions for importing via npm and yarn should be changed to download agora-react-native 3.7.1 specifically.

**Comment by billy-the-fish** [comment]
Pr to staging please. Assign Anastasia as reviewer please.
