### ISSUE TITLE
Update v4.0.1 iOS API ref

### ISSUE THREAD

**Issue by Cilla-luodan** [AgoraIO/Docs-Source#971]
Hi Iain, there's a P0 priority issue that needs to be fixed in the v4.0.1 API ref.
The source file is attached, please update it ASAP, thanks.
[ios-ng.zip](https://github.com/AgoraIO/Docs-Source/files/10150567/ios-ng.zip)

**Comment by billy-the-fish** [comment]
Hi @Cilla-luodan, the zip that you sent does not implement the styling we use for the EN docs. Can you please point me to the tag/branch/pr/whatever where you made these changes to the source so I can see what needs to be done please.

**Comment by Cilla-luodan** [comment]
OK, I create a branch for this change, please go to: 4.0.1-bugfix-1207
