### ISSUE TITLE
Linux Java server gateway quick start guide in step 3, one line is miss

### ISSUE THREAD

**Issue by Monichen-agora** [AgoraIO/Docs-Source#984]
https://docs.agora.io/cn/server_gateway/integrate_java_sdk?platform=All%20Platforms

<img width="1004" alt="Screen Shot 2022-12-06 at 4 46 08 PM" src="https://user-images.githubusercontent.com/77456831/206060177-86c1720b-7437-4b5a-a1f4-529c096f37d9.png">

after mkdir there should be a "cd lib"
mkdir lib
cd lib                    >>>>>>missing
wget https://repo1.maven.org/maven2/io/agora/rtc/linux-sdk/3.7.200.21/linux-sdk-3.7.200.21.jar
jar xvf linux-sdk-3.7.200.21.jar

BTW, the Chinese version has the same error.  Already asked the doc team to fix it.

**Comment by saudsami** [comment]
Fixed
