### ISSUE TITLE
Update C# API Ref for 3.x SDK

### ISSUE THREAD

**Issue by lemon-chen** [AgoraIO/Docs-Source#986]
The current C# API Reference contains addInjectStreamUrl related methods and classes. This service is no longer available and should be removed from the doc. 

Attached are the source files for the Voice and Video SDK API ref. Please review and publish them. Thanks！
[voice c#.zip](https://github.com/AgoraIO/Docs-Source/files/10173960/voice.c.zip)
[video c#.zip](https://github.com/AgoraIO/Docs-Source/files/10173961/video.c.zip)

**Comment by billy-the-fish** [comment]
@nirm2009, this is for the 3.x API.
