### ISSUE TITLE
Rewrite the ai noise suppression docs to use the authentication mechanism

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#989]
**Business case**: Easily add this feature to their apps

**Subject Matter Expert**: 
  - *Technical*: 
  - *Language*: Anastasia
  - *PM*: Pavan

**Scope**: The implementation docs included in https://github.com/AgoraIO/Docs-Source/blob/ai-noise-supression-rewrite/video-calling/develop/ai-noise-suppression.mdx. 
- [x] Android: @saudsami 
- [x] iOS: @nirm2009 
- [x] Web: @hussain-khalid 
- [x] macOS: @nirm2009 
- [x] Windows: @Pankajg123  
- [x] Electron: @Kishan-Dhakan 
- [x] Unity: @nirm2009 
- [x] Flutter: @saudsami 
- [x] React-Native: @Kishan-Dhakan 

**Acceptance criteria**: Developers can easily enable noise suppression using this doc. 

**Additional valuable information**: Branch from and merge to https://github.com/AgoraIO/Docs-Source/tree/ai-noise-supression-rewrite.

**Comment by Pankajg123** [comment]
Closing the issue.
