### ISSUE TITLE
Third Party cloud recording vendor id 

### ISSUE THREAD

**Issue by mjjabarullah** [AgoraIO/Docs-Source#991]
Please include third part cloud recording vendor id for all the storage vendor .. i cannot find it anywhere in your documentation

**Comment by billy-the-fish** [comment]
Kishan, please check against the old docs and update. 
Pr to staging please. Assign Anastasia as reviewer please.

**Comment by Kishan-Dhakan** [comment]
Hi @mjjabarullah, the vendor IDs and storageConfig options are documented here: https://docs.agora.io/en/cloud-recording/reference/rest-api/start?platform=RESTful#storageConfig. If you need any more information, please feel free to re-open this issue. Thank you.
